/* Reconstructed C source for Python module 'aiohttp_socks._deprecated'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_aiohttp_socks$_deprecated @ 0x1412055B0
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_aiohttp_socks$_deprecated;
PyDictObject *moduledict_aiohttp_socks$_deprecated;

/* Module constants: 41 entries recovered from blob chunk 'aiohttp_socks._deprecated'. */
static struct ModuleConstants {
    PyObject *const_str_plain_warnings;  /* [0] str = 'warnings' */
    PyObject *const_str_plain_warn;  /* [1] str = 'warn' */
    PyObject *const_str_digest_e049ccf5;  /* [2] str = 'SocksConnector is deprecated. Use ProxyConnector instead.' */
    PyObject *const_str_plain_DeprecationWarning;  /* [3] str = 'DeprecationWarning' */
    PyObject *const_tuple_1;  /* [4] tuple = (3,) */
    PyObject *const_tuple_1_1;  /* [5] tuple = ('stacklevel',) */
    PyObject *const_str_plain__warn_about_connector;  /* [6] str = '_warn_about_connector' */
    PyObject *const_str_plain_proxy_type;  /* [7] str = 'proxy_type' */
    PyObject *const_str_plain_ProxyType;  /* [8] str = 'ProxyType' */
    PyObject *const_str_plain_from_url;  /* [9] str = 'from_url' */
    PyObject *const_str_plain_origin;  /* [10] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [11] str = 'has_location' */
    PyObject *const_str_plain_python_socks;  /* [12] str = 'python_socks' */
    PyObject *const_tuple_3;  /* [13] tuple = ('ProxyError', 'ProxyConnectionError', 'ProxyType') */
    PyObject *const_str_plain_ProxyError;  /* [14] str = 'ProxyError' */
    PyObject *const_str_plain_ProxyConnectionError;  /* [15] str = 'ProxyConnectionError' */
    PyObject *const_str_plain_connector;  /* [16] str = 'connector' */
    PyObject *const_tuple_1_2;  /* [17] tuple = ('ProxyConnector',) */
    PyObject *const_str_plain_ProxyConnector;  /* [18] str = 'ProxyConnector' */
    PyObject *const_tuple_1_3;  /* [19] tuple = ('object',) */
    PyObject *const_str_plain___prepare__;  /* [20] str = '__prepare__' */
    PyObject *const_str_plain_SocksVer;  /* [21] str = 'SocksVer' */
    PyObject *const_str_plain___getitem__;  /* [22] str = '__getitem__' */
    PyObject *const_str_digest_b9509dfb;  /* [23] str = '%s.__prepare__() must return a mapping, not %s' */
    PyObject *const_str_digest_5fec942c;  /* [24] str = '<metaclass>' */
    PyObject *const_str_digest_eec1f652;  /* [25] str = 'aiohttp_socks._deprecated' */
    PyObject *const_str_plain___qualname__;  /* [26] str = '__qualname__' */
    PyObject *const_str_plain_SOCKS4;  /* [27] str = 'SOCKS4' */
    PyObject *const_int_pos_2;  /* [28] int = 2 */
    PyObject *const_str_plain_SOCKS5;  /* [29] str = 'SOCKS5' */
    PyObject *const_str_plain___orig_bases__;  /* [30] str = '__orig_bases__' */
    PyObject *const_str_plain_SocksConnector;  /* [31] str = 'SocksConnector' */
    PyObject *const_str_digest_b478d8ad;  /* [32] str = 'SocksConnector.__init__' */
    PyObject *const_str_digest_c7980ace;  /* [33] str = 'SocksConnector.from_url' */
    PyObject *const_str_plain_SocksError;  /* [34] str = 'SocksError' */
    PyObject *const_str_plain_SocksConnectionError;  /* [35] str = 'SocksConnectionError' */
    PyObject *const_str_digest_00d7d269;  /* [36] str = 'aiohttp_socks\\_deprecated.py' */
    PyObject *const_str_digest_e36849dc;  /* [37] str = '<module aiohttp_socks._deprecated>' */
    PyObject *const_tuple_1_4;  /* [38] tuple = ('__class__',) */
    PyObject *const_tuple_4;  /* [39] tuple = ('self', 'socks_ver', 'kwargs', '__class__') */
    PyObject *const_tuple_4_1;  /* [40] tuple = ('cls', 'url', 'kwargs', '__class__') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("aiohttp_socks._deprecated"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0___warn_about_connector;   /* '_warn_about_connector' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__python_socks;   /* 'python_socks' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__connector;   /* 'connector' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__ProxyConnector;   /* 'ProxyConnector' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__SocksConnectionError;   /* 'SocksConnectionError' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__SocksConnectionError;   /* 'SocksConnectionError' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6___deprecated$gt$;   /* '_deprecated>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def _warn_about_connector(stacklevel)
 *  qualname: _warn_about_connector   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$_warn_about_connector(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def python_socks(ProxyError, ProxyConnectionError, ProxyType)
 *  qualname: python_socks   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$python_socks(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def connector(ProxyConnector)
 *  qualname: connector   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$connector(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ProxyConnector(object)
 *  qualname: ProxyConnector   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$ProxyConnector(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def SocksConnectionError(__class__)
 *  qualname: <module aiohttp_socks._deprecated>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$SocksConnectionError(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def SocksConnectionError(self, socks_ver, kwargs, __class__)
 *  qualname: <module aiohttp_socks._deprecated>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$SocksConnectionError(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _deprecated>(cls, url, kwargs, __class__)
 *  qualname: <module aiohttp_socks._deprecated>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated$_deprecated$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_aiohttp_socks$_deprecated$_warn_about_connector(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _warn_about_connector(stacklevel): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$python_socks(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def python_socks(ProxyError, ProxyConnectionError, ProxyType): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$connector(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def connector(ProxyConnector): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$ProxyConnector(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ProxyConnector(object): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$SocksConnectionError(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def SocksConnectionError(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$SocksConnectionError(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def SocksConnectionError(self, socks_ver, kwargs, __class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated$_deprecated$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _deprecated>(cls, url, kwargs, __class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_aiohttp_socks$_deprecated(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_aiohttp_socks$_deprecated = module;
    moduledict_aiohttp_socks$_deprecated = MODULE_DICT(module_aiohttp_socks$_deprecated);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1412055B0
     *
     * Recovered imports (detected from module constants): */
    /*   import aiohttp_socks._deprecated */
    /*   import SocksConnector.__init__ */
    /*   import SocksConnector.from_url */

    return module;
}

