/* Reconstructed C source for Python module 'aiohttp_socks.connector'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_aiohttp_socks$connector @ 0x141213720
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_aiohttp_socks$connector;
PyDictObject *moduledict_aiohttp_socks$connector;

/* Module constants: 112 entries recovered from blob chunk 'aiohttp_socks.connector'. */
static struct ModuleConstants {
    PyObject *const_str_plain_hostname;  /* [0] str = 'hostname' */
    PyObject *const_str_plain_host;  /* [1] str = 'host' */
    PyObject *const_str_plain_port;  /* [2] str = 'port' */
    PyObject *const_str_plain_family;  /* [3] str = 'family' */
    PyObject *const_str_plain_proto;  /* [4] str = 'proto' */
    PyObject *const_str_plain_flags;  /* [5] str = 'flags' */
    PyObject *const_str_plain_resolve;  /* [6] str = 'resolve' */
    PyObject *const_str_digest_39d2534d;  /* [7] str = 'NoResolver.resolve' */
    PyObject *const_str_digest_67562e58;  /* [8] str = 'NoResolver.close' */
    PyObject *const_str_plain__writer;  /* [9] str = '_writer' */
    PyObject *const_str_plain_NoResolver;  /* [10] str = 'NoResolver' */
    PyObject *const_str_plain_resolver;  /* [11] str = 'resolver' */
    PyObject *const_str_plain__proxy_type;  /* [12] str = '_proxy_type' */
    PyObject *const_str_plain__proxy_host;  /* [13] str = '_proxy_host' */
    PyObject *const_str_plain__proxy_port;  /* [14] str = '_proxy_port' */
    PyObject *const_str_plain__proxy_username;  /* [15] str = '_proxy_username' */
    PyObject *const_str_plain__proxy_password;  /* [16] str = '_proxy_password' */
    PyObject *const_str_plain__rdns;  /* [17] str = '_rdns' */
    PyObject *const_str_plain__proxy_ssl;  /* [18] str = '_proxy_ssl' */
    PyObject *const_str_plain_Proxy;  /* [19] str = 'Proxy' */
    PyObject *const_str_plain_self;  /* [20] str = 'self' */
    PyObject *const_tuple_7;  /* [21] tuple = ('proxy_type', 'host', 'port', 'username', 'password', 'rdns... */
    PyObject *const_str_plain_kwargs;  /* [22] str = 'kwargs' */
    PyObject *const_tuple_1;  /* [23] tuple = ('timeout',) */
    PyObject *const_str_plain_sock_connect;  /* [24] str = 'sock_connect' */
    PyObject *const_str_plain_connect;  /* [25] str = 'connect' */
    PyObject *const_str_plain_ssl;  /* [26] str = 'ssl' */
    PyObject *const_tuple_4;  /* [27] tuple = ('dest_host', 'dest_port', 'dest_ssl', 'timeout') */
    PyObject *const_str_plain_writer;  /* [28] str = 'writer' */
    PyObject *const_str_plain_transport;  /* [29] str = 'transport' */
    PyObject *const_str_plain__ResponseHandler;  /* [30] str = '_ResponseHandler' */
    PyObject *const_str_plain__loop;  /* [31] str = '_loop' */
    PyObject *const_tuple_2;  /* [32] tuple = ('loop', 'writer') */
    PyObject *const_str_plain_set_protocol;  /* [33] str = 'set_protocol' */
    PyObject *const_str_plain_connection_made;  /* [34] str = 'connection_made' */
    PyObject *const_str_plain__wrap_create_connection;  /* [35] str = '_wrap_create_connection' */
    PyObject *const_str_digest_042b8c97;  /* [36] str = 'ProxyConnector._wrap_create_connection' */
    PyObject *const_str_plain_parse_proxy_url;  /* [37] str = 'parse_proxy_url' */
    PyObject *const_str_plain_proxy_type;  /* [38] str = 'proxy_type' */
    PyObject *const_str_plain_username;  /* [39] str = 'username' */
    PyObject *const_str_plain_password;  /* [40] str = 'password' */
    PyObject *const_str_plain__proxy_infos;  /* [41] str = '_proxy_infos' */
    PyObject *const_str_plain_rdns;  /* [42] str = 'rdns' */
    PyObject *const_str_plain_forward;  /* [43] str = 'forward' */
    PyObject *const_tuple_7_1;  /* [44] tuple = ('proxy_type', 'host', 'port', 'username', 'password', 'rdns... */
    PyObject *const_str_plain_proxy;  /* [45] str = 'proxy' */
    PyObject *const_str_digest_0dde630c;  /* [46] str = 'ChainProxyConnector._wrap_create_connection' */
    PyObject *const_str_plain_ProxyInfo;  /* [47] str = 'ProxyInfo' */
    PyObject *const_tuple_5;  /* [48] tuple = ('proxy_type', 'host', 'port', 'username', 'password') */
    PyObject *const_str_plain_infos;  /* [49] str = 'infos' */
    PyObject *const_str_plain_origin;  /* [50] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [51] str = 'has_location' */
    PyObject *const_str_plain_asyncio;  /* [52] str = 'asyncio' */
    PyObject *const_str_plain_socket;  /* [53] str = 'socket' */
    PyObject *const_str_plain_typing;  /* [54] str = 'typing' */
    PyObject *const_tuple_2_1;  /* [55] tuple = ('BaseTransport', 'StreamWriter') */
    PyObject *const_str_plain_BaseTransport;  /* [56] str = 'BaseTransport' */
    PyObject *const_str_plain_StreamWriter;  /* [57] str = 'StreamWriter' */
    PyObject *const_str_plain_Iterable;  /* [58] str = 'Iterable' */
    PyObject *const_str_plain_aiohttp;  /* [59] str = 'aiohttp' */
    PyObject *const_tuple_1_1;  /* [60] tuple = ('TCPConnector',) */
    PyObject *const_str_plain_TCPConnector;  /* [61] str = 'TCPConnector' */
    PyObject *const_str_digest_4221ee2d;  /* [62] str = 'aiohttp.abc' */
    PyObject *const_tuple_1_2;  /* [63] tuple = ('AbstractResolver',) */
    PyObject *const_str_plain_AbstractResolver;  /* [64] str = 'AbstractResolver' */
    PyObject *const_str_digest_ec266c59;  /* [65] str = 'aiohttp.client_proto' */
    PyObject *const_tuple_1_3;  /* [66] tuple = ('ResponseHandler',) */
    PyObject *const_str_plain_ResponseHandler;  /* [67] str = 'ResponseHandler' */
    PyObject *const_str_plain_python_socks;  /* [68] str = 'python_socks' */
    PyObject *const_tuple_2_2;  /* [69] tuple = ('ProxyType', 'parse_proxy_url') */
    PyObject *const_str_plain_ProxyType;  /* [70] str = 'ProxyType' */
    PyObject *const_str_digest_d9ee1570;  /* [71] str = 'python_socks.async_.asyncio.v2' */
    PyObject *const_tuple_1_4;  /* [72] tuple = ('Proxy',) */
    PyObject *const_str_plain___prepare__;  /* [73] str = '__prepare__' */
    PyObject *const_str_plain___getitem__;  /* [74] str = '__getitem__' */
    PyObject *const_str_digest_b9509dfb;  /* [75] str = '%s.__prepare__() must return a mapping, not %s' */
    PyObject *const_str_digest_5fec942c;  /* [76] str = '<metaclass>' */
    PyObject *const_str_digest_de3f10cf;  /* [77] str = 'aiohttp_socks.connector' */
    PyObject *const_str_plain___qualname__;  /* [78] str = '__qualname__' */
    PyObject *const_str_plain_AF_INET;  /* [79] str = 'AF_INET' */
    PyObject *const_str_plain___orig_bases__;  /* [80] str = '__orig_bases__' */
    PyObject *const_str_digest_6cc3aaa1;  /* [81] str = '\n    To fix issue https://github.com/romis2012/aiohttp-soc... */
    PyObject *const_str_plain_loop;  /* [82] str = 'loop' */
    PyObject *const_str_plain_AbstractEventLoop;  /* [83] str = 'AbstractEventLoop' */
    PyObject *const_str_digest_e6199511;  /* [84] str = '_ResponseHandler.__init__' */
    PyObject *const_str_plain_ProxyConnector;  /* [85] str = 'ProxyConnector' */
    PyObject *const_str_plain_SOCKS5;  /* [86] str = 'SOCKS5' */
    PyObject *const_str_digest_7f85f3b9;  /* [87] str = 'ProxyConnector.__init__' */
    PyObject *const_str_plain_from_url;  /* [88] str = 'from_url' */
    PyObject *const_str_digest_6bd0ab33;  /* [89] str = 'ProxyConnector.from_url' */
    PyObject *const_str_plain_NamedTuple;  /* [90] str = 'NamedTuple' */
    PyObject *const_str_plain_str;  /* [91] str = 'str' */
    PyObject *const_str_plain_Optional;  /* [92] str = 'Optional' */
    PyObject *const_str_plain_bool;  /* [93] str = 'bool' */
    PyObject *const_str_plain_ChainProxyConnector;  /* [94] str = 'ChainProxyConnector' */
    PyObject *const_str_plain_proxy_infos;  /* [95] str = 'proxy_infos' */
    PyObject *const_str_digest_b8f74ce7;  /* [96] str = 'ChainProxyConnector.__init__' */
    PyObject *const_str_plain_urls;  /* [97] str = 'urls' */
    PyObject *const_str_plain_from_urls;  /* [98] str = 'from_urls' */
    PyObject *const_str_digest_0e86e74b;  /* [99] str = 'ChainProxyConnector.from_urls' */
    PyObject *const_str_digest_ad415309;  /* [100] str = 'aiohttp_socks\\connector.py' */
    PyObject *const_str_digest_0e4665c5;  /* [101] str = '<module aiohttp_socks.connector>' */
    PyObject *const_tuple_1_5;  /* [102] tuple = ('__class__',) */
    PyObject *const_tuple_4_1;  /* [103] tuple = ('self', 'proxy_infos', 'kwargs', '__class__') */
    PyObject *const_tuple_10;  /* [104] tuple = ('self', 'proxy_type', 'host', 'port', 'username', 'password... */
    PyObject *const_tuple_4_2;  /* [105] tuple = ('self', 'loop', 'writer', '__class__') */
    PyObject *const_tuple_14;  /* [106] tuple = ('self', 'protocol_factory', 'host', 'port', 'ssl', 'kwargs'... */
    PyObject *const_tuple_12;  /* [107] tuple = ('self', 'protocol_factory', 'host', 'port', 'ssl', 'kwargs'... */
    PyObject *const_tuple_1_6;  /* [108] tuple = ('self',) */
    PyObject *const_tuple_8;  /* [109] tuple = ('cls', 'url', 'kwargs', 'proxy_type', 'host', 'port', 'user... */
    PyObject *const_tuple_11;  /* [110] tuple = ('cls', 'urls', 'kwargs', 'infos', 'url', 'proxy_type', 'hos... */
    PyObject *const_tuple_4_3;  /* [111] tuple = ('self', 'host', 'port', 'family') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("aiohttp_socks.connector"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__self;   /* 'self' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__kwargs;   /* 'kwargs' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__ssl;   /* 'ssl' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3___loop;   /* '_loop' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__forward;   /* 'forward' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__ProxyInfo;   /* 'ProxyInfo' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__typing;   /* 'typing' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__aiohttp;   /* 'aiohttp' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__AbstractResolver;   /* 'AbstractResolver' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__ResponseHandler;   /* 'ResponseHandler' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__python_socks;   /* 'python_socks' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11____prepare__;   /* '__prepare__' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__from_urls;   /* 'from_urls' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__connector$gt$;   /* 'connector>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__connector$gt$;   /* 'connector>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__connector$gt$;   /* 'connector>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def self(proxy_type, host, port, username, password, rdns, proxy_ssl)
 *  qualname: self   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$self(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def kwargs(timeout)
 *  qualname: kwargs   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$kwargs(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ssl(dest_host, dest_port, dest_ssl, timeout)
 *  qualname: ssl   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$ssl(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def typing(BaseTransport, StreamWriter)
 *  qualname: typing   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$typing(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def aiohttp(TCPConnector)
 *  qualname: aiohttp.abc   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$aiohttp(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def AbstractResolver(AbstractResolver)
 *  qualname: aiohttp.abc   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$AbstractResolver(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ResponseHandler(ResponseHandler)
 *  qualname: aiohttp.client_proto   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$ResponseHandler(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def python_socks(ProxyType, parse_proxy_url)
 *  qualname: python_socks.async_.asyncio.v2   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$python_socks(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def __prepare__(Proxy)
 *  qualname: python_socks.async_.asyncio.v2   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$__prepare__(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def from_urls(__class__)
 *  qualname: <module aiohttp_socks.connector>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$from_urls(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def connector>(self, proxy_infos, kwargs, __class__)
 *  qualname: <module aiohttp_socks.connector>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def connector>(self, proxy_type, host, port, username, password, rdns, proxy_ssl, kwargs, __class__)
 *  qualname: <module aiohttp_socks.connector>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def connector>(self, loop, writer, __class__)
 *  qualname: <module aiohttp_socks.connector>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: ProxyConnector
 *   methods recovered: 1
 *   class body was also compiled to native code */
static PyObject *impl_aiohttp_socks$connector$ProxyConnector$_loop(PyThreadState *tstate, PyObject **python_pars);  /* def ProxyConnector._loop(loop, writer) line 0 */

/* Class: ChainProxyConnector
 *   methods recovered: 2
 *   class body was also compiled to native code */
static PyObject *impl_aiohttp_socks$connector$ChainProxyConnector$forward(PyThreadState *tstate, PyObject **python_pars);  /* def ChainProxyConnector.forward(proxy_type, host, port, username, password, rdns, forward) line 0 */
static PyObject *impl_aiohttp_socks$connector$ChainProxyConnector$ProxyInfo(PyThreadState *tstate, PyObject **python_pars);  /* def ChainProxyConnector.ProxyInfo(proxy_type, host, port, username, password) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_aiohttp_socks$connector$self(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def self(proxy_type, host, port, username, password, rdns, proxy_ssl): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$kwargs(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def kwargs(timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$ssl(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ssl(dest_host, dest_port, dest_ssl, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$typing(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def typing(BaseTransport, StreamWriter): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$aiohttp(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def aiohttp(TCPConnector): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$AbstractResolver(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def AbstractResolver(AbstractResolver): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$ResponseHandler(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ResponseHandler(ResponseHandler): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$python_socks(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def python_socks(ProxyType, parse_proxy_url): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$__prepare__(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def __prepare__(Proxy): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$from_urls(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def from_urls(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def connector>(self, proxy_infos, kwargs, __class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def connector>(self, proxy_type, host, port, username, password, rdns, proxy_ssl, kwargs, __class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$connector$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def connector>(self, loop, writer, __class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$ProxyConnector$_loop(PyThreadState *tstate, PyObject **python_pars) {
    /* def ProxyConnector._loop(loop, writer): ... */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$ChainProxyConnector$forward(PyThreadState *tstate, PyObject **python_pars) {
    /* def ChainProxyConnector.forward(proxy_type, host, port, username, password, rdns, forward): ... */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector$ChainProxyConnector$ProxyInfo(PyThreadState *tstate, PyObject **python_pars) {
    /* def ChainProxyConnector.ProxyInfo(proxy_type, host, port, username, password): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_aiohttp_socks$connector(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_aiohttp_socks$connector = module;
    moduledict_aiohttp_socks$connector = MODULE_DICT(module_aiohttp_socks$connector);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141213720
     *
     * Recovered imports (detected from module constants): */
    /*   import NoResolver.resolve */
    /*   import NoResolver.close */
    /*   import ProxyConnector._wrap_create_connection */
    /*   import ChainProxyConnector._wrap_create_connection */
    /*   import aiohttp.abc */
    /*   import aiohttp.client_proto */
    /*   import python_socks.async_.asyncio.v2 */
    /*   import aiohttp_socks.connector */
    /*   import _ResponseHandler.__init__ */
    /*   import ProxyConnector.__init__ */
    /*   import ProxyConnector.from_url */
    /*   import ChainProxyConnector.__init__ */
    /*   import ChainProxyConnector.from_urls */

    return module;
}

