/* Reconstructed C source for Python module 'aiohttp_socks.utils'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_aiohttp_socks$utils @ 0x14121EE50
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_aiohttp_socks$utils;
PyDictObject *moduledict_aiohttp_socks$utils;

/* Module constants: 47 entries recovered from blob chunk 'aiohttp_socks.utils'. */
static struct ModuleConstants {
    PyObject *const_str_plain_warnings;  /* [0] str = 'warnings' */
    PyObject *const_str_plain_warn;  /* [1] str = 'warn' */
    PyObject *const_str_digest_49641895;  /* [2] str = 'open_connection is deprecated. Use https://github.com/romis... */
    PyObject *const_str_plain_DeprecationWarning;  /* [3] str = 'DeprecationWarning' */
    PyObject *const_tuple_1;  /* [4] tuple = (2,) */
    PyObject *const_tuple_1_1;  /* [5] tuple = ('stacklevel',) */
    PyObject *const_str_plain_host;  /* [6] str = 'host' */
    PyObject *const_str_plain_port;  /* [7] str = 'port' */
    PyObject *const_str_digest_fe7617a3;  /* [8] str = 'host and port must be specified' */
    PyObject *const_str_plain_loop;  /* [9] str = 'loop' */
    PyObject *const_str_plain_asyncio;  /* [10] str = 'asyncio' */
    PyObject *const_str_plain_get_event_loop;  /* [11] str = 'get_event_loop' */
    PyObject *const_str_plain_proxy_url;  /* [12] str = 'proxy_url' */
    PyObject *const_str_plain_parse_proxy_url;  /* [13] str = 'parse_proxy_url' */
    PyObject *const_str_plain_Proxy;  /* [14] str = 'Proxy' */
    PyObject *const_str_plain_create;  /* [15] str = 'create' */
    PyObject *const_str_plain_proxy_type;  /* [16] str = 'proxy_type' */
    PyObject *const_str_plain_proxy_host;  /* [17] str = 'proxy_host' */
    PyObject *const_str_plain_proxy_port;  /* [18] str = 'proxy_port' */
    PyObject *const_str_plain_username;  /* [19] str = 'username' */
    PyObject *const_str_plain_password;  /* [20] str = 'password' */
    PyObject *const_str_plain_rdns;  /* [21] str = 'rdns' */
    PyObject *const_tuple_7;  /* [22] tuple = ('proxy_type', 'host', 'port', 'username', 'password', 'rdns... */
    PyObject *const_str_plain_connect;  /* [23] str = 'connect' */
    PyObject *const_str_plain_open_connection;  /* [24] str = 'open_connection' */
    PyObject *const_str_plain_sock;  /* [25] str = 'sock' */
    PyObject *const_str_plain_kwargs;  /* [26] str = 'kwargs' */
    PyObject *const_str_digest_35f88e43;  /* [27] str = 'create_connection is deprecated. Use https://github.com/rom... */
    PyObject *const_str_plain_protocol_factory;  /* [28] str = 'protocol_factory' */
    PyObject *const_str_digest_b359935c;  /* [29] str = 'protocol_factory must be specified' */
    PyObject *const_str_plain_create_connection;  /* [30] str = 'create_connection' */
    PyObject *const_str_plain_origin;  /* [31] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [32] str = 'has_location' */
    PyObject *const_str_plain_python_socks;  /* [33] str = 'python_socks' */
    PyObject *const_tuple_2;  /* [34] tuple = ('ProxyType', 'parse_proxy_url') */
    PyObject *const_str_plain_ProxyType;  /* [35] str = 'ProxyType' */
    PyObject *const_str_digest_fea8d5fd;  /* [36] str = 'python_socks.async_.asyncio' */
    PyObject *const_tuple_1_2;  /* [37] tuple = ('Proxy',) */
    PyObject *const_tuple_3;  /* [38] tuple = (None, None, None) */
    PyObject *const_str_plain_SOCKS5;  /* [39] str = 'SOCKS5' */
    PyObject *const_str_digest_f528764d;  /* [40] str = '127.0.0.1' */
    PyObject *const_int_pos_1080;  /* [41] int = 1080 */
    PyObject *const_tuple_4;  /* [42] tuple = (None, None, None, None) */
    PyObject *const_str_digest_c640a1c3;  /* [43] str = 'aiohttp_socks\\utils.py' */
    PyObject *const_str_digest_bd354fe7;  /* [44] str = '<module aiohttp_socks.utils>' */
    PyObject *const_tuple_14;  /* [45] tuple = ('proxy_url', 'protocol_factory', 'host', 'port', 'proxy_typ... */
    PyObject *const_tuple_13;  /* [46] tuple = ('proxy_url', 'host', 'port', 'proxy_type', 'proxy_host', 'p... */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("aiohttp_socks.utils"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__host;   /* 'host' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__rdns;   /* 'rdns' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__python_socks;   /* 'python_socks' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__ProxyType;   /* 'ProxyType' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__utils$gt$;   /* 'utils>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__utils$gt$;   /* 'utils>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def host(stacklevel)
 *  qualname: host   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$host(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def rdns(proxy_type, host, port, username, password, rdns, loop)
 *  qualname: rdns   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$rdns(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def python_socks(ProxyType, parse_proxy_url)
 *  qualname: python_socks.async_.asyncio   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$python_socks(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ProxyType(Proxy)
 *  qualname: python_socks.async_.asyncio   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$ProxyType(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def utils>(proxy_url, protocol_factory, host, port, proxy_type, proxy_host, proxy_port, username, password, rdns, loop, kwargs, proxy, sock)
 *  qualname: <module aiohttp_socks.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def utils>(proxy_url, host, port, proxy_type, proxy_host, proxy_port, username, password, rdns, loop, kwargs, proxy, sock)
 *  qualname: <module aiohttp_socks.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_aiohttp_socks$utils$host(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def host(stacklevel): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils$rdns(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def rdns(proxy_type, host, port, username, password, rdns, loop): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils$python_socks(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def python_socks(ProxyType, parse_proxy_url): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils$ProxyType(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ProxyType(Proxy): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def utils>(proxy_url, protocol_factory, host, port, proxy_type, proxy_host, proxy_port, username, password, rdns, loop, kwargs, proxy, sock): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def utils>(proxy_url, host, port, proxy_type, proxy_host, proxy_port, username, password, rdns, loop, kwargs, proxy, sock): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_aiohttp_socks$utils(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_aiohttp_socks$utils = module;
    moduledict_aiohttp_socks$utils = MODULE_DICT(module_aiohttp_socks$utils);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x14121EE50
     *
     * Recovered imports (detected from module constants): */
    /*   import python_socks.async_.asyncio */
    /*   import 127.0.0.1 */

    return module;
}

