/* Reconstructed C source for Python module 'core.ipv6.firewall_manager'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$ipv6$firewall_manager @ 0x141906690
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$ipv6$firewall_manager;
PyDictObject *moduledict_core$ipv6$firewall_manager;

/* Module constants: 66 entries recovered from blob chunk 'core.ipv6.firewall_manager'. */
static struct ModuleConstants {
    PyObject *const_str_plain_subprocess;  /* [0] str = 'subprocess' */
    PyObject *const_str_plain_run;  /* [1] str = 'run' */
    PyObject *const_str_plain_netsh;  /* [2] str = 'netsh' */
    PyObject *const_str_plain_advfirewall;  /* [3] str = 'advfirewall' */
    PyObject *const_str_plain_firewall;  /* [4] str = 'firewall' */
    PyObject *const_str_plain_add;  /* [5] str = 'add' */
    PyObject *const_str_plain_rule;  /* [6] str = 'rule' */
    PyObject *const_str_digest_49dec07b;  /* [7] str = 'name=' */
    PyObject *const_str_digest_65f9e670;  /* [8] str = 'dir=in' */
    PyObject *const_str_digest_850d30ea;  /* [9] str = 'action=allow' */
    PyObject *const_str_digest_13f3d198;  /* [10] str = 'protocol=TCP' */
    PyObject *const_str_digest_ba541e38;  /* [11] str = 'localport=' */
    PyObject *const_str_plain_CREATE_NO_WINDOW;  /* [12] str = 'CREATE_NO_WINDOW' */
    PyObject *const_tuple_3;  /* [13] tuple = ('capture_output', 'text', 'creationflags') */
    PyObject *const_str_plain_returncode;  /* [14] str = 'returncode' */
    PyObject *const_str_digest_b0afb854;  /* [15] str = 'Thêm luật Firewall cho port ' */
    PyObject *const_str_digest_6dd1d987;  /* [16] str = ' thất bại: ' */
    PyObject *const_str_plain_stderr;  /* [17] str = 'stderr' */
    PyObject *const_str_plain_strip;  /* [18] str = 'strip' */
    PyObject *const_str_plain_logger;  /* [19] str = 'logger' */
    PyObject *const_str_plain_info;  /* [20] str = 'info' */
    PyObject *const_str_digest_d342bb2e;  /* [21] str = 'Firewall: Đã mở rule ' */
    PyObject *const_str_digest_35358f18;  /* [22] str = ' (port ' */
    PyObject *const_str_digest_9371d7a2;  /* [23] str = ')' */
    PyObject *const_str_plain_FirewallManager;  /* [24] str = 'FirewallManager' */
    PyObject *const_str_plain_RULE_PREFIX;  /* [25] str = 'RULE_PREFIX' */
    PyObject *const_str_plain_replace;  /* [26] str = 'replace' */
    PyObject *const_tuple_2;  /* [27] tuple = (' ', '_') */
    PyObject *const_str_plain__Range;  /* [28] str = '_Range' */
    PyObject *const_str_digest_336d5ebc;  /* [29] str = '-' */
    PyObject *const_str_plain_remove_rule;  /* [30] str = 'remove_rule' */
    PyObject *const_str_digest_4c28bb0a;  /* [31] str = '⚡ Firewall: Đã mở nhanh rule dải cổng ' */
    PyObject *const_str_digest_2002e39a;  /* [32] str = ' (ports: ' */
    PyObject *const_str_plain_warning;  /* [33] str = 'warning' */
    PyObject *const_str_digest_914c8fc6;  /* [34] str = 'Lỗi mở firewall range ' */
    PyObject *const_str_digest_e2654927;  /* [35] str = ': ' */
    PyObject *const_str_digest_08094dd5;  /* [36] str = 'Mở 1 rule duy nhất cho toàn bộ dải cổng của group (Tối ưu t... */
    PyObject *const_str_plain_delete;  /* [37] str = 'delete' */
    PyObject *const_str_digest_24dd00db;  /* [38] str = 'Firewall: Đã xóa rule ' */
    PyObject *const_str_plain_origin;  /* [39] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [40] str = 'has_location' */
    PyObject *const_str_plain_logging;  /* [41] str = 'logging' */
    PyObject *const_str_plain_getLogger;  /* [42] str = 'getLogger' */
    PyObject *const_tuple_1;  /* [43] tuple = ('IPv6Proxy',) */
    PyObject *const_int_digest_9ab98b1f;  /* [44] int = 134217728 */
    PyObject *const_str_digest_ab2bcfd3;  /* [45] str = 'core.ipv6.firewall_manager' */
    PyObject *const_str_plain___qualname__;  /* [46] str = '__qualname__' */
    PyObject *const_str_plain_IPv6Proxy_;  /* [47] str = 'IPv6Proxy_' */
    PyObject *const_str_plain_add_rule;  /* [48] str = 'add_rule' */
    PyObject *const_str_digest_15d8305b;  /* [49] str = 'FirewallManager.add_rule' */
    PyObject *const_dict_3;  /* [50] dict = {'group_name': 'str', 'start_port': 'int', 'end_port': 'int'... */
    PyObject *const_str_plain_add_range_rule;  /* [51] str = 'add_range_rule' */
    PyObject *const_str_digest_15953425;  /* [52] str = 'FirewallManager.add_range_rule' */
    PyObject *const_dict_1;  /* [53] dict = {'group_name': 'str'} */
    PyObject *const_str_plain_remove_range_rule;  /* [54] str = 'remove_range_rule' */
    PyObject *const_str_digest_f5718076;  /* [55] str = 'FirewallManager.remove_range_rule' */
    PyObject *const_str_digest_7911831f;  /* [56] str = 'FirewallManager.remove_rule' */
    PyObject *const_str_plain_make_rule_name;  /* [57] str = 'make_rule_name' */
    PyObject *const_str_digest_bd605507;  /* [58] str = 'FirewallManager.make_rule_name' */
    PyObject *const_str_digest_cdf90d91;  /* [59] str = 'core\\ipv6\\firewall_manager.py' */
    PyObject *const_str_digest_ad2021c3;  /* [60] str = '<module core.ipv6.firewall_manager>' */
    PyObject *const_tuple_6;  /* [61] tuple = ('group_name', 'start_port', 'end_port', 'rule_name', 'port_... */
    PyObject *const_tuple_3_1;  /* [62] tuple = ('rule_name', 'port', 'result') */
    PyObject *const_tuple_3_2;  /* [63] tuple = ('group_name', 'port', 'safe_group') */
    PyObject *const_tuple_2_1;  /* [64] tuple = ('group_name', 'rule_name') */
    PyObject *const_tuple_1_1;  /* [65] tuple = ('rule_name',) */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.ipv6.firewall_manager"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__CREATE_NO_WINDOW;   /* 'CREATE_NO_WINDOW' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__make_rule_name;   /* 'make_rule_name' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__firewall_manager$gt$;   /* 'firewall_manager>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__firewall_manager$gt$;   /* 'firewall_manager>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__firewall_manager$gt$;   /* 'firewall_manager>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def CREATE_NO_WINDOW(capture_output, text, creationflags)
 *  qualname: CREATE_NO_WINDOW   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$CREATE_NO_WINDOW(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(IPv6Proxy)
 *  qualname: core.ipv6.firewall_manager   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def make_rule_name(group_name, start_port, end_port, rule_name, port_range, result)
 *  qualname: <module core.ipv6.firewall_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$make_rule_name(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def firewall_manager>(rule_name, port, result)
 *  qualname: <module core.ipv6.firewall_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def firewall_manager>(group_name, port, safe_group)
 *  qualname: <module core.ipv6.firewall_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def firewall_manager>(group_name, rule_name)
 *  qualname: <module core.ipv6.firewall_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$ipv6$firewall_manager$CREATE_NO_WINDOW(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def CREATE_NO_WINDOW(capture_output, text, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$firewall_manager$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(IPv6Proxy): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$firewall_manager$make_rule_name(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def make_rule_name(group_name, start_port, end_port, rule_name, port_range, result): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def firewall_manager>(rule_name, port, result): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def firewall_manager>(group_name, port, safe_group): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$firewall_manager$firewall_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def firewall_manager>(group_name, rule_name): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$ipv6$firewall_manager(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$ipv6$firewall_manager = module;
    moduledict_core$ipv6$firewall_manager = MODULE_DICT(module_core$ipv6$firewall_manager);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141906690
     *
     * Recovered imports (detected from module constants): */
    /*   import core.ipv6.firewall_manager */
    /*   import FirewallManager.add_rule */
    /*   import FirewallManager.add_range_rule */
    /*   import FirewallManager.remove_range_rule */
    /*   import FirewallManager.remove_rule */
    /*   import FirewallManager.make_rule_name */

    return module;
}

