/* Reconstructed C source for Python module 'core.ipv6.ipv6_manager'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$ipv6$ipv6_manager @ 0x141952E80
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$ipv6$ipv6_manager;
PyDictObject *moduledict_core$ipv6$ipv6_manager;

/* Module constants: 297 entries recovered from blob chunk 'core.ipv6.ipv6_manager'. */
static struct ModuleConstants {
    PyObject *const_str_plain_pathlib;  /* [0] str = 'pathlib' */
    PyObject *const_tuple_1;  /* [1] tuple = ('Path',) */
    PyObject *const_str_plain_Path;  /* [2] str = 'Path' */
    PyObject *const_str_plain_frozen;  /* [3] str = 'frozen' */
    PyObject *const_str_plain_executable;  /* [4] str = 'executable' */
    PyObject *const_str_plain_resolve;  /* [5] str = 'resolve' */
    PyObject *const_str_plain_data;  /* [6] str = 'data' */
    PyObject *const_str_plain_data_dir;  /* [7] str = 'data_dir' */
    PyObject *const_str_plain_mkdir;  /* [8] str = 'mkdir' */
    PyObject *const_tuple_2;  /* [9] tuple = (True, True) */
    PyObject *const_tuple_2_1;  /* [10] tuple = ('parents', 'exist_ok') */
    PyObject *const_str_digest_f75a7f48;  /* [11] str = 'custom_subnet.txt' */
    PyObject *const_str_plain_custom_prefix_file;  /* [12] str = 'custom_prefix_file' */
    PyObject *const_str_digest_8c3b9a2a;  /* [13] str = 'custom_interface.txt' */
    PyObject *const_str_plain_custom_interface_file;  /* [14] str = 'custom_interface_file' */
    PyObject *const_str_plain_configs;  /* [15] str = 'configs' */
    PyObject *const_tuple_2_2;  /* [16] tuple = ('custom_subnet.txt', 'custom_interface.txt') */
    PyObject *const_str_plain_legacy_configs_dir;  /* [17] str = 'legacy_configs_dir' */
    PyObject *const_str_plain_self;  /* [18] str = 'self' */
    PyObject *const_str_plain_shutil;  /* [19] str = 'shutil' */
    PyObject *const_str_plain_copy2;  /* [20] str = 'copy2' */
    PyObject *const_str_plain_logger;  /* [21] str = 'logger' */
    PyObject *const_str_plain_info;  /* [22] str = 'info' */
    PyObject *const_str_digest_17fbb4c4;  /* [23] str = '📦 [Auto-Migration] Đã chuyển ' */
    PyObject *const_str_digest_ab10e246;  /* [24] str = ' vào data/' */
    PyObject *const_str_plain_interface_name;  /* [25] str = 'interface_name' */
    PyObject *const_str_plain_prefix;  /* [26] str = 'prefix' */
    PyObject *const_str_plain__luid;  /* [27] str = '_luid' */
    PyObject *const_str_plain__added_addresses;  /* [28] str = '_added_addresses' */
    PyObject *const_str_plain_subprocess;  /* [29] str = 'subprocess' */
    PyObject *const_str_plain_run;  /* [30] str = 'run' */
    PyObject *const_str_plain_CREATE_NO_WINDOW;  /* [31] str = 'CREATE_NO_WINDOW' */
    PyObject *const_tuple_1_1;  /* [32] tuple = (['netsh', 'interface', 'ipv6', 'show', 'addresses'],) */
    PyObject *const_tuple_3;  /* [33] tuple = ('capture_output', 'text', 'creationflags') */
    PyObject *const_str_plain_stdout;  /* [34] str = 'stdout' */
    PyObject *const_str_plain_re;  /* [35] str = 're' */
    PyObject *const_tuple_1_2;  /* [36] tuple = ('([0-9a-fA-F]{1,4}(?::[0-9a-fA-F]{0,4}){2,7})(?:%\\d+)?\\s*... */
    PyObject *const_str_plain_splitlines;  /* [37] str = 'splitlines' */
    PyObject *const_str_plain_match;  /* [38] str = 'match' */
    PyObject *const_str_digest_f4bdf93b;  /* [39] str = '^Interface\\s+(\\d+):\\s+(.+)$' */
    PyObject *const_str_plain_group;  /* [40] str = 'group' */
    PyObject *const_tuple_1_3;  /* [41] tuple = (2,) */
    PyObject *const_str_plain_strip;  /* [42] str = 'strip' */
    PyObject *const_str_plain_iface_map;  /* [43] str = 'iface_map' */
    PyObject *const_str_plain_startswith;  /* [44] str = 'startswith' */
    PyObject *const_tuple_1_4;  /* [45] tuple = (('Addr Type', '---', '---------'),) */
    PyObject *const_str_plain_ipv6_re;  /* [46] str = 'ipv6_re' */
    PyObject *const_str_plain_search;  /* [47] str = 'search' */
    PyObject *const_str_plain_current_iface;  /* [48] str = 'current_iface' */
    PyObject *const_tuple_1_5;  /* [49] tuple = (1,) */
    PyObject *const_str_plain_ipaddress;  /* [50] str = 'ipaddress' */
    PyObject *const_str_plain_IPv6Address;  /* [51] str = 'IPv6Address' */
    PyObject *const_str_plain_is_link_local;  /* [52] str = 'is_link_local' */
    PyObject *const_str_plain_is_loopback;  /* [53] str = 'is_loopback' */
    PyObject *const_str_plain_is_multicast;  /* [54] str = 'is_multicast' */
    PyObject *const_str_plain_is_private;  /* [55] str = 'is_private' */
    PyObject *const_str_plain_IPv6Network;  /* [56] str = 'IPv6Network' */
    PyObject *const_str_digest_36110e42;  /* [57] str = '/64' */
    PyObject *const_tuple_1_6;  /* [58] tuple = (False,) */
    PyObject *const_tuple_1_7;  /* [59] tuple = ('strict',) */
    PyObject *const_tuple_4;  /* [60] tuple = ('public', 'temporary', 'dhcp', 'other') */
    PyObject *const_str_plain_append;  /* [61] str = 'append' */
    PyObject *const_str_plain_ip;  /* [62] str = 'ip' */
    PyObject *const_str_plain_is_dynamic;  /* [63] str = 'is_dynamic' */
    PyObject *const_str_plain_sort;  /* [64] str = 'sort' */
    PyObject *const_str_digest_11659e6b;  /* [65] str = '<lambda>' */
    PyObject *const_str_digest_4785c65a;  /* [66] str = 'IPv6Manager.get_available_interfaces.<locals>.<lambda>' */
    PyObject *const_tuple_1_8;  /* [67] tuple = ('key',) */
    PyObject *const_str_plain_interfaces_list;  /* [68] str = 'interfaces_list' */
    PyObject *const_str_digest_83ed897c;  /* [69] str = 'Không có IPv6 Public' */
    PyObject *const_str_plain_has_ipv6;  /* [70] str = 'has_ipv6' */
    PyObject *const_str_plain_is_current;  /* [71] str = 'is_current' */
    PyObject *const_str_digest_cc7d9130;  /* [72] str = 'Quét và trả về danh sách tất cả card mạng khả dụng trên hệ ... */
    PyObject *const_str_digest_e9e2aa81;  /* [73] str = 'utf-8' */
    PyObject *const_tuple_3_1;  /* [74] tuple = (None, None, None) */
    PyObject *const_str_plain_val;  /* [75] str = 'val' */
    PyObject *const_str_plain__find_active_interface_name;  /* [76] str = '_find_active_interface_name' */
    PyObject *const_str_plain_Custom;  /* [77] str = 'Custom' */
    PyObject *const_str_plain__get_interface_luid;  /* [78] str = '_get_interface_luid' */
    PyObject *const_str_digest_4ee69a50;  /* [79] str = 'Sử dụng custom prefix IPv6 từ file: ' */
    PyObject *const_str_digest_1171ae58;  /* [80] str = ' trên card ' */
    PyObject *const_str_plain_error;  /* [81] str = 'error' */
    PyObject *const_str_digest_a928c27a;  /* [82] str = 'Lỗi đọc custom prefix: ' */
    PyObject *const_str_plain_saved_iface;  /* [83] str = 'saved_iface' */
    PyObject *const_str_plain_candidates;  /* [84] str = 'candidates' */
    PyObject *const_tuple_1_9;  /* [85] tuple = ('Không tìm thấy dải IPv6 khả dụng trên máy',) */
    PyObject *const_str_digest_830ee947;  /* [86] str = 'IPv6Manager.detect_interface_and_prefix.<locals>.<lambda>' */
    PyObject *const_int_pos_3;  /* [87] int = 3 */
    PyObject *const_int_pos_4;  /* [88] int = 4 */
    PyObject *const_str_digest_c6824b6b;  /* [89] str = "Đã phát hiện Card mạng '" */
    PyObject *const_str_digest_3a8a19a5;  /* [90] str = "' với prefix IPv6 " */
    PyObject *const_str_digest_87566411;  /* [91] str = ' (nguồn: ' */
    PyObject *const_int_pos_2;  /* [92] int = 2 */
    PyObject *const_str_digest_9371d7a2;  /* [93] str = ')' */
    PyObject *const_str_plain_write;  /* [94] str = 'write' */
    PyObject *const_str_plain_detect_interface_and_prefix;  /* [95] str = 'detect_interface_and_prefix' */
    PyObject *const_tuple_1_10;  /* [96] tuple = ('force_iface',) */
    PyObject *const_str_digest_2fa73f54;  /* [97] str = 'Lỗi lưu custom interface: ' */
    PyObject *const_str_digest_282e68d0;  /* [98] str = 'Lưu card mạng được chọn vào cấu hình cố định' */
    PyObject *const_str_plain_HAS_WIN32_IPHLP;  /* [99] str = 'HAS_WIN32_IPHLP' */
    PyObject *const_str_plain_c_uint64;  /* [100] str = 'c_uint64' */
    PyObject *const_str_plain_iphlpapi;  /* [101] str = 'iphlpapi' */
    PyObject *const_str_plain_ConvertInterfaceAliasToLuid;  /* [102] str = 'ConvertInterfaceAliasToLuid' */
    PyObject *const_str_plain_byref;  /* [103] str = 'byref' */
    PyObject *const_str_plain_value;  /* [104] str = 'value' */
    PyObject *const_tuple_1_11;  /* [105] tuple = (['netsh', 'interface', 'ipv6', 'show', 'interfaces'],) */
    PyObject *const_str_plain_isdigit;  /* [106] str = 'isdigit' */
    PyObject *const_str_plain_ConvertInterfaceIndexToLuid;  /* [107] str = 'ConvertInterfaceIndexToLuid' */
    PyObject *const_str_plain_luid;  /* [108] str = 'luid' */
    PyObject *const_str_plain_MIB_UNICASTIPADDRESS_ROW;  /* [109] str = 'MIB_UNICASTIPADDRESS_ROW' */
    PyObject *const_str_plain_InitializeUnicastIpAddressEntry;  /* [110] str = 'InitializeUnicastIpAddressEntry' */
    PyObject *const_str_plain_InterfaceLuid;  /* [111] str = 'InterfaceLuid' */
    PyObject *const_str_plain_AF_INET6;  /* [112] str = 'AF_INET6' */
    PyObject *const_str_plain_Address;  /* [113] str = 'Address' */
    PyObject *const_str_plain_si_family;  /* [114] str = 'si_family' */
    PyObject *const_str_plain_Ipv6;  /* [115] str = 'Ipv6' */
    PyObject *const_str_plain_sin6_family;  /* [116] str = 'sin6_family' */
    PyObject *const_str_plain_packed;  /* [117] str = 'packed' */
    PyObject *const_str_plain_row;  /* [118] str = 'row' */
    PyObject *const_str_plain_sin6_addr;  /* [119] str = 'sin6_addr' */
    PyObject *const_str_plain_OnLinkPrefixLength;  /* [120] str = 'OnLinkPrefixLength' */
    PyObject *const_str_plain_SkipAsSource;  /* [121] str = 'SkipAsSource' */
    PyObject *const_int_digest_7ba34a7c;  /* [122] int = 4294967295 */
    PyObject *const_str_plain_ValidLifetime;  /* [123] str = 'ValidLifetime' */
    PyObject *const_str_plain_PreferredLifetime;  /* [124] str = 'PreferredLifetime' */
    PyObject *const_str_plain_CreateUnicastIpAddressEntry;  /* [125] str = 'CreateUnicastIpAddressEntry' */
    PyObject *const_tuple_2_3;  /* [126] tuple = (0, 5010) */
    PyObject *const_str_plain_DeleteUnicastIpAddressEntry;  /* [127] str = 'DeleteUnicastIpAddressEntry' */
    PyObject *const_tuple_2_4;  /* [128] tuple = (0, 1168) */
    PyObject *const_str_plain_Ethernet;  /* [129] str = 'Ethernet' */
    PyObject *const_str_plain_manual;  /* [130] str = 'manual' */
    PyObject *const_str_plain_del_list;  /* [131] str = 'del_list' */
    PyObject *const_str_plain_remove_addresses_batch;  /* [132] str = 'remove_addresses_batch' */
    PyObject *const_str_plain_clear;  /* [133] str = 'clear' */
    PyObject *const_tuple_1_12;  /* [134] tuple = ('Đã dọn dẹp sạch toàn bộ IPv6 Manual cũ trên các card mạng'... */
    PyObject *const_str_plain_warning;  /* [135] str = 'warning' */
    PyObject *const_str_digest_846789f9;  /* [136] str = 'Lỗi flush manual IPv6: ' */
    PyObject *const_str_digest_c587b054;  /* [137] str = 'Dọn dẹp sạch sẽ toàn bộ các IP gán Manual rác cũ trên card ... */
    PyObject *const_str_digest_3e208843;  /* [138] str = 'Chưa phát hiện dải IPv6' */
    PyObject *const_str_plain_network_address;  /* [139] str = 'network_address' */
    PyObject *const_str_plain_secrets;  /* [140] str = 'secrets' */
    PyObject *const_str_plain_randbits;  /* [141] str = 'randbits' */
    PyObject *const_tuple_1_13;  /* [142] tuple = (64,) */
    PyObject *const_str_plain_prefix_int;  /* [143] str = 'prefix_int' */
    PyObject *const_str_plain_addresses;  /* [144] str = 'addresses' */
    PyObject *const_str_plain__win32_add_ipv6;  /* [145] str = '_win32_add_ipv6' */
    PyObject *const_str_plain_add;  /* [146] str = 'add' */
    PyObject *const_str_plain_debug;  /* [147] str = 'debug' */
    PyObject *const_str_digest_3bbe3a88;  /* [148] str = 'Win32 add IPv6 fail, fallback netsh: ' */
    PyObject *const_str_plain_netsh;  /* [149] str = 'netsh' */
    PyObject *const_str_plain_interface;  /* [150] str = 'interface' */
    PyObject *const_str_plain_ipv6;  /* [151] str = 'ipv6' */
    PyObject *const_str_plain_address;  /* [152] str = 'address' */
    PyObject *const_str_plain_returncode;  /* [153] str = 'returncode' */
    PyObject *const_str_digest_4506ec48;  /* [154] str = 'Gán IPv6 ' */
    PyObject *const_str_digest_6dd1d987;  /* [155] str = ' thất bại: ' */
    PyObject *const_str_plain_stderr;  /* [156] str = 'stderr' */
    PyObject *const_str_plain_success_addrs;  /* [157] str = 'success_addrs' */
    PyObject *const_str_digest_8618818a;  /* [158] str = '⚡ [Win32 Native] Đã gán siêu tốc ' */
    PyObject *const_str_digest_e31083b6;  /* [159] str = ' địa chỉ IPv6 vào card mạng!' */
    PyObject *const_str_digest_d36cd4bc;  /* [160] str = 'Win32 API gán IPv6 lỗi: ' */
    PyObject *const_str_digest_997070db;  /* [161] str = ', fallback sang netsh pool...' */
    PyObject *const_dict_1;  /* [162] dict = {'addr': 'str'} */
    PyObject *const_str_plain__add_single_netsh;  /* [163] str = '_add_single_netsh' */
    PyObject *const_str_digest_cfb679bf;  /* [164] str = 'IPv6Manager.add_addresses_batch.<locals>._add_single_netsh' */
    PyObject *const_str_plain_concurrent;  /* [165] str = 'concurrent' */
    PyObject *const_str_plain_futures;  /* [166] str = 'futures' */
    PyObject *const_str_plain_ThreadPoolExecutor;  /* [167] str = 'ThreadPoolExecutor' */
    PyObject *const_tuple_1_14;  /* [168] tuple = ('max_workers',) */
    PyObject *const_str_plain_map;  /* [169] str = 'map' */
    PyObject *const_str_digest_13481df9;  /* [170] str = '⚡ [netsh Pool] Đã gán ' */
    PyObject *const_str_digest_6510d2e9;  /* [171] str = 'Gán đồng loạt hàng loạt địa chỉ IPv6 vào card mạng qua Win3... */
    PyObject *const_str_plain__win32_del_ipv6;  /* [172] str = '_win32_del_ipv6' */
    PyObject *const_str_plain_discard;  /* [173] str = 'discard' */
    PyObject *const_str_plain_delete;  /* [174] str = 'delete' */
    PyObject *const_str_digest_736d90a2;  /* [175] str = '⚡ [Win32 Native] Đã dọn dẹp ' */
    PyObject *const_str_digest_1ebab7a9;  /* [176] str = ' địa chỉ IPv6 trên card mạng' */
    PyObject *const_str_digest_0c02134f;  /* [177] str = 'Win32 API xóa IPv6 lỗi: ' */
    PyObject *const_str_plain__del_single_netsh;  /* [178] str = '_del_single_netsh' */
    PyObject *const_str_digest_32a74db9;  /* [179] str = 'IPv6Manager.remove_addresses_batch.<locals>._del_single_net... */
    PyObject *const_str_digest_c322c1b5;  /* [180] str = '⚡ [netsh Pool] Đã dọn dẹp ' */
    PyObject *const_str_digest_48796238;  /* [181] str = 'Xóa đồng loạt hàng loạt địa chỉ IPv6 trên card mạng qua Win... */
    PyObject *const_str_plain_unlink;  /* [182] str = 'unlink' */
    PyObject *const_str_digest_e3d6a563;  /* [183] str = 'Lỗi lưu custom prefix: ' */
    PyObject *const_str_plain_origin;  /* [184] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [185] str = 'has_location' */
    PyObject *const_str_plain_logging;  /* [186] str = 'logging' */
    PyObject *const_str_plain_sys;  /* [187] str = 'sys' */
    PyObject *const_str_plain_ctypes;  /* [188] str = 'ctypes' */
    PyObject *const_str_plain_wintypes;  /* [189] str = 'wintypes' */
    PyObject *const_str_digest_a45bd416;  /* [190] str = 'concurrent.futures' */
    PyObject *const_str_plain_getLogger;  /* [191] str = 'getLogger' */
    PyObject *const_tuple_1_15;  /* [192] tuple = ('IPv6Proxy',) */
    PyObject *const_int_digest_9ab98b1f;  /* [193] int = 134217728 */
    PyObject *const_int_pos_23;  /* [194] int = 23 */
    PyObject *const_str_plain_WinDLL;  /* [195] str = 'WinDLL' */
    PyObject *const_tuple_1_16;  /* [196] tuple = ('iphlpapi.dll',) */
    PyObject *const_str_plain_Structure;  /* [197] str = 'Structure' */
    PyObject *const_str_plain___prepare__;  /* [198] str = '__prepare__' */
    PyObject *const_str_plain_SOCKADDR_IN6;  /* [199] str = 'SOCKADDR_IN6' */
    PyObject *const_str_plain___getitem__;  /* [200] str = '__getitem__' */
    PyObject *const_str_digest_b9509dfb;  /* [201] str = '%s.__prepare__() must return a mapping, not %s' */
    PyObject *const_str_digest_5fec942c;  /* [202] str = '<metaclass>' */
    PyObject *const_str_digest_5f57e4dd;  /* [203] str = 'core.ipv6.ipv6_manager' */
    PyObject *const_str_plain___qualname__;  /* [204] str = '__qualname__' */
    PyObject *const_str_plain_USHORT;  /* [205] str = 'USHORT' */
    PyObject *const_str_plain_sin6_port;  /* [206] str = 'sin6_port' */
    PyObject *const_str_plain_sin6_flowinfo;  /* [207] str = 'sin6_flowinfo' */
    PyObject *const_str_plain_ULONG;  /* [208] str = 'ULONG' */
    PyObject *const_str_plain_c_ubyte;  /* [209] str = 'c_ubyte' */
    PyObject *const_int_pos_16;  /* [210] int = 16 */
    PyObject *const_str_plain_sin6_scope_id;  /* [211] str = 'sin6_scope_id' */
    PyObject *const_str_plain__fields_;  /* [212] str = '_fields_' */
    PyObject *const_str_plain___orig_bases__;  /* [213] str = '__orig_bases__' */
    PyObject *const_str_plain_Union;  /* [214] str = 'Union' */
    PyObject *const_str_plain_SOCKADDR_INET;  /* [215] str = 'SOCKADDR_INET' */
    PyObject *const_str_plain_Ipv4;  /* [216] str = 'Ipv4' */
    PyObject *const_str_plain_c_byte;  /* [217] str = 'c_byte' */
    PyObject *const_str_plain_InterfaceIndex;  /* [218] str = 'InterfaceIndex' */
    PyObject *const_str_plain_DWORD;  /* [219] str = 'DWORD' */
    PyObject *const_str_plain_PrefixOrigin;  /* [220] str = 'PrefixOrigin' */
    PyObject *const_str_plain_c_int;  /* [221] str = 'c_int' */
    PyObject *const_str_plain_SuffixOrigin;  /* [222] str = 'SuffixOrigin' */
    PyObject *const_str_plain_c_uint8;  /* [223] str = 'c_uint8' */
    PyObject *const_str_plain_DadState;  /* [224] str = 'DadState' */
    PyObject *const_str_plain_ScopeId;  /* [225] str = 'ScopeId' */
    PyObject *const_str_plain_CreationTimeStamp;  /* [226] str = 'CreationTimeStamp' */
    PyObject *const_str_plain_c_int64;  /* [227] str = 'c_int64' */
    PyObject *const_str_plain_POINTER;  /* [228] str = 'POINTER' */
    PyObject *const_str_plain_argtypes;  /* [229] str = 'argtypes' */
    PyObject *const_str_plain_restype;  /* [230] str = 'restype' */
    PyObject *const_str_plain_LPCWSTR;  /* [231] str = 'LPCWSTR' */
    PyObject *const_str_plain_e;  /* [232] str = 'e' */
    PyObject *const_str_digest_c549db3b;  /* [233] str = 'Không thể khởi tạo Win32 IP Helper API: ' */
    PyObject *const_str_plain_IPv6Manager;  /* [234] str = 'IPv6Manager' */
    PyObject *const_tuple_1_17;  /* [235] tuple = (None,) */
    PyObject *const_str_digest_7d15ac38;  /* [236] str = 'IPv6Manager.__init__' */
    PyObject *const_dict_1_1;  /* [237] dict = {'return': 'list'} */
    PyObject *const_str_plain_get_available_interfaces;  /* [238] str = 'get_available_interfaces' */
    PyObject *const_str_digest_b776b702;  /* [239] str = 'IPv6Manager.get_available_interfaces' */
    PyObject *const_dict_1_2;  /* [240] dict = {'force_iface': 'str'} */
    PyObject *const_str_digest_76aebdd9;  /* [241] str = 'IPv6Manager.detect_interface_and_prefix' */
    PyObject *const_dict_2;  /* [242] dict = {'iface_name': 'str', 'return': 'bool'} */
    PyObject *const_str_plain_save_custom_interface;  /* [243] str = 'save_custom_interface' */
    PyObject *const_str_digest_0c5c6cc6;  /* [244] str = 'IPv6Manager.save_custom_interface' */
    PyObject *const_dict_1_3;  /* [245] dict = {'return': 'int'} */
    PyObject *const_str_digest_90460a87;  /* [246] str = 'IPv6Manager._get_interface_luid' */
    PyObject *const_dict_4;  /* [247] dict = {'addr_str': 'str', 'luid': 'int', 'prefix_len': 'int', 'ret... */
    PyObject *const_str_digest_2711d2a2;  /* [248] str = 'IPv6Manager._win32_add_ipv6' */
    PyObject *const_dict_3;  /* [249] dict = {'addr_str': 'str', 'luid': 'int', 'return': 'bool'} */
    PyObject *const_str_digest_7188cc61;  /* [250] str = 'IPv6Manager._win32_del_ipv6' */
    PyObject *const_str_plain_flush_all_manual_addresses;  /* [251] str = 'flush_all_manual_addresses' */
    PyObject *const_str_digest_9f2d871e;  /* [252] str = 'IPv6Manager.flush_all_manual_addresses' */
    PyObject *const_str_plain_generate_addresses;  /* [253] str = 'generate_addresses' */
    PyObject *const_str_digest_868662ba;  /* [254] str = 'IPv6Manager.generate_addresses' */
    PyObject *const_dict_1_4;  /* [255] dict = {'address': 'str'} */
    PyObject *const_str_plain_add_address;  /* [256] str = 'add_address' */
    PyObject *const_str_digest_e47988ca;  /* [257] str = 'IPv6Manager.add_address' */
    PyObject *const_tuple_1_18;  /* [258] tuple = (40,) */
    PyObject *const_dict_3_1;  /* [259] dict = {'addresses': 'list', 'max_workers': 'int', 'return': 'list'... */
    PyObject *const_str_plain_add_addresses_batch;  /* [260] str = 'add_addresses_batch' */
    PyObject *const_str_digest_2046c6d3;  /* [261] str = 'IPv6Manager.add_addresses_batch' */
    PyObject *const_str_plain_remove_address;  /* [262] str = 'remove_address' */
    PyObject *const_str_digest_743feafc;  /* [263] str = 'IPv6Manager.remove_address' */
    PyObject *const_dict_2_1;  /* [264] dict = {'addresses': 'list', 'max_workers': 'int'} */
    PyObject *const_str_digest_e5ad1c21;  /* [265] str = 'IPv6Manager.remove_addresses_batch' */
    PyObject *const_str_plain_cleanup_all;  /* [266] str = 'cleanup_all' */
    PyObject *const_str_digest_b92c142a;  /* [267] str = 'IPv6Manager.cleanup_all' */
    PyObject *const_dict_1_5;  /* [268] dict = {'return': 'str'} */
    PyObject *const_str_digest_64cf0564;  /* [269] str = 'IPv6Manager._find_active_interface_name' */
    PyObject *const_dict_2_2;  /* [270] dict = {'prefix_str': 'str', 'return': 'bool'} */
    PyObject *const_str_plain_save_custom_prefix;  /* [271] str = 'save_custom_prefix' */
    PyObject *const_str_digest_2988ef00;  /* [272] str = 'IPv6Manager.save_custom_prefix' */
    PyObject *const_str_digest_1d77e011;  /* [273] str = 'core\\ipv6\\ipv6_manager.py' */
    PyObject *const_tuple_1_19;  /* [274] tuple = ('c',) */
    PyObject *const_tuple_1_20;  /* [275] tuple = ('x',) */
    PyObject *const_str_digest_e966c040;  /* [276] str = '<module core.ipv6.ipv6_manager>' */
    PyObject *const_tuple_1_21;  /* [277] tuple = ('__class__',) */
    PyObject *const_tuple_9;  /* [278] tuple = ('self', 'data_dir', 'Path', 'base_dir', 'legacy_configs_dir... */
    PyObject *const_tuple_3_2;  /* [279] tuple = ('addr', 'res', 'self') */
    PyObject *const_tuple_1_22;  /* [280] tuple = ('self',) */
    PyObject *const_tuple_2_5;  /* [281] tuple = ('addr', 'self') */
    PyObject *const_tuple_5;  /* [282] tuple = ('self', 'result', 'output', 'line', 'm') */
    PyObject *const_tuple_6;  /* [283] tuple = ('self', 'luid', 'res', 'line', 'parts', 'idx') */
    PyObject *const_tuple_9_1;  /* [284] tuple = ('self', 'addr_str', 'luid', 'prefix_len', 'row', 'ip_obj', ... */
    PyObject *const_tuple_8;  /* [285] tuple = ('self', 'addr_str', 'luid', 'row', 'ip_obj', 'i', 'b', 'res... */
    PyObject *const_tuple_5_1;  /* [286] tuple = ('self', 'address', 'luid', 'e', 'result') */
    PyObject *const_tuple_11;  /* [287] tuple = ('self', 'addresses', 'max_workers', 'luid', 'success_addrs'... */
    PyObject *const_tuple_17;  /* [288] tuple = ('self', 'f', 'val', 'e', 'result', 'output', 'current_iface... */
    PyObject *const_tuple_20;  /* [289] tuple = ('self', 'force_iface', 'saved_iface', 'f', 'val', 'e', 'res... */
    PyObject *const_tuple_10;  /* [290] tuple = ('self', 'result', 'current_iface', 'ipv6_re', 'del_list', '... */
    PyObject *const_tuple_9_2;  /* [291] tuple = ('self', 'count', 'addresses', 'prefix_int', '_', 'suffix', ... */
    PyObject *const_tuple_17_1;  /* [292] tuple = ('self', 'result', 'output', 'current_iface', 'iface_map', '... */
    PyObject *const_tuple_3_3;  /* [293] tuple = ('self', 'address', 'luid') */
    PyObject *const_tuple_8_1;  /* [294] tuple = ('self', 'addresses', 'max_workers', 'luid', 'addr', 'e', '_... */
    PyObject *const_tuple_4_1;  /* [295] tuple = ('self', 'iface_name', 'f', 'e') */
    PyObject *const_tuple_5_2;  /* [296] tuple = ('self', 'prefix_str', 'prefix', 'f', 'e') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.ipv6.ipv6_manager"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__pathlib;   /* 'pathlib' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__mkdir;   /* 'mkdir' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__stdout;   /* 'stdout' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__append;   /* 'append' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__append;   /* 'append' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__interfaces_list;   /* 'interfaces_list' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__detect_interface_and_prefix;   /* 'detect_interface_and_prefix' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__ThreadPoolExecutor;   /* 'ThreadPoolExecutor' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__save_custom_prefix;   /* 'save_custom_prefix' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__save_custom_prefix;   /* 'save_custom_prefix' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__ipv6_manager$gt$;   /* 'ipv6_manager>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__ipv6_manager$gt$;   /* 'ipv6_manager>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__ipv6_manager$gt$;   /* 'ipv6_manager>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__ipv6_manager$gt$;   /* 'ipv6_manager>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def pathlib(Path)
 *  qualname: pathlib   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$pathlib(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def mkdir(parents, exist_ok)
 *  qualname: custom_subnet.txt   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$mkdir(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def stdout(capture_output, text, creationflags)
 *  qualname: stdout   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$stdout(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def append(strict)
 *  qualname: append   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$append(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def append(public, temporary, dhcp, other)
 *  qualname: append   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$append(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def interfaces_list(key)
 *  qualname: <lambda>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$interfaces_list(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def detect_interface_and_prefix(force_iface)
 *  qualname: detect_interface_and_prefix   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$detect_interface_and_prefix(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ThreadPoolExecutor(max_workers)
 *  qualname: IPv6Manager.add_addresses_batch.<locals>._add_single_netsh   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$ThreadPoolExecutor(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(IPv6Proxy)
 *  qualname: concurrent.futures   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def save_custom_prefix(x)
 *  qualname: <module core.ipv6.ipv6_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$save_custom_prefix(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ipv6_manager>(__class__)
 *  qualname: <module core.ipv6.ipv6_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ipv6_manager>(self, data_dir, Path, base_dir, legacy_configs_dir, fname, legacy_file, target_file, shutil)
 *  qualname: <module core.ipv6.ipv6_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ipv6_manager>(addr, res, self)
 *  qualname: <module core.ipv6.ipv6_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ipv6_manager>(self)
 *  qualname: <module core.ipv6.ipv6_manager>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: IPv6Manager
 *   methods recovered: 1
 *   class body was also compiled to native code */
static PyObject *impl_core$ipv6$ipv6_manager$IPv6Manager$save_custom_prefix(PyThreadState *tstate, PyObject **python_pars);  /* def IPv6Manager.save_custom_prefix(c) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$ipv6$ipv6_manager$pathlib(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pathlib(Path): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$mkdir(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def mkdir(parents, exist_ok): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$stdout(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def stdout(capture_output, text, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$append(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def append(strict): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$append(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def append(public, temporary, dhcp, other): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$interfaces_list(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def interfaces_list(key): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$detect_interface_and_prefix(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def detect_interface_and_prefix(force_iface): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$ThreadPoolExecutor(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ThreadPoolExecutor(max_workers): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(IPv6Proxy): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$save_custom_prefix(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def save_custom_prefix(x): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ipv6_manager>(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ipv6_manager>(self, data_dir, Path, base_dir, legacy_configs_dir, fname, legacy_file, target_file, shutil): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ipv6_manager>(addr, res, self): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$ipv6_manager$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ipv6_manager>(self): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$ipv6_manager$IPv6Manager$save_custom_prefix(PyThreadState *tstate, PyObject **python_pars) {
    /* def IPv6Manager.save_custom_prefix(c): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$ipv6$ipv6_manager(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$ipv6$ipv6_manager = module;
    moduledict_core$ipv6$ipv6_manager = MODULE_DICT(module_core$ipv6$ipv6_manager);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141952E80
     *
     * Recovered imports (detected from module constants): */
    /*   import custom_subnet.txt */
    /*   import custom_interface.txt */
    /*   import concurrent.futures */
    /*   import core.ipv6.ipv6_manager */
    /*   import IPv6Manager.__init__ */
    /*   import IPv6Manager.get_available_interfaces */
    /*   import IPv6Manager.detect_interface_and_prefix */
    /*   import IPv6Manager.save_custom_interface */
    /*   import IPv6Manager._get_interface_luid */
    /*   import IPv6Manager._win32_add_ipv6 */
    /*   import IPv6Manager._win32_del_ipv6 */
    /*   import IPv6Manager.flush_all_manual_addresses */
    /*   import IPv6Manager.generate_addresses */
    /*   import IPv6Manager.add_address */
    /*   import IPv6Manager.add_addresses_batch */
    /*   import IPv6Manager.remove_address */
    /*   import IPv6Manager.remove_addresses_batch */
    /*   import IPv6Manager.cleanup_all */
    /*   import IPv6Manager._find_active_interface_name */
    /*   import IPv6Manager.save_custom_prefix */

    return module;
}

