/* Reconstructed C source for Python module 'core.ipv6.proxy_instance'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$ipv6$proxy_instance @ 0x141974360
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$ipv6$proxy_instance;
PyDictObject *moduledict_core$ipv6$proxy_instance;

/* Module constants: 158 entries recovered from blob chunk 'core.ipv6.proxy_instance'. */
static struct ModuleConstants {
    PyObject *const_str_plain_source_ipv6;  /* [0] str = 'source_ipv6' */
    PyObject *const_str_plain_port;  /* [1] str = 'port' */
    PyObject *const_str_plain_group_name;  /* [2] str = 'group_name' */
    PyObject *const_str_plain_proxy_type;  /* [3] str = 'proxy_type' */
    PyObject *const_str_plain_strip;  /* [4] str = 'strip' */
    PyObject *const_str_plain_username;  /* [5] str = 'username' */
    PyObject *const_str_plain_password;  /* [6] str = 'password' */
    PyObject *const_str_plain__server_sock;  /* [7] str = '_server_sock' */
    PyObject *const_str_plain__thread;  /* [8] str = '_thread' */
    PyObject *const_str_plain__running;  /* [9] str = '_running' */
    PyObject *const_str_plain_socket;  /* [10] str = 'socket' */
    PyObject *const_str_plain_AF_INET;  /* [11] str = 'AF_INET' */
    PyObject *const_str_plain_SOCK_STREAM;  /* [12] str = 'SOCK_STREAM' */
    PyObject *const_str_plain_setsockopt;  /* [13] str = 'setsockopt' */
    PyObject *const_str_plain_SOL_SOCKET;  /* [14] str = 'SOL_SOCKET' */
    PyObject *const_str_plain_SO_REUSEADDR;  /* [15] str = 'SO_REUSEADDR' */
    PyObject *const_str_plain_bind;  /* [16] str = 'bind' */
    PyObject *const_str_digest_f1f17934;  /* [17] str = '0.0.0.0' */
    PyObject *const_str_plain_listen;  /* [18] str = 'listen' */
    PyObject *const_tuple_1;  /* [19] tuple = (200,) */
    PyObject *const_str_plain_settimeout;  /* [20] str = 'settimeout' */
    PyObject *const_tuple_1_1;  /* [21] tuple = (2.0,) */
    PyObject *const_str_plain_threading;  /* [22] str = 'threading' */
    PyObject *const_str_plain_Thread;  /* [23] str = 'Thread' */
    PyObject *const_str_plain__accept_loop;  /* [24] str = '_accept_loop' */
    PyObject *const_tuple_2;  /* [25] tuple = ('target', 'daemon') */
    PyObject *const_str_plain_start;  /* [26] str = 'start' */
    PyObject *const_str_plain_self;  /* [27] str = 'self' */
    PyObject *const_str_plain_accept;  /* [28] str = 'accept' */
    PyObject *const_tuple_1_2;  /* [29] tuple = (60,) */
    PyObject *const_str_plain__handle_client;  /* [30] str = '_handle_client' */
    PyObject *const_tuple_3;  /* [31] tuple = ('target', 'args', 'daemon') */
    PyObject *const_str_plain_timeout;  /* [32] str = 'timeout' */
    PyObject *const_str_plain_base64;  /* [33] str = 'base64' */
    PyObject *const_str_plain_b64encode;  /* [34] str = 'b64encode' */
    PyObject *const_str_digest_853ae90f;  /* [35] str = ':' */
    PyObject *const_str_plain_decode;  /* [36] str = 'decode' */
    PyObject *const_str_plain_splitlines;  /* [37] str = 'splitlines' */
    PyObject *const_str_plain_startswith;  /* [38] str = 'startswith' */
    PyObject *const_tuple_1_3;  /* [39] tuple = ('proxy-authorization:',) */
    PyObject *const_tuple_2_1;  /* [40] tuple = (':', 1) */
    PyObject *const_str_plain_basic;  /* [41] str = 'basic' */
    PyObject *const_str_plain_socks5;  /* [42] str = 'socks5' */
    PyObject *const_str_plain__handle_socks5;  /* [43] str = '_handle_socks5' */
    PyObject *const_str_plain_recv;  /* [44] str = 'recv' */
    PyObject *const_tuple_1_4;  /* [45] tuple = (16384,) */
    PyObject *const_tuple_2_2;  /* [46] tuple = ('utf-8', 'replace') */
    PyObject *const_tuple_1_5;  /* [47] tuple = ('errors',) */
    PyObject *const_str_plain__check_http_auth;  /* [48] str = '_check_http_auth' */
    PyObject *const_str_plain_sendall;  /* [49] str = 'sendall' */
    PyObject *const_tuple_1_6;  /* [50] tuple = (b'HTTP/1.1 407 Proxy Authentication Required\r\nProxy-Authe... */
    PyObject *const_tuple_1_7;  /* [51] tuple = ('\r\n',) */
    PyObject *const_tuple_1_8;  /* [52] tuple = ('\n',) */
    PyObject *const_tuple_1_9;  /* [53] tuple = (' ',) */
    PyObject *const_str_plain_upper;  /* [54] str = 'upper' */
    PyObject *const_str_plain_CONNECT;  /* [55] str = 'CONNECT' */
    PyObject *const_str_plain__handle_connect;  /* [56] str = '_handle_connect' */
    PyObject *const_str_plain__handle_http;  /* [57] str = '_handle_http' */
    PyObject *const_str_plain_logger;  /* [58] str = 'logger' */
    PyObject *const_str_plain_debug;  /* [59] str = 'debug' */
    PyObject *const_str_digest_3dab1a39;  /* [60] str = 'Lỗi client tại ' */
    PyObject *const_str_digest_e2654927;  /* [61] str = ': ' */
    PyObject *const_tuple_1_10;  /* [62] tuple = (2,) */
    PyObject *const_int_pos_5;  /* [63] int = 5 */
    PyObject *const_int_pos_2;  /* [64] int = 2 */
    PyObject *const_tuple_1_11;  /* [65] tuple = (b'\x05\xff',) */
    PyObject *const_tuple_1_12;  /* [66] tuple = (b'\x05\x02',) */
    PyObject *const_tuple_2_3;  /* [67] tuple = ('utf-8', 'ignore') */
    PyObject *const_tuple_1_13;  /* [68] tuple = (1,) */
    PyObject *const_tuple_1_14;  /* [69] tuple = (b'\x01\x00',) */
    PyObject *const_tuple_1_15;  /* [70] tuple = (b'\x01\x01',) */
    PyObject *const_tuple_1_16;  /* [71] tuple = (b'\x05\x00',) */
    PyObject *const_tuple_1_17;  /* [72] tuple = (4,) */
    PyObject *const_int_pos_3;  /* [73] int = 3 */
    PyObject *const_str_plain_inet_ntoa;  /* [74] str = 'inet_ntoa' */
    PyObject *const_tuple_1_18;  /* [75] tuple = ('utf-8',) */
    PyObject *const_int_pos_4;  /* [76] int = 4 */
    PyObject *const_tuple_1_19;  /* [77] tuple = (16,) */
    PyObject *const_str_plain_inet_ntop;  /* [78] str = 'inet_ntop' */
    PyObject *const_str_plain_AF_INET6;  /* [79] str = 'AF_INET6' */
    PyObject *const_str_plain_struct;  /* [80] str = 'struct' */
    PyObject *const_str_plain_unpack;  /* [81] str = 'unpack' */
    PyObject *const_str_digest_59c1cb7d;  /* [82] str = '!H' */
    PyObject *const_str_plain__connect_to_dest;  /* [83] str = '_connect_to_dest' */
    PyObject *const_tuple_1_20;  /* [84] tuple = (b'\x05\x01\x00\x01\x00\x00\x00\x00\x00\x00',) */
    PyObject *const_tuple_1_21;  /* [85] tuple = (b'\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00',) */
    PyObject *const_str_plain__tunnel;  /* [86] str = '_tunnel' */
    PyObject *const_str_plain_getaddrinfo;  /* [87] str = 'getaddrinfo' */
    PyObject *const_str_plain_AF_UNSPEC;  /* [88] str = 'AF_UNSPEC' */
    PyObject *const_str_plain_IPPROTO_IPV6;  /* [89] str = 'IPPROTO_IPV6' */
    PyObject *const_str_plain_IPV6_V6ONLY;  /* [90] str = 'IPV6_V6ONLY' */
    PyObject *const_tuple_1_22;  /* [91] tuple = (30,) */
    PyObject *const_str_plain_connect;  /* [92] str = 'connect' */
    PyObject *const_str_digest_9e31e9a2;  /* [93] str = '::ffff:' */
    PyObject *const_str_plain_rsplit;  /* [94] str = 'rsplit' */
    PyObject *const_tuple_1_23;  /* [95] tuple = (b'HTTP/1.1 502 Bad Gateway\r\n\r\n',) */
    PyObject *const_tuple_1_24;  /* [96] tuple = (b'HTTP/1.1 200 Connection established\r\n\r\n',) */
    PyObject *const_tuple_1_25;  /* [97] tuple = (('http://', 'https://'),) */
    PyObject *const_str_plain_urlparse;  /* [98] str = 'urlparse' */
    PyObject *const_str_plain_hostname;  /* [99] str = 'hostname' */
    PyObject *const_str_plain_scheme;  /* [100] str = 'scheme' */
    PyObject *const_str_plain_https;  /* [101] str = 'https' */
    PyObject *const_int_pos_443;  /* [102] int = 443 */
    PyObject *const_int_pos_80;  /* [103] int = 80 */
    PyObject *const_str_plain_query;  /* [104] str = 'query' */
    PyObject *const_str_digest_d1457b72;  /* [105] str = '?' */
    PyObject *const_str_digest_7215ee9c;  /* [106] str = ' ' */
    PyObject *const_str_digest_69c32f04;  /* [107] str = ' HTTP/1.1' */
    PyObject *const_str_digest_81051bcc;  /* [108] str = '\r\n' */
    PyObject *const_str_digest_cb492b7d;  /* [109] str = '\r\n\r\n' */
    PyObject *const_str_digest_e9e2aa81;  /* [110] str = 'utf-8' */
    PyObject *const_str_digest_68b329da;  /* [111] str = '\n' */
    PyObject *const_tuple_1_26;  /* [112] tuple = ('host:',) */
    PyObject *const_str_plain__forward_response;  /* [113] str = '_forward_response' */
    PyObject *const_str_plain_select;  /* [114] str = 'select' */
    PyObject *const_str_plain_socks;  /* [115] str = 'socks' */
    PyObject *const_tuple_1_27;  /* [116] tuple = (4096,) */
    PyObject *const_str_plain_from_sock;  /* [117] str = 'from_sock' */
    PyObject *const_tuple_1_28;  /* [118] tuple = (65536,) */
    PyObject *const_str_plain_to_sock;  /* [119] str = 'to_sock' */
    PyObject *const_str_plain_origin;  /* [120] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [121] str = 'has_location' */
    PyObject *const_str_digest_16d628fa;  /* [122] str = 'urllib.parse' */
    PyObject *const_tuple_1_29;  /* [123] tuple = ('urlparse',) */
    PyObject *const_str_plain_logging;  /* [124] str = 'logging' */
    PyObject *const_str_plain_getLogger;  /* [125] str = 'getLogger' */
    PyObject *const_tuple_1_30;  /* [126] tuple = ('IPv6Proxy',) */
    PyObject *const_str_digest_321d9a42;  /* [127] str = 'core.ipv6.proxy_instance' */
    PyObject *const_str_plain_ProxyInstance;  /* [128] str = 'ProxyInstance' */
    PyObject *const_str_plain___qualname__;  /* [129] str = '__qualname__' */
    PyObject *const_tuple_3_1;  /* [130] tuple = ('http', None, None) */
    PyObject *const_str_digest_75c98bb8;  /* [131] str = 'ProxyInstance.__init__' */
    PyObject *const_str_digest_21674858;  /* [132] str = 'ProxyInstance.start' */
    PyObject *const_str_plain_stop;  /* [133] str = 'stop' */
    PyObject *const_str_digest_bd18fdf8;  /* [134] str = 'ProxyInstance.stop' */
    PyObject *const_str_digest_e89bcd2c;  /* [135] str = 'ProxyInstance._accept_loop' */
    PyObject *const_dict_2;  /* [136] dict = {'decoded_header': 'str', 'return': 'bool'} */
    PyObject *const_str_digest_66e49e78;  /* [137] str = 'ProxyInstance._check_http_auth' */
    PyObject *const_str_digest_ab177464;  /* [138] str = 'ProxyInstance._handle_client' */
    PyObject *const_str_digest_ea5ca49f;  /* [139] str = 'ProxyInstance._handle_socks5' */
    PyObject *const_str_digest_a60882ee;  /* [140] str = 'ProxyInstance._connect_to_dest' */
    PyObject *const_str_digest_aecfecf9;  /* [141] str = 'ProxyInstance._handle_connect' */
    PyObject *const_str_digest_2e8b81c7;  /* [142] str = 'ProxyInstance._handle_http' */
    PyObject *const_str_digest_7f237a4b;  /* [143] str = 'ProxyInstance._tunnel' */
    PyObject *const_str_digest_a82f3029;  /* [144] str = 'ProxyInstance._forward_response' */
    PyObject *const_str_digest_8b56e1a6;  /* [145] str = 'core\\ipv6\\proxy_instance.py' */
    PyObject *const_str_digest_79ad691e;  /* [146] str = '<module core.ipv6.proxy_instance>' */
    PyObject *const_tuple_7;  /* [147] tuple = ('self', 'source_ipv6', 'port', 'group_name', 'proxy_type', ... */
    PyObject *const_tuple_3_2;  /* [148] tuple = ('self', 'client_sock', 'addr') */
    PyObject *const_tuple_5;  /* [149] tuple = ('self', 'decoded_header', 'expected_token', 'line', 'parts'... */
    PyObject *const_tuple_11;  /* [150] tuple = ('self', 'host', 'port', 'addrinfo', 'family', 'type_', 'pro... */
    PyObject *const_tuple_4;  /* [151] tuple = ('self', 'from_sock', 'to_sock', 'data') */
    PyObject *const_tuple_11_1;  /* [152] tuple = ('self', 'client_sock', 'addr', 'data', 'raw', 'decoded', 'f... */
    PyObject *const_tuple_7_1;  /* [153] tuple = ('self', 'client_sock', 'uri', 'host', 'port_str', 'port', '... */
    PyObject *const_tuple_16;  /* [154] tuple = ('self', 'client_sock', 'method', 'uri', 'raw_data', 'decode... */
    PyObject *const_tuple_23;  /* [155] tuple = ('self', 'client_sock', 'header', 'ver', 'nmethods', 'method... */
    PyObject *const_tuple_9;  /* [156] tuple = ('self', 'sock1', 'sock2', 'socks', 'readable', '_', 's', 'o... */
    PyObject *const_tuple_1_31;  /* [157] tuple = ('self',) */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.ipv6.proxy_instance"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0___accept_loop;   /* '_accept_loop' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1___handle_client;   /* '_handle_client' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2___check_http_auth;   /* '_check_http_auth' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__logging;   /* 'logging' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__proxy_instance$gt$;   /* 'proxy_instance>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__proxy_instance$gt$;   /* 'proxy_instance>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__proxy_instance$gt$;   /* 'proxy_instance>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__proxy_instance$gt$;   /* 'proxy_instance>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def _accept_loop(target, daemon)
 *  qualname: _accept_loop   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$_accept_loop(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _handle_client(target, args, daemon)
 *  qualname: _handle_client   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$_handle_client(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _check_http_auth(errors)
 *  qualname: _check_http_auth   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$_check_http_auth(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def logging(urlparse)
 *  qualname: urllib.parse   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$logging(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(IPv6Proxy)
 *  qualname: core.ipv6.proxy_instance   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def proxy_instance>(self, source_ipv6, port, group_name, proxy_type, username, password)
 *  qualname: <module core.ipv6.proxy_instance>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def proxy_instance>(self, client_sock, addr)
 *  qualname: <module core.ipv6.proxy_instance>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def proxy_instance>(self, decoded_header, expected_token, line, parts)
 *  qualname: <module core.ipv6.proxy_instance>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def proxy_instance>(self, host, port, addrinfo, family, type_, proto, canonname, sockaddr, s, mapped)
 *  qualname: <module core.ipv6.proxy_instance>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$ipv6$proxy_instance$_accept_loop(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _accept_loop(target, daemon): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$_handle_client(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _handle_client(target, args, daemon): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$_check_http_auth(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _check_http_auth(errors): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$logging(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def logging(urlparse): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(IPv6Proxy): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def proxy_instance>(self, source_ipv6, port, group_name, proxy_type, username, password): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def proxy_instance>(self, client_sock, addr): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def proxy_instance>(self, decoded_header, expected_token, line, parts): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$proxy_instance$proxy_instance$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def proxy_instance>(self, host, port, addrinfo, family, type_, proto, canonname, sockaddr, s, mapped): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$ipv6$proxy_instance(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$ipv6$proxy_instance = module;
    moduledict_core$ipv6$proxy_instance = MODULE_DICT(module_core$ipv6$proxy_instance);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141974360
     *
     * Recovered imports (detected from module constants): */
    /*   import 0.0.0.0 */
    /*   import urllib.parse */
    /*   import core.ipv6.proxy_instance */
    /*   import ProxyInstance.__init__ */
    /*   import ProxyInstance.start */
    /*   import ProxyInstance.stop */
    /*   import ProxyInstance._accept_loop */
    /*   import ProxyInstance._check_http_auth */
    /*   import ProxyInstance._handle_client */
    /*   import ProxyInstance._handle_socks5 */
    /*   import ProxyInstance._connect_to_dest */
    /*   import ProxyInstance._handle_connect */
    /*   import ProxyInstance._handle_http */
    /*   import ProxyInstance._tunnel */
    /*   import ProxyInstance._forward_response */

    return module;
}

