/* Reconstructed C source for Python module 'core.ipv6.utils'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$ipv6$utils @ 0x14197D980
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$ipv6$utils;
PyDictObject *moduledict_core$ipv6$utils;

/* Module constants: 62 entries recovered from blob chunk 'core.ipv6.utils'. */
static struct ModuleConstants {
    PyObject *const_str_plain_windll;  /* [0] str = 'windll' */
    PyObject *const_str_plain_shell32;  /* [1] str = 'shell32' */
    PyObject *const_str_plain_IsUserAnAdmin;  /* [2] str = 'IsUserAnAdmin' */
    PyObject *const_str_plain_start_port;  /* [3] str = 'start_port' */
    PyObject *const_str_plain__used;  /* [4] str = '_used' */
    PyObject *const_str_plain_threading;  /* [5] str = 'threading' */
    PyObject *const_str_plain_Lock;  /* [6] str = 'Lock' */
    PyObject *const_str_plain__lock;  /* [7] str = '_lock' */
    PyObject *const_str_plain__is_port_free;  /* [8] str = '_is_port_free' */
    PyObject *const_str_plain_add;  /* [9] str = 'add' */
    PyObject *const_int_pos_65536;  /* [10] int = 65536 */
    PyObject *const_str_plain_self;  /* [11] str = 'self' */
    PyObject *const_tuple_3;  /* [12] tuple = (None, None, None) */
    PyObject *const_str_digest_40f9d7cd;  /* [13] str = 'Không còn port khả dụng' */
    PyObject *const_str_plain_allocated;  /* [14] str = 'allocated' */
    PyObject *const_str_plain_curr;  /* [15] str = 'curr' */
    PyObject *const_str_digest_eb5ff196;  /* [16] str = 'Không đủ cổng khả dụng trong dải port' */
    PyObject *const_str_digest_111d6ec1;  /* [17] str = 'Cấp phát hàng loạt N cổng liên tục siêu tốc (chỉ mất ~0.001... */
    PyObject *const_str_plain_discard;  /* [18] str = 'discard' */
    PyObject *const_str_plain_socket;  /* [19] str = 'socket' */
    PyObject *const_str_plain_AF_INET;  /* [20] str = 'AF_INET' */
    PyObject *const_str_plain_SOCK_STREAM;  /* [21] str = 'SOCK_STREAM' */
    PyObject *const_str_plain_bind;  /* [22] str = 'bind' */
    PyObject *const_str_digest_f1f17934;  /* [23] str = '0.0.0.0' */
    PyObject *const_str_plain_SOCK_DGRAM;  /* [24] str = 'SOCK_DGRAM' */
    PyObject *const_str_plain_settimeout;  /* [25] str = 'settimeout' */
    PyObject *const_tuple_1;  /* [26] tuple = (1,) */
    PyObject *const_str_plain_connect;  /* [27] str = 'connect' */
    PyObject *const_tuple_1_1;  /* [28] tuple = (('1.1.1.1', 80),) */
    PyObject *const_str_plain_getsockname;  /* [29] str = 'getsockname' */
    PyObject *const_str_digest_f528764d;  /* [30] str = '127.0.0.1' */
    PyObject *const_str_plain_origin;  /* [31] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [32] str = 'has_location' */
    PyObject *const_str_plain_ctypes;  /* [33] str = 'ctypes' */
    PyObject *const_str_plain_logging;  /* [34] str = 'logging' */
    PyObject *const_str_plain_sys;  /* [35] str = 'sys' */
    PyObject *const_str_plain_is_admin;  /* [36] str = 'is_admin' */
    PyObject *const_str_digest_9055e1bd;  /* [37] str = 'core.ipv6.utils' */
    PyObject *const_str_plain_PortManager;  /* [38] str = 'PortManager' */
    PyObject *const_str_plain___qualname__;  /* [39] str = '__qualname__' */
    PyObject *const_tuple_1_2;  /* [40] tuple = (20000,) */
    PyObject *const_str_digest_d64fca1b;  /* [41] str = 'PortManager.__init__' */
    PyObject *const_tuple_1_3;  /* [42] tuple = (None,) */
    PyObject *const_str_plain_allocate;  /* [43] str = 'allocate' */
    PyObject *const_str_digest_2a4e492f;  /* [44] str = 'PortManager.allocate' */
    PyObject *const_dict_3;  /* [45] dict = {'count': 'int', 'preferred_start': 'int', 'return': 'list'} */
    PyObject *const_str_plain_allocate_batch;  /* [46] str = 'allocate_batch' */
    PyObject *const_str_digest_f1772f76;  /* [47] str = 'PortManager.allocate_batch' */
    PyObject *const_str_plain_release;  /* [48] str = 'release' */
    PyObject *const_str_digest_e364b3a7;  /* [49] str = 'PortManager.release' */
    PyObject *const_str_digest_27c95285;  /* [50] str = 'PortManager._is_port_free' */
    PyObject *const_str_plain_is_used;  /* [51] str = 'is_used' */
    PyObject *const_str_digest_ce9875ca;  /* [52] str = 'PortManager.is_used' */
    PyObject *const_str_plain_get_local_ipv4;  /* [53] str = 'get_local_ipv4' */
    PyObject *const_str_digest_c845869b;  /* [54] str = 'core\\ipv6\\utils.py' */
    PyObject *const_str_digest_d27752b4;  /* [55] str = '<module core.ipv6.utils>' */
    PyObject *const_tuple_2;  /* [56] tuple = ('self', 'start_port') */
    PyObject *const_tuple_3_1;  /* [57] tuple = ('self', 'port', 's') */
    PyObject *const_tuple_3_2;  /* [58] tuple = ('self', 'preferred_port', 'port') */
    PyObject *const_tuple_5;  /* [59] tuple = ('self', 'count', 'preferred_start', 'allocated', 'curr') */
    PyObject *const_tuple_2_1;  /* [60] tuple = ('s', 'ip') */
    PyObject *const_tuple_2_2;  /* [61] tuple = ('self', 'port') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.ipv6.utils"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__get_local_ipv4;   /* 'get_local_ipv4' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__get_local_ipv4;   /* 'get_local_ipv4' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__utils$gt$;   /* 'utils>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__utils$gt$;   /* 'utils>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def get_local_ipv4(self, start_port)
 *  qualname: <module core.ipv6.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$utils$get_local_ipv4(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def get_local_ipv4(self, port, s)
 *  qualname: <module core.ipv6.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$utils$get_local_ipv4(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def utils>(self, preferred_port, port)
 *  qualname: <module core.ipv6.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def utils>(self, count, preferred_start, allocated, curr)
 *  qualname: <module core.ipv6.utils>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$ipv6$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$ipv6$utils$get_local_ipv4(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def get_local_ipv4(self, start_port): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$utils$get_local_ipv4(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def get_local_ipv4(self, port, s): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def utils>(self, preferred_port, port): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$ipv6$utils$utils$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def utils>(self, count, preferred_start, allocated, curr): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$ipv6$utils(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$ipv6$utils = module;
    moduledict_core$ipv6$utils = MODULE_DICT(module_core$ipv6$utils);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x14197D980
     *
     * Recovered imports (detected from module constants): */
    /*   import 0.0.0.0 */
    /*   import 127.0.0.1 */
    /*   import core.ipv6.utils */
    /*   import PortManager.__init__ */
    /*   import PortManager.allocate */
    /*   import PortManager.allocate_batch */
    /*   import PortManager.release */
    /*   import PortManager._is_port_free */
    /*   import PortManager.is_used */

    return module;
}

