/* Reconstructed C source for Python module 'aiohttp_socks'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_aiohttp_socks @ 0x1412081C0
 * Flags: PACKAGE, TRANSLATED
 * Is package: True
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_aiohttp_socks;
PyDictObject *moduledict_aiohttp_socks;

/* Module constants: 33 entries recovered from blob chunk 'aiohttp_socks'. */
static struct ModuleConstants {
    PyObject *const_str_plain_environ;  /* [0] str = 'environ' */
    PyObject *const_tuple_2;  /* [1] tuple = ('NUITKA_PACKAGE_aiohttp_socks', '\\not_existing') */
    PyObject *const_str_plain_origin;  /* [2] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [3] str = 'has_location' */
    PyObject *const_str_plain_submodule_search_locations;  /* [4] str = 'submodule_search_locations' */
    PyObject *const_str_digest_df35223f;  /* [5] str = 'aiohttp-socks' */
    PyObject *const_str_plain___title__;  /* [6] str = '__title__' */
    PyObject *const_str_digest_cc9277bd;  /* [7] str = '0.8.4' */
    PyObject *const_str_plain___version__;  /* [8] str = '__version__' */
    PyObject *const_str_plain_python_socks;  /* [9] str = 'python_socks' */
    PyObject *const_tuple_4;  /* [10] tuple = ('ProxyError', 'ProxyTimeoutError', 'ProxyConnectionError', ... */
    PyObject *const_str_plain_ProxyError;  /* [11] str = 'ProxyError' */
    PyObject *const_str_plain_ProxyTimeoutError;  /* [12] str = 'ProxyTimeoutError' */
    PyObject *const_str_plain_ProxyConnectionError;  /* [13] str = 'ProxyConnectionError' */
    PyObject *const_str_plain_ProxyType;  /* [14] str = 'ProxyType' */
    PyObject *const_str_plain_connector;  /* [15] str = 'connector' */
    PyObject *const_tuple_3;  /* [16] tuple = ('ProxyConnector', 'ChainProxyConnector', 'ProxyInfo') */
    PyObject *const_str_plain_ProxyConnector;  /* [17] str = 'ProxyConnector' */
    PyObject *const_str_plain_ChainProxyConnector;  /* [18] str = 'ChainProxyConnector' */
    PyObject *const_str_plain_ProxyInfo;  /* [19] str = 'ProxyInfo' */
    PyObject *const_str_plain_utils;  /* [20] str = 'utils' */
    PyObject *const_tuple_2_1;  /* [21] tuple = ('open_connection', 'create_connection') */
    PyObject *const_str_plain_open_connection;  /* [22] str = 'open_connection' */
    PyObject *const_str_plain_create_connection;  /* [23] str = 'create_connection' */
    PyObject *const_str_plain__deprecated;  /* [24] str = '_deprecated' */
    PyObject *const_tuple_4_1;  /* [25] tuple = ('SocksVer', 'SocksConnector', 'SocksConnectionError', 'Sock... */
    PyObject *const_str_plain_SocksVer;  /* [26] str = 'SocksVer' */
    PyObject *const_str_plain_SocksConnector;  /* [27] str = 'SocksConnector' */
    PyObject *const_str_plain_SocksConnectionError;  /* [28] str = 'SocksConnectionError' */
    PyObject *const_str_plain_SocksError;  /* [29] str = 'SocksError' */
    PyObject *const_tuple_15;  /* [30] tuple = ('__title__', '__version__', 'ProxyConnector', 'ChainProxyCo... */
    PyObject *const_str_digest_3f127e9f;  /* [31] str = 'aiohttp_socks\\__init__.py' */
    PyObject *const_str_digest_23b87b2f;  /* [32] str = '<module aiohttp_socks>' */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("aiohttp_socks"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__python_socks;   /* 'python_socks' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__connector;   /* 'connector' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__utils;   /* 'utils' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3___deprecated;   /* '_deprecated' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__SocksError;   /* 'SocksError' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def python_socks(ProxyError, ProxyTimeoutError, ProxyConnectionError, ProxyType)
 *  qualname: python_socks   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$python_socks(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def connector(ProxyConnector, ChainProxyConnector, ProxyInfo)
 *  qualname: connector   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$connector(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def utils(open_connection, create_connection)
 *  qualname: utils   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$utils(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _deprecated(SocksVer, SocksConnector, SocksConnectionError, SocksError)
 *  qualname: _deprecated   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$_deprecated(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def SocksError(__title__, __version__, ProxyConnector, ChainProxyConnector, ProxyInfo, ProxyType, ProxyError, ProxyConnectionError, ProxyTimeoutError, open_connection, create_connection, SocksVer, SocksConnector, SocksError, SocksConnectionError)
 *  qualname: <module aiohttp_socks>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_aiohttp_socks$SocksError(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_aiohttp_socks$python_socks(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def python_socks(ProxyError, ProxyTimeoutError, ProxyConnectionError, ProxyType): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$connector(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def connector(ProxyConnector, ChainProxyConnector, ProxyInfo): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$utils(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def utils(open_connection, create_connection): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$_deprecated(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _deprecated(SocksVer, SocksConnector, SocksConnectionError, SocksError): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_aiohttp_socks$SocksError(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def SocksError(__title__, __version__, ProxyConnector, ChainProxyConnector, ProxyInfo, ProxyType, ProxyError, ProxyConnectionError, ProxyTimeoutError, open_connection, create_connection, SocksVer, SocksConnector, SocksError, SocksConnectionError): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_aiohttp_socks(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_aiohttp_socks = module;
    moduledict_aiohttp_socks = MODULE_DICT(module_aiohttp_socks);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1412081C0
     *
     * Recovered imports (detected from module constants): */
    /*   import 0.8.4 */

    return module;
}

