/* Reconstructed C source for Python module 'core.dcom_mgr'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$dcom_mgr @ 0x1418FEAF0
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$dcom_mgr;
PyDictObject *moduledict_core$dcom_mgr;

/* Module constants: 361 entries recovered from blob chunk 'core.dcom_mgr'. */
static struct ModuleConstants {
    PyObject *const_str_plain_connected_profiles;  /* [0] str = 'connected_profiles' */
    PyObject *const_str_plain_expandvars;  /* [1] str = 'expandvars' */
    PyObject *const_tuple_1;  /* [2] tuple = ('%APPDATA%\\Microsoft\\Network\\Connections\\Pbk\\rasphone.... */
    PyObject *const_tuple_1_1;  /* [3] tuple = ('%ALLUSERSPROFILE%\\Microsoft\\Network\\Connections\\Pbk\\r... */
    PyObject *const_tuple_1_2;  /* [4] tuple = ('%PROGRAMDATA%\\Microsoft\\Network\\Connections\\Pbk\\rasph... */
    PyObject *const_str_digest_e9e2aa81;  /* [5] str = 'utf-8' */
    PyObject *const_str_plain_ignore;  /* [6] str = 'ignore' */
    PyObject *const_str_plain_re;  /* [7] str = 're' */
    PyObject *const_str_plain_match;  /* [8] str = 'match' */
    PyObject *const_str_digest_d0ac8119;  /* [9] str = '^\\[(.*)\\]\\s*$' */
    PyObject *const_str_plain_strip;  /* [10] str = 'strip' */
    PyObject *const_str_plain_group;  /* [11] str = 'group' */
    PyObject *const_tuple_1_3;  /* [12] tuple = (1,) */
    PyObject *const_str_plain_seen;  /* [13] str = 'seen' */
    PyObject *const_str_plain_add;  /* [14] str = 'add' */
    PyObject *const_str_plain_self;  /* [15] str = 'self' */
    PyObject *const_str_plain__is_vpn_profile;  /* [16] str = '_is_vpn_profile' */
    PyObject *const_str_plain__detect_carrier_from_name;  /* [17] str = '_detect_carrier_from_name' */
    PyObject *const_str_plain_profiles;  /* [18] str = 'profiles' */
    PyObject *const_str_plain_append;  /* [19] str = 'append' */
    PyObject *const_str_plain_rasdial;  /* [20] str = 'rasdial' */
    PyObject *const_str_plain_carrier;  /* [21] str = 'carrier' */
    PyObject *const_str_plain_source;  /* [22] str = 'source' */
    PyObject *const_str_digest_c260dc4b;  /* [23] str = 'rasphone.pbk' */
    PyObject *const_tuple_3;  /* [24] tuple = (None, None, None) */
    PyObject *const_str_plain_logger;  /* [25] str = 'logger' */
    PyObject *const_str_plain_debug;  /* [26] str = 'debug' */
    PyObject *const_str_digest_350c8780;  /* [27] str = 'Lỗi đọc file ' */
    PyObject *const_str_digest_e2654927;  /* [28] str = ': ' */
    PyObject *const_str_plain_subprocess;  /* [29] str = 'subprocess' */
    PyObject *const_str_plain_run;  /* [30] str = 'run' */
    PyObject *const_str_plain_CREATE_NO_WINDOW;  /* [31] str = 'CREATE_NO_WINDOW' */
    PyObject *const_tuple_1_4;  /* [32] tuple = (['rasdial'],) */
    PyObject *const_tuple_3_1;  /* [33] tuple = ('capture_output', 'text', 'creationflags') */
    PyObject *const_str_plain_stdout;  /* [34] str = 'stdout' */
    PyObject *const_str_plain_splitlines;  /* [35] str = 'splitlines' */
    PyObject *const_str_plain_startswith;  /* [36] str = 'startswith' */
    PyObject *const_tuple_1_5;  /* [37] tuple = ('No connections',) */
    PyObject *const_tuple_1_6;  /* [38] tuple = ('Command completed',) */
    PyObject *const_str_digest_36931a9a;  /* [39] str = 'kết nối' */
    PyObject *const_str_plain_active_rasdial;  /* [40] str = 'active_rasdial' */
    PyObject *const_str_digest_88402700;  /* [41] str = 'Quét tất cả profile kết nối Dial-up / Dcom thực tế (đã lọc ... */
    PyObject *const_tuple_1_7;  /* [42] tuple = ('[',) */
    PyObject *const_str_plain_endswith;  /* [43] str = 'endswith' */
    PyObject *const_tuple_1_8;  /* [44] tuple = (']',) */
    PyObject *const_tuple_4;  /* [45] tuple = ('slice', 1, -1, None) */
    PyObject *const_str_plain_curr_prof;  /* [46] str = 'curr_prof' */
    PyObject *const_tuple_1_9;  /* [47] tuple = ('Port=',) */
    PyObject *const_tuple_1_10;  /* [48] tuple = ('PreferredPort=',) */
    PyObject *const_tuple_2;  /* [49] tuple = ('=', 1) */
    PyObject *const_str_plain_upper;  /* [50] str = 'upper' */
    PyObject *const_tuple_1_11;  /* [51] tuple = ('COM',) */
    PyObject *const_str_plain_com_to_rasdial;  /* [52] str = 'com_to_rasdial' */
    PyObject *const_str_plain_winreg;  /* [53] str = 'winreg' */
    PyObject *const_str_plain_OpenKey;  /* [54] str = 'OpenKey' */
    PyObject *const_str_plain_HKEY_LOCAL_MACHINE;  /* [55] str = 'HKEY_LOCAL_MACHINE' */
    PyObject *const_str_digest_bd85b312;  /* [56] str = 'SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e96d-e325-1... */
    PyObject *const_tuple_4_1;  /* [57] tuple = ('range', 0, 128, 1) */
    PyObject *const_str_plain_EnumKey;  /* [58] str = 'EnumKey' */
    PyObject *const_str_plain_modem_class_key;  /* [59] str = 'modem_class_key' */
    PyObject *const_str_plain_QueryValueEx;  /* [60] str = 'QueryValueEx' */
    PyObject *const_str_plain_DriverDesc;  /* [61] str = 'DriverDesc' */
    PyObject *const_str_plain_AttachedTo;  /* [62] str = 'AttachedTo' */
    PyObject *const_str_plain_modem_names;  /* [63] str = 'modem_names' */
    PyObject *const_str_plain_CloseKey;  /* [64] str = 'CloseKey' */
    PyObject *const_str_digest_23c0d407;  /* [65] str = 'HARDWARE\\DEVICEMAP\\SERIALCOMM' */
    PyObject *const_tuple_4_2;  /* [66] tuple = ('range', 0, 512, 1) */
    PyObject *const_str_plain_EnumValue;  /* [67] str = 'EnumValue' */
    PyObject *const_str_plain_key;  /* [68] str = 'key' */
    PyObject *const_str_plain_reg_ports;  /* [69] str = 'reg_ports' */
    PyObject *const_str_plain_bth;  /* [70] str = 'bth' */
    PyObject *const_str_plain_bluetooth;  /* [71] str = 'bluetooth' */
    PyObject *const_str_plain_serial0;  /* [72] str = 'serial0' */
    PyObject *const_str_plain_acpi;  /* [73] str = 'acpi' */
    PyObject *const_str_plain_virtual;  /* [74] str = 'virtual' */
    PyObject *const_str_plain_com0com;  /* [75] str = 'com0com' */
    PyObject *const_str_digest_5725bbda;  /* [76] str = 'USB 3G/4G Modem' */
    PyObject *const_str_digest_5209e1d8;  /* [77] str = ' ➔ [Rasdial: ' */
    PyObject *const_str_digest_0fbd1776;  /* [78] str = ']' */
    PyObject *const_str_plain_ports;  /* [79] str = 'ports' */
    PyObject *const_str_plain_port;  /* [80] str = 'port' */
    PyObject *const_str_digest_f574aa20;  /* [81] str = ' - ' */
    PyObject *const_str_plain_com;  /* [82] str = 'com' */
    PyObject *const_str_plain_desc;  /* [83] str = 'desc' */
    PyObject *const_str_plain_rasdial_profile;  /* [84] str = 'rasdial_profile' */
    PyObject *const_str_digest_a1c991da;  /* [85] str = 'Lỗi quét cổng COM qua Registry: ' */
    PyObject *const_str_digest_e3c3e440;  /* [86] str = 'Quét danh sách cổng COM của Modem / USB Dongle 4G-5G thực t... */
    PyObject *const_str_plain_scan_com_ports;  /* [87] str = 'scan_com_ports' */
    PyObject *const_tuple_1_12;  /* [88] tuple = ('port',) */
    PyObject *const_tuple_1_13;  /* [89] tuple = ('rasdial_profile',) */
    PyObject *const_str_digest_85aa32a7;  /* [90] str = 'Tra cứu card mạng (Rasdial profile) tương ứng với 1 cổng CO... */
    PyObject *const_list_4;  /* [91] list = ['192.168.8.1', '192.168.9.1', '192.168.10.1', '192.168.100.... */
    PyObject *const_str_plain_urllib;  /* [92] str = 'urllib' */
    PyObject *const_str_plain_request;  /* [93] str = 'request' */
    PyObject *const_str_plain_Request;  /* [94] str = 'Request' */
    PyObject *const_str_digest_dbd7790b;  /* [95] str = 'http://' */
    PyObject *const_str_digest_850b2a1d;  /* [96] str = '/api/webserver/SesTokInfo' */
    PyObject *const_tuple_1_14;  /* [97] tuple = ({'User-Agent': 'Mozilla/5.0'},) */
    PyObject *const_tuple_1_15;  /* [98] tuple = ('headers',) */
    PyObject *const_str_plain_urlopen;  /* [99] str = 'urlopen' */
    PyObject *const_tuple_1_16;  /* [100] tuple = (0.6,) */
    PyObject *const_tuple_1_17;  /* [101] tuple = ('timeout',) */
    PyObject *const_str_plain_decode;  /* [102] str = 'decode' */
    PyObject *const_tuple_2_1;  /* [103] tuple = ('utf-8', 'ignore') */
    PyObject *const_tuple_1_18;  /* [104] tuple = ('errors',) */
    PyObject *const_str_digest_08b7d168;  /* [105] str = '<response>' */
    PyObject *const_str_plain_SesInfo;  /* [106] str = 'SesInfo' */
    PyObject *const_str_plain_TokInfo;  /* [107] str = 'TokInfo' */
    PyObject *const_str_plain_gateways;  /* [108] str = 'gateways' */
    PyObject *const_str_plain_ip;  /* [109] str = 'ip' */
    PyObject *const_str_plain_hilink;  /* [110] str = 'hilink' */
    PyObject *const_str_plain_url;  /* [111] str = 'url' */
    PyObject *const_str_plain_model;  /* [112] str = 'model' */
    PyObject *const_str_digest_5edc2965;  /* [113] str = 'Huawei/ZTE HiLink Dongle' */
    PyObject *const_str_digest_1bb86b35;  /* [114] str = 'Quét các Gateway HiLink của Huawei/ZTE USB Dongle (chỉ nhận... */
    PyObject *const_str_plain_VPN_EXCLUDE_KEYWORDS;  /* [115] str = 'VPN_EXCLUDE_KEYWORDS' */
    PyObject *const_str_digest_6723a68d;  /* [116] str = 'Kiểm tra xem tên profile có phải là phần mềm VPN thương mại... */
    PyObject *const_str_plain_scan_rasdial_profiles;  /* [117] str = 'scan_rasdial_profiles' */
    PyObject *const_str_plain_com_ports;  /* [118] str = 'com_ports' */
    PyObject *const_str_plain_scan_hilink_gateways;  /* [119] str = 'scan_hilink_gateways' */
    PyObject *const_str_digest_4ece7230;  /* [120] str = 'Thực hiện quét toàn diện: Rasdial Profiles + COM Ports + Hi... */
    PyObject *const_str_digest_81541726;  /* [121] str = '[' */
    PyObject *const_str_plain_rstrip;  /* [122] str = 'rstrip' */
    PyObject *const_tuple_1_19;  /* [123] tuple = ('\r\n',) */
    PyObject *const_str_plain_lines;  /* [124] str = 'lines' */
    PyObject *const_str_plain_in_target;  /* [125] str = 'in_target' */
    PyObject *const_str_plain_found_prioritize;  /* [126] str = 'found_prioritize' */
    PyObject *const_str_plain_new_lines;  /* [127] str = 'new_lines' */
    PyObject *const_str_digest_8c0abe03;  /* [128] str = 'IpPrioritizeRemote=0' */
    PyObject *const_tuple_1_20;  /* [129] tuple = ('IpPrioritizeRemote=',) */
    PyObject *const_str_digest_81051bcc;  /* [130] str = '\r\n' */
    PyObject *const_str_plain_write;  /* [131] str = 'write' */
    PyObject *const_str_plain_warning;  /* [132] str = 'warning' */
    PyObject *const_str_digest_228925fd;  /* [133] str = 'Không thể cấu hình pbk tại ' */
    PyObject *const_str_plain_modified_any;  /* [134] str = 'modified_any' */
    PyObject *const_str_digest_24331a10;  /* [135] str = '\n        Cấu hình Profile Rasdial độc lập (IpPrioritizeRem... */
    PyObject *const_tuple_2_2;  /* [136] tuple = ('rotate_mode', 'rasdial') */
    PyObject *const_str_plain_info;  /* [137] str = 'info' */
    PyObject *const_str_digest_eb31dc6c;  /* [138] str = 'Đang ngắt kết nối Rasdial: ' */
    PyObject *const_str_digest_11c0d066;  /* [139] str = '/disconnect' */
    PyObject *const_int_pos_10;  /* [140] int = 10 */
    PyObject *const_tuple_4_3;  /* [141] tuple = ('capture_output', 'text', 'creationflags', 'timeout') */
    PyObject *const_tuple_1_21;  /* [142] tuple = ('hilink_ip',) */
    PyObject *const_str_digest_8281aea9;  /* [143] str = '192.168.8.1' */
    PyObject *const_str_plain__set_hilink_data;  /* [144] str = '_set_hilink_data' */
    PyObject *const_tuple_1_22;  /* [145] tuple = (False,) */
    PyObject *const_tuple_1_23;  /* [146] tuple = ('enable',) */
    PyObject *const_str_plain_com_at;  /* [147] str = 'com_at' */
    PyObject *const_tuple_1_24;  /* [148] tuple = ('com_port',) */
    PyObject *const_str_plain_COM3;  /* [149] str = 'COM3' */
    PyObject *const_str_plain__send_at_command;  /* [150] str = '_send_at_command' */
    PyObject *const_bytes_digest_ec2826cb;  /* [151] bytes = b'AT+CFUN=0\r\n' */
    PyObject *const_str_digest_138dbee4;  /* [152] str = 'Lỗi khi ngắt kết nối Dcom: ' */
    PyObject *const_str_digest_d0088406;  /* [153] str = 'Ngắt kết nối phần cứng mạng của Dcom khi tắt proxy hoặc xóa... */
    PyObject *const_str_plain_get_interface_for_com;  /* [154] str = 'get_interface_for_com' */
    PyObject *const_str_plain_ensure_profile_isolated;  /* [155] str = 'ensure_profile_isolated' */
    PyObject *const_tuple_1_25;  /* [156] tuple = ('rasdial_user',) */
    PyObject *const_tuple_1_26;  /* [157] tuple = ('rasdial_pass',) */
    PyObject *const_str_digest_3fca46c8;  /* [158] str = 'Đang kết nối lại Rasdial: ' */
    PyObject *const_int_pos_20;  /* [159] int = 20 */
    PyObject *const_str_plain_returncode;  /* [160] str = 'returncode' */
    PyObject *const_str_digest_e9921ce4;  /* [161] str = 'Successfully connected' */
    PyObject *const_str_digest_fee95f5e;  /* [162] str = 'đã kết nối' */
    PyObject *const_str_plain_setup_interface_isolated_route;  /* [163] str = 'setup_interface_isolated_route' */
    PyObject *const_str_digest_c4e2cb75;  /* [164] str = '✅ Đã kết nối thành công Rasdial: ' */
    PyObject *const_str_digest_3833fed6;  /* [165] str = "Cảnh báo kết nối Rasdial '" */
    PyObject *const_str_digest_2bc31585;  /* [166] str = "': " */
    PyObject *const_str_plain_stderr;  /* [167] str = 'stderr' */
    PyObject *const_tuple_1_27;  /* [168] tuple = (True,) */
    PyObject *const_str_digest_1b274c56;  /* [169] str = 'Lỗi khi kết nối lại Dcom: ' */
    PyObject *const_str_digest_1c7c0fa6;  /* [170] str = 'Kết nối lại phần cứng mạng của Dcom khi bật lại switch prox... */
    PyObject *const_str_digest_9419a9f4;  /* [171] str = "Get-NetIPAddress -InterfaceAlias '" */
    PyObject *const_str_digest_8ef30cfd;  /* [172] str = "' -AddressFamily IPv4 -ErrorAction SilentlyContinue | ForEa... */
    PyObject *const_str_plain_powershell;  /* [173] str = 'powershell' */
    PyObject *const_str_digest_4089c192;  /* [174] str = '-NoProfile' */
    PyObject *const_str_digest_0bc69e2a;  /* [175] str = '-Command' */
    PyObject *const_int_pos_6;  /* [176] int = 6 */
    PyObject *const_tuple_3_2;  /* [177] tuple = ('capture_output', 'creationflags', 'timeout') */
    PyObject *const_str_digest_2f97f4a8;  /* [178] str = "⚡ Đã thiết lập Isolated Outbound Route (Metric 500) cho Dco... */
    PyObject *const_str_digest_3590cb8a;  /* [179] str = "'" */
    PyObject *const_str_digest_f1897011;  /* [180] str = 'Không thể tạo route phụ cho Dcom: ' */
    PyObject *const_str_digest_b7830dd5;  /* [181] str = '\n        Cấp thêm tuyến định tuyến 0.0.0.0/0 (Metric 500) ... */
    PyObject *const_float_3_5;  /* [182] float = 3.5 */
    PyObject *const_tuple_2_3;  /* [183] tuple = ('delay_preset', 'default') */
    PyObject *const_str_plain_viettel;  /* [184] str = 'viettel' */
    PyObject *const_float_2_5;  /* [185] float = 2.5 */
    PyObject *const_str_plain_vinaphone;  /* [186] str = 'vinaphone' */
    PyObject *const_float_4_5;  /* [187] float = 4.5 */
    PyObject *const_str_plain_mobifone;  /* [188] str = 'mobifone' */
    PyObject *const_float_5_5;  /* [189] float = 5.5 */
    PyObject *const_str_plain_custom;  /* [190] str = 'custom' */
    PyObject *const_tuple_1_28;  /* [191] tuple = ('delay_seconds',) */
    PyObject *const_tuple_2_4;  /* [192] tuple = (False, 'Chưa chọn hoặc thiếu Tên Profile Rasdial') */
    PyObject *const_str_digest_91846c63;  /* [193] str = 'Chờ ' */
    PyObject *const_str_digest_70bf27df;  /* [194] str = 's ngắt sóng để trạm BTS cấp IP mới...' */
    PyObject *const_str_plain_time;  /* [195] str = 'time' */
    PyObject *const_str_plain_sleep;  /* [196] str = 'sleep' */
    PyObject *const_str_digest_93570dd9;  /* [197] str = 'connected to' */
    PyObject *const_tuple_1_29;  /* [198] tuple = (1.0,) */
    PyObject *const_str_digest_5d1aecbc;  /* [199] str = "Xoay IP Rasdial '" */
    PyObject *const_str_digest_9500891a;  /* [200] str = "' thành công" */
    PyObject *const_str_digest_ccdeea65;  /* [201] str = 'Thử kết nối lại lần 2 cho ' */
    PyObject *const_str_digest_2f43b42f;  /* [202] str = '...' */
    PyObject *const_tuple_1_30;  /* [203] tuple = (2.5,) */
    PyObject *const_str_digest_2bf8e87e;  /* [204] str = "' thành công (Lần 2)" */
    PyObject *const_str_digest_293035fa;  /* [205] str = 'Lỗi kết nối lại' */
    PyObject *const_str_digest_22c65f33;  /* [206] str = 'Lỗi Rasdial: ' */
    PyObject *const_str_plain__rotate_hilink;  /* [207] str = '_rotate_hilink' */
    PyObject *const_str_plain__rotate_com_at;  /* [208] str = '_rotate_com_at' */
    PyObject *const_str_digest_32b24b49;  /* [209] str = "Kết nối lại Rasdial profile '" */
    PyObject *const_str_digest_7747e5a6;  /* [210] str = "' sau khi reset sóng COM..." */
    PyObject *const_str_plain_connect_dcom;  /* [211] str = 'connect_dcom' */
    PyObject *const_str_plain_rotate_mode;  /* [212] str = 'rotate_mode' */
    PyObject *const_str_plain_custom_cmd;  /* [213] str = 'custom_cmd' */
    PyObject *const_tuple_1_31;  /* [214] tuple = ('custom_cmd',) */
    PyObject *const_tuple_2_5;  /* [215] tuple = (False, 'Chưa nhập lệnh xoay Custom Command') */
    PyObject *const_str_digest_71b5bb6f;  /* [216] str = 'Thực thi Custom Command: ' */
    PyObject *const_int_pos_15;  /* [217] int = 15 */
    PyObject *const_tuple_5;  /* [218] tuple = ('shell', 'capture_output', 'text', 'timeout', 'creationflag... */
    PyObject *const_tuple_2_6;  /* [219] tuple = (True, 'Thực thi Custom Command thành công') */
    PyObject *const_str_digest_ac916ffd;  /* [220] str = 'Lỗi lệnh: ' */
    PyObject *const_str_digest_ba579294;  /* [221] str = 'Chế độ xoay không hỗ trợ: ' */
    PyObject *const_str_plain_TimeoutExpired;  /* [222] str = 'TimeoutExpired' */
    PyObject *const_tuple_2_7;  /* [223] tuple = (False, 'Lỗi: Quá thời gian thực thi lệnh (Timeout > 15s)') */
    PyObject *const_str_plain_error;  /* [224] str = 'error' */
    PyObject *const_str_digest_32d462a1;  /* [225] str = 'Lỗi xoay IP Dcom: ' */
    PyObject *const_str_digest_75a6bff0;  /* [226] str = 'Lỗi ngoại lệ: ' */
    PyObject *const_str_digest_6e1ee440;  /* [227] str = '\n        Thực hiện xoay IP cho 1 Dcom dựa theo mode cấu hì... */
    PyObject *const_str_digest_b08c6262;  /* [228] str = 'urllib.request' */
    PyObject *const_str_digest_2e14fd00;  /* [229] str = 'xml.etree.ElementTree' */
    PyObject *const_str_plain_etree;  /* [230] str = 'etree' */
    PyObject *const_str_plain_ElementTree;  /* [231] str = 'ElementTree' */
    PyObject *const_tuple_1_32;  /* [232] tuple = (2.0,) */
    PyObject *const_str_plain_fromstring;  /* [233] str = 'fromstring' */
    PyObject *const_str_plain_findtext;  /* [234] str = 'findtext' */
    PyObject *const_tuple_1_33;  /* [235] tuple = ('SesInfo',) */
    PyObject *const_tuple_1_34;  /* [236] tuple = ('TokInfo',) */
    PyObject *const_dict_1;  /* [237] dict = {'Content-Type': 'application/x-www-form-urlencoded; charset... */
    PyObject *const_str_plain_Cookie;  /* [238] str = 'Cookie' */
    PyObject *const_str_plain___RequestVerificationToken;  /* [239] str = '__RequestVerificationToken' */
    PyObject *const_str_digest_8e7aed21;  /* [240] str = '/api/dialup/mobile-dataswitch' */
    PyObject *const_bytes_digest_4b25ab2b;  /* [241] bytes = b'<?xml version="1.0" encoding="UTF-8"?><request><dataswitch... */
    PyObject *const_str_plain_POST;  /* [242] str = 'POST' */
    PyObject *const_tuple_3_3;  /* [243] tuple = ('data', 'headers', 'method') */
    PyObject *const_tuple_1_35;  /* [244] tuple = (3.0,) */
    PyObject *const_tuple_1_36;  /* [245] tuple = (1.5,) */
    PyObject *const_bytes_digest_4375b176;  /* [246] bytes = b'<?xml version="1.0" encoding="UTF-8"?><request><dataswitch... */
    PyObject *const_str_digest_d9e64c25;  /* [247] str = '<response>OK</response>' */
    PyObject *const_str_plain_status;  /* [248] str = 'status' */
    PyObject *const_int_pos_200;  /* [249] int = 200 */
    PyObject *const_str_digest_bebcbdbf;  /* [250] str = 'Xoay IP HiLink (' */
    PyObject *const_str_digest_9f530b41;  /* [251] str = ') thành công' */
    PyObject *const_str_digest_79db35dd;  /* [252] str = 'Đã gửi lệnh xoay IP tới HiLink (' */
    PyObject *const_str_digest_9371d7a2;  /* [253] str = ')' */
    PyObject *const_str_digest_e5762c3d;  /* [254] str = 'Lỗi kết nối HiLink ' */
    PyObject *const_str_digest_39a0457e;  /* [255] str = 'Gửi lệnh đổi dữ liệu di động qua Web API của HiLink Huawei/... */
    PyObject *const_tuple_2_8;  /* [256] tuple = ('', '') */
    PyObject *const_str_digest_c4ca4238;  /* [257] str = '1' */
    PyObject *const_str_digest_cfcd2084;  /* [258] str = '0' */
    PyObject *const_str_digest_bcfbda46;  /* [259] str = '<?xml version="1.0" encoding="UTF-8"?><request><dataswitch>... */
    PyObject *const_str_digest_21540b09;  /* [260] str = '</dataswitch></request>' */
    PyObject *const_str_digest_2bbfc756;  /* [261] str = 'Bật hoặc tắt kết nối dữ liệu di động HiLink.' */
    PyObject *const_bytes_digest_8ac07bdb;  /* [262] bytes = b'AT+CFUN=1\r\n' */
    PyObject *const_str_digest_8d14b7f2;  /* [263] str = 'Xoay IP qua cổng ' */
    PyObject *const_str_digest_dee80d69;  /* [264] str = ' thành công' */
    PyObject *const_str_digest_061e5340;  /* [265] str = 'Không thể gửi lệnh AT Command tới cổng ' */
    PyObject *const_str_digest_e443c2a5;  /* [266] str = 'Gửi lệnh AT Command qua cổng Serial COM (AT+CFUN=0/1) với t... */
    PyObject *const_tuple_6;  /* [267] tuple = ('COM10', 'COM8', 'COM9', 'COM3', 'COM4', 'COM11') */
    PyObject *const_str_plain_ports_to_try;  /* [268] str = 'ports_to_try' */
    PyObject *const_str_plain_serial;  /* [269] str = 'serial' */
    PyObject *const_str_plain_Serial;  /* [270] str = 'Serial' */
    PyObject *const_int_pos_115200;  /* [271] int = 115200 */
    PyObject *const_str_plain_command;  /* [272] str = 'command' */
    PyObject *const_tuple_1_37;  /* [273] tuple = (0.2,) */
    PyObject *const_str_digest_2131a6de;  /* [274] str = 'Gửi lệnh AT Command qua cổng COM Serial (tự động thử các cổ... */
    PyObject *const_str_plain_vt;  /* [275] str = 'vt' */
    PyObject *const_str_plain_Viettel;  /* [276] str = 'Viettel' */
    PyObject *const_str_plain_vina;  /* [277] str = 'vina' */
    PyObject *const_str_plain_vnpt;  /* [278] str = 'vnpt' */
    PyObject *const_str_plain_Vinaphone;  /* [279] str = 'Vinaphone' */
    PyObject *const_str_plain_mobi;  /* [280] str = 'mobi' */
    PyObject *const_str_plain_vms;  /* [281] str = 'vms' */
    PyObject *const_str_plain_Mobifone;  /* [282] str = 'Mobifone' */
    PyObject *const_str_plain_vietnamobile;  /* [283] str = 'vietnamobile' */
    PyObject *const_str_plain_vnm;  /* [284] str = 'vnm' */
    PyObject *const_str_plain_Vietnamobile;  /* [285] str = 'Vietnamobile' */
    PyObject *const_str_digest_1c4d1273;  /* [286] str = '4G/5G Cellular' */
    PyObject *const_str_digest_e5586d87;  /* [287] str = 'Nhận diện tên nhà mạng từ tên profile kết nối.' */
    PyObject *const_str_plain_origin;  /* [288] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [289] str = 'has_location' */
    PyObject *const_str_plain_os;  /* [290] str = 'os' */
    PyObject *const_str_plain_sys;  /* [291] str = 'sys' */
    PyObject *const_str_plain_socket;  /* [292] str = 'socket' */
    PyObject *const_str_plain_logging;  /* [293] str = 'logging' */
    PyObject *const_str_plain_asyncio;  /* [294] str = 'asyncio' */
    PyObject *const_str_digest_16d628fa;  /* [295] str = 'urllib.parse' */
    PyObject *const_str_plain_Dict;  /* [296] str = 'Dict' */
    PyObject *const_str_plain_List;  /* [297] str = 'List' */
    PyObject *const_str_plain_Optional;  /* [298] str = 'Optional' */
    PyObject *const_str_plain_Tuple;  /* [299] str = 'Tuple' */
    PyObject *const_str_plain_getLogger;  /* [300] str = 'getLogger' */
    PyObject *const_tuple_1_38;  /* [301] tuple = ('DcomManager',) */
    PyObject *const_int_digest_9ab98b1f;  /* [302] int = 134217728 */
    PyObject *const_list_21;  /* [303] list = ['purevpn', 'nordvpn', 'expressvpn', 'surfshark', 'pia', 'pr... */
    PyObject *const_str_digest_7d9cf8b2;  /* [304] str = 'core.dcom_mgr' */
    PyObject *const_str_digest_159229be;  /* [305] str = '\n    Quản lý phần cứng Dcom / USB 4G-5G, quét thiết bị và ... */
    PyObject *const_str_plain_DcomManager;  /* [306] str = 'DcomManager' */
    PyObject *const_str_plain___qualname__;  /* [307] str = '__qualname__' */
    PyObject *const_str_digest_0f9e089a;  /* [308] str = 'DcomManager.__init__' */
    PyObject *const_str_plain_return;  /* [309] str = 'return' */
    PyObject *const_str_digest_8f85e646;  /* [310] str = 'DcomManager.scan_rasdial_profiles' */
    PyObject *const_str_digest_ca9a5971;  /* [311] str = 'DcomManager.scan_com_ports' */
    PyObject *const_str_plain_com_port;  /* [312] str = 'com_port' */
    PyObject *const_str_digest_e8e4597d;  /* [313] str = 'DcomManager.get_interface_for_com' */
    PyObject *const_str_digest_edea263f;  /* [314] str = 'DcomManager.scan_hilink_gateways' */
    PyObject *const_dict_2;  /* [315] dict = {'name': 'str', 'return': 'bool'} */
    PyObject *const_str_digest_7e699e92;  /* [316] str = 'DcomManager._is_vpn_profile' */
    PyObject *const_str_plain_full_scan;  /* [317] str = 'full_scan' */
    PyObject *const_str_digest_3d2bebc1;  /* [318] str = 'DcomManager.full_scan' */
    PyObject *const_dict_2_1;  /* [319] dict = {'profile_name': 'str', 'return': 'bool'} */
    PyObject *const_str_digest_d9904199;  /* [320] str = 'DcomManager.ensure_profile_isolated' */
    PyObject *const_str_plain_config;  /* [321] str = 'config' */
    PyObject *const_str_plain_disconnect_dcom;  /* [322] str = 'disconnect_dcom' */
    PyObject *const_str_digest_18b789d9;  /* [323] str = 'DcomManager.disconnect_dcom' */
    PyObject *const_str_digest_bc988228;  /* [324] str = 'DcomManager.connect_dcom' */
    PyObject *const_dict_1_1;  /* [325] dict = {'profile_name': 'str'} */
    PyObject *const_str_digest_bc31585d;  /* [326] str = 'DcomManager.setup_interface_isolated_route' */
    PyObject *const_tuple_2_9;  /* [327] tuple = ('bool', 'str') */
    PyObject *const_str_plain_rotate_ip;  /* [328] str = 'rotate_ip' */
    PyObject *const_str_digest_b713221c;  /* [329] str = 'DcomManager.rotate_ip' */
    PyObject *const_str_plain_gateway_ip;  /* [330] str = 'gateway_ip' */
    PyObject *const_str_digest_5c8fc9e9;  /* [331] str = 'DcomManager._rotate_hilink' */
    PyObject *const_dict_3;  /* [332] dict = {'gateway_ip': 'str', 'enable': 'bool', 'return': 'bool'} */
    PyObject *const_str_digest_6970bc12;  /* [333] str = 'DcomManager._set_hilink_data' */
    PyObject *const_tuple_1_39;  /* [334] tuple = (3.5,) */
    PyObject *const_str_plain_delay_seconds;  /* [335] str = 'delay_seconds' */
    PyObject *const_str_digest_8ee94483;  /* [336] str = 'DcomManager._rotate_com_at' */
    PyObject *const_dict_3_1;  /* [337] dict = {'com_port': 'str', 'command': 'bytes', 'return': 'bool'} */
    PyObject *const_str_digest_3b3fff41;  /* [338] str = 'DcomManager._send_at_command' */
    PyObject *const_dict_2_2;  /* [339] dict = {'name': 'str', 'return': 'str'} */
    PyObject *const_str_digest_17eb01f5;  /* [340] str = 'DcomManager._detect_carrier_from_name' */
    PyObject *const_str_plain_dcom_mgr;  /* [341] str = 'dcom_mgr' */
    PyObject *const_str_digest_283ab0d3;  /* [342] str = 'core\\dcom_mgr.py' */
    PyObject *const_str_digest_83c8158b;  /* [343] str = '<module core.dcom_mgr>' */
    PyObject *const_tuple_1_40;  /* [344] tuple = ('__class__',) */
    PyObject *const_tuple_1_41;  /* [345] tuple = ('self',) */
    PyObject *const_tuple_3_4;  /* [346] tuple = ('self', 'name', 'nl') */
    PyObject *const_tuple_4_4;  /* [347] tuple = ('self', 'name', 'nl', 'vpn') */
    PyObject *const_tuple_5_1;  /* [348] tuple = ('self', 'com_port', 'delay_seconds', 'ok1', 'ok2') */
    PyObject *const_tuple_18;  /* [349] tuple = ('self', 'gateway_ip', 'urllib', 'ET', 'base_url', 'session_... */
    PyObject *const_tuple_8;  /* [350] tuple = ('self', 'com_port', 'command', 'ports_to_try', 'candidate',... */
    PyObject *const_tuple_15;  /* [351] tuple = ('self', 'gateway_ip', 'enable', 'urllib', 'ET', 'base_url',... */
    PyObject *const_tuple_10;  /* [352] tuple = ('self', 'config', 'mode', 'profile', 'username', 'password'... */
    PyObject *const_tuple_7;  /* [353] tuple = ('self', 'config', 'mode', 'profile', 'gateway_ip', 'com_por... */
    PyObject *const_tuple_15_1;  /* [354] tuple = ('self', 'profile_name', 'pbk_paths', 'target_header', 'modi... */
    PyObject *const_tuple_5_2;  /* [355] tuple = ('self', 'com_port', 'com_upper', 'ports', 'p') */
    PyObject *const_tuple_19;  /* [356] tuple = ('self', 'config', 'mode', 'profile', 'delay', 'preset', 'us... */
    PyObject *const_tuple_30;  /* [357] tuple = ('self', 'ports', 'com_to_rasdial', 'pbk_paths', 'p', 'f', '... */
    PyObject *const_tuple_7_1;  /* [358] tuple = ('self', 'gateways', 'candidate_ips', 'ip', 'req', 'resp', '... */
    PyObject *const_tuple_14;  /* [359] tuple = ('self', 'profiles', 'seen', 'pbk_paths', 'path', 'f', 'line... */
    PyObject *const_tuple_4_5;  /* [360] tuple = ('self', 'profile_name', 'cmd', 'e') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.dcom_mgr"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__stdout;   /* 'stdout' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__upper;   /* 'upper' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__scan_com_ports;   /* 'scan_com_ports' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__scan_com_ports;   /* 'scan_com_ports' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__urlopen;   /* 'urlopen' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__decode;   /* 'decode' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__decode;   /* 'decode' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__info;   /* 'info' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8___set_hilink_data;   /* '_set_hilink_data' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9___set_hilink_data;   /* '_set_hilink_data' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__com_at;   /* 'com_at' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__com_at;   /* 'com_at' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__ensure_profile_isolated;   /* 'ensure_profile_isolated' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__ensure_profile_isolated;   /* 'ensure_profile_isolated' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__powershell;   /* 'powershell' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__viettel;   /* 'viettel' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_16__custom;   /* 'custom' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_17__custom_cmd;   /* 'custom_cmd' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_18__TimeoutExpired;   /* 'TimeoutExpired' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_19__findtext;   /* 'findtext' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_20__findtext;   /* 'findtext' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_21__POST;   /* 'POST' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_22__ports_to_try;   /* 'ports_to_try' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_23__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_24__rotate_ip;   /* 'rotate_ip' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_25__dcom_mgr;   /* 'dcom_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_26__dcom_mgr;   /* 'dcom_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_27__dcom_mgr$gt$;   /* 'dcom_mgr>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_28__dcom_mgr$gt$;   /* 'dcom_mgr>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def stdout(capture_output, text, creationflags)
 *  qualname: stdout   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$stdout(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def upper(COM)
 *  qualname: upper   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$upper(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def scan_com_ports(port)
 *  qualname: scan_com_ports   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$scan_com_ports(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def scan_com_ports(rasdial_profile)
 *  qualname: scan_com_ports   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$scan_com_ports(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def urlopen(headers)
 *  qualname: urlopen   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$urlopen(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def decode(timeout)
 *  qualname: <response>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$decode(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def decode(errors)
 *  qualname: <response>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$decode(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def info(rotate_mode, rasdial)
 *  qualname: info   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$info(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _set_hilink_data(capture_output, text, creationflags, timeout)
 *  qualname: _set_hilink_data   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$_set_hilink_data(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _set_hilink_data(hilink_ip)
 *  qualname: _set_hilink_data   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$_set_hilink_data(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def com_at(enable)
 *  qualname: com_at   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$com_at(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def com_at(com_port)
 *  qualname: com_at   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$com_at(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ensure_profile_isolated(rasdial_user)
 *  qualname: ensure_profile_isolated   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$ensure_profile_isolated(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ensure_profile_isolated(rasdial_pass)
 *  qualname: ensure_profile_isolated   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$ensure_profile_isolated(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def powershell(capture_output, creationflags, timeout)
 *  qualname: powershell   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$powershell(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def viettel(delay_preset, default)
 *  qualname: viettel   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$viettel(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def custom(delay_seconds)
 *  qualname: custom   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$custom(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def custom_cmd(custom_cmd)
 *  qualname: custom_cmd   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$custom_cmd(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def TimeoutExpired(shell, capture_output, text, timeout, creationflags)
 *  qualname: TimeoutExpired   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$TimeoutExpired(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def findtext(SesInfo)
 *  qualname: findtext   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$findtext(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def findtext(TokInfo)
 *  qualname: findtext   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$findtext(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def POST(data, headers, method)
 *  qualname: <response>OK</response>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$POST(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def ports_to_try(COM10, COM8, COM9, COM3, COM4, COM11)
 *  qualname: ports_to_try   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$ports_to_try(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(DcomManager)
 *  qualname: core.dcom_mgr   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def dcom_mgr(__class__)
 *  qualname: <module core.dcom_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$dcom_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def dcom_mgr(self)
 *  qualname: <module core.dcom_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$dcom_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def dcom_mgr>(self, name, nl)
 *  qualname: <module core.dcom_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$dcom_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def dcom_mgr>(self, name, nl, vpn)
 *  qualname: <module core.dcom_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$dcom_mgr$dcom_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: DcomManager
 *   methods recovered: 1
 *   class body was also compiled to native code */
static PyObject *impl_core$dcom_mgr$DcomManager$rotate_ip(PyThreadState *tstate, PyObject **python_pars);  /* def DcomManager.rotate_ip(bool, str) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$dcom_mgr$stdout(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def stdout(capture_output, text, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$upper(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def upper(COM): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$scan_com_ports(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def scan_com_ports(port): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$scan_com_ports(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def scan_com_ports(rasdial_profile): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$urlopen(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def urlopen(headers): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$decode(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def decode(timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$decode(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def decode(errors): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$info(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def info(rotate_mode, rasdial): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$_set_hilink_data(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _set_hilink_data(capture_output, text, creationflags, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$_set_hilink_data(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _set_hilink_data(hilink_ip): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$com_at(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def com_at(enable): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$com_at(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def com_at(com_port): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$ensure_profile_isolated(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ensure_profile_isolated(rasdial_user): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$ensure_profile_isolated(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ensure_profile_isolated(rasdial_pass): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$powershell(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def powershell(capture_output, creationflags, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$viettel(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def viettel(delay_preset, default): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$custom(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def custom(delay_seconds): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$custom_cmd(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def custom_cmd(custom_cmd): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$TimeoutExpired(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def TimeoutExpired(shell, capture_output, text, timeout, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$findtext(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def findtext(SesInfo): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$findtext(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def findtext(TokInfo): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$POST(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def POST(data, headers, method): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$ports_to_try(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def ports_to_try(COM10, COM8, COM9, COM3, COM4, COM11): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(DcomManager): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$dcom_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def dcom_mgr(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$dcom_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def dcom_mgr(self): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$dcom_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def dcom_mgr>(self, name, nl): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$dcom_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def dcom_mgr>(self, name, nl, vpn): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$dcom_mgr$DcomManager$rotate_ip(PyThreadState *tstate, PyObject **python_pars) {
    /* def DcomManager.rotate_ip(bool, str): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$dcom_mgr(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$dcom_mgr = module;
    moduledict_core$dcom_mgr = MODULE_DICT(module_core$dcom_mgr);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1418FEAF0
     *
     * Recovered imports (detected from module constants): */
    /*   import rasphone.pbk */
    /*   import 192.168.8.1 */
    /*   import urllib.request */
    /*   import xml.etree.ElementTree */
    /*   import urllib.parse */
    /*   import core.dcom_mgr */
    /*   import DcomManager.__init__ */
    /*   import DcomManager.scan_rasdial_profiles */
    /*   import DcomManager.scan_com_ports */
    /*   import DcomManager.get_interface_for_com */
    /*   import DcomManager.scan_hilink_gateways */
    /*   import DcomManager._is_vpn_profile */
    /*   import DcomManager.full_scan */
    /*   import DcomManager.ensure_profile_isolated */
    /*   import DcomManager.disconnect_dcom */
    /*   import DcomManager.connect_dcom */
    /*   import DcomManager.setup_interface_isolated_route */
    /*   import DcomManager.rotate_ip */
    /*   import DcomManager._rotate_hilink */
    /*   import DcomManager._set_hilink_data */
    /*   import DcomManager._rotate_com_at */
    /*   import DcomManager._send_at_command */
    /*   import DcomManager._detect_carrier_from_name */

    return module;
}

