/* Reconstructed C source for Python module 'core.ipv6'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$ipv6 @ 0x1419020C0
 * Flags: PACKAGE, TRANSLATED
 * Is package: True
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$ipv6;
PyDictObject *moduledict_core$ipv6;

/* Module constants: 10 entries recovered from blob chunk 'core.ipv6'. */
static struct ModuleConstants {
    PyObject *const_str_plain_join;  /* [0] str = 'join' */
    PyObject *const_str_plain_environ;  /* [1] str = 'environ' */
    PyObject *const_tuple_2;  /* [2] tuple = ('NUITKA_PACKAGE_core', '\\not_existing') */
    PyObject *const_str_plain_ipv6;  /* [3] str = 'ipv6' */
    PyObject *const_tuple_2_1;  /* [4] tuple = ('NUITKA_PACKAGE_core_ipv6', '\\not_existing') */
    PyObject *const_str_plain_origin;  /* [5] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [6] str = 'has_location' */
    PyObject *const_str_plain_submodule_search_locations;  /* [7] str = 'submodule_search_locations' */
    PyObject *const_str_digest_43c11d93;  /* [8] str = 'core\\ipv6\\__init__.py' */
    PyObject *const_str_digest_8ac409a9;  /* [9] str = '<module core.ipv6>' */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.ipv6"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */


/* === Free function signatures =============================== */

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$ipv6(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$ipv6 = module;
    moduledict_core$ipv6 = MODULE_DICT(module_core$ipv6);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1419020C0
     *
     * Recovered imports (detected from module constants): */

    return module;
}

