/* Reconstructed C source for Python module 'core.licensing'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$licensing @ 0x141998650
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$licensing;
PyDictObject *moduledict_core$licensing;

/* Module constants: 221 entries recovered from blob chunk 'core.licensing'. */
static struct ModuleConstants {
    PyObject *const_str_plain_base64;  /* [0] str = 'base64' */
    PyObject *const_str_plain_b64decode;  /* [1] str = 'b64decode' */
    PyObject *const_str_digest_f454b15d;  /* [2] str = 'Decrypts XOR obfuscated base64 strings.' */
    PyObject *const_int_pos_90;  /* [3] int = 90 */
    PyObject *const_str_digest_a49c8f51;  /* [4] str = '<genexpr>' */
    PyObject *const_str_digest_05629743;  /* [5] str = '_o.<locals>.<genexpr>' */
    PyObject *const_str_plain_app_name;  /* [6] str = 'app_name' */
    PyObject *const_str_plain_last_error;  /* [7] str = 'last_error' */
    PyObject *const_str_plain_license_info;  /* [8] str = 'license_info' */
    PyObject *const_str_plain_frozen;  /* [9] str = 'frozen' */
    PyObject *const_str_plain_executable;  /* [10] str = 'executable' */
    PyObject *const_str_plain_join;  /* [11] str = 'join' */
    PyObject *const_str_plain__o;  /* [12] str = '_o' */
    PyObject *const_tuple_1;  /* [13] tuple = ('PjsuO3U2Mzk/NCk/dD47Lg==',) */
    PyObject *const_tuple_1_1;  /* [14] tuple = ('/',) */
    PyObject *const_str_plain_license_file;  /* [15] str = 'license_file' */
    PyObject *const_str_plain_makedirs;  /* [16] str = 'makedirs' */
    PyObject *const_tuple_1_2;  /* [17] tuple = (True,) */
    PyObject *const_tuple_1_3;  /* [18] tuple = ('exist_ok',) */
    PyObject *const_str_plain_config;  /* [19] str = 'config' */
    PyObject *const_str_digest_171f5de3;  /* [20] str = 'license.dat' */
    PyObject *const_str_plain_configs;  /* [21] str = 'configs' */
    PyObject *const_str_plain_self;  /* [22] str = 'self' */
    PyObject *const_str_plain_shutil;  /* [23] str = 'shutil' */
    PyObject *const_str_plain_copy2;  /* [24] str = 'copy2' */
    PyObject *const_str_plain_get_hwid;  /* [25] str = 'get_hwid' */
    PyObject *const_str_plain_LicenseManager;  /* [26] str = 'LicenseManager' */
    PyObject *const_str_plain__hwid_cache;  /* [27] str = '_hwid_cache' */
    PyObject *const_str_plain_subprocess;  /* [28] str = 'subprocess' */
    PyObject *const_str_plain_run;  /* [29] str = 'run' */
    PyObject *const_tuple_4;  /* [30] tuple = (['powershell', '-NoProfile', '-NonInteractive', '-Command',... */
    PyObject *const_tuple_3;  /* [31] tuple = ('capture_output', 'text', 'creationflags') */
    PyObject *const_str_plain_stdout;  /* [32] str = 'stdout' */
    PyObject *const_str_plain_strip;  /* [33] str = 'strip' */
    PyObject *const_tuple_4_1;  /* [34] tuple = (['powershell', '-NoProfile', '-NonInteractive', '-Command',... */
    PyObject *const_str_digest_336d5ebc;  /* [35] str = '-' */
    PyObject *const_str_plain_hashlib;  /* [36] str = 'hashlib' */
    PyObject *const_str_plain_sha256;  /* [37] str = 'sha256' */
    PyObject *const_str_plain_hexdigest;  /* [38] str = 'hexdigest' */
    PyObject *const_tuple_4_2;  /* [39] tuple = ('slice', None, 24, None) */
    PyObject *const_str_plain_upper;  /* [40] str = 'upper' */
    PyObject *const_str_plain_platform;  /* [41] str = 'platform' */
    PyObject *const_str_plain_node;  /* [42] str = 'node' */
    PyObject *const_str_digest_b8e2a087;  /* [43] str = 'Generates a unique hardware ID (same logic as OCReview).' */
    PyObject *const_str_plain_encode;  /* [44] str = 'encode' */
    PyObject *const_str_plain_digest;  /* [45] str = 'digest' */
    PyObject *const_str_digest_8a28c577;  /* [46] str = 'Derives a stable 32-byte AES key from the HWID.' */
    PyObject *const_str_plain_time;  /* [47] str = 'time' */
    PyObject *const_str_plain__last_net_time_check;  /* [48] str = '_last_net_time_check' */
    PyObject *const_int_pos_300;  /* [49] int = 300 */
    PyObject *const_str_plain__cached_net_time_offset;  /* [50] str = '_cached_net_time_offset' */
    PyObject *const_str_digest_8ffdefbd;  /* [51] str = 'https://www.google.com' */
    PyObject *const_str_digest_9c29616a;  /* [52] str = 'https://www.cloudflare.com' */
    PyObject *const_str_digest_163a6f47;  /* [53] str = 'https://1.1.1.1' */
    PyObject *const_str_plain_requests;  /* [54] str = 'requests' */
    PyObject *const_str_plain_head;  /* [55] str = 'head' */
    PyObject *const_tuple_1_4;  /* [56] tuple = (1.5,) */
    PyObject *const_tuple_1_5;  /* [57] tuple = ('timeout',) */
    PyObject *const_str_plain_headers;  /* [58] str = 'headers' */
    PyObject *const_tuple_1_6;  /* [59] tuple = ('Date',) */
    PyObject *const_str_digest_1a9591a8;  /* [60] str = 'email.utils' */
    PyObject *const_tuple_1_7;  /* [61] tuple = ('parsedate_to_datetime',) */
    PyObject *const_str_plain_parsedate_to_datetime;  /* [62] str = 'parsedate_to_datetime' */
    PyObject *const_str_plain_timestamp;  /* [63] str = 'timestamp' */
    PyObject *const_str_plain_now;  /* [64] str = 'now' */
    PyObject *const_str_plain_cls;  /* [65] str = 'cls' */
    PyObject *const_str_digest_8f712ca5;  /* [66] str = 'Lấy giờ thực chuẩn quốc tế qua HTTP Date header (cache offs... */
    PyObject *const_str_plain__last_valid_status;  /* [67] str = '_last_valid_status' */
    PyObject *const_str_plain__last_valid_cache_time;  /* [68] str = '_last_valid_cache_time' */
    PyObject *const_float_5_0;  /* [69] float = 5.0 */
    PyObject *const_str_plain__license_lock;  /* [70] str = '_license_lock' */
    PyObject *const_str_digest_e9e2aa81;  /* [71] str = 'utf-8' */
    PyObject *const_tuple_3_1;  /* [72] tuple = (None, None, None) */
    PyObject *const_str_plain_blob;  /* [73] str = 'blob' */
    PyObject *const_tuple_4_3;  /* [74] tuple = ('slice', None, 16, None) */
    PyObject *const_tuple_4_4;  /* [75] tuple = ('slice', 16, None, None) */
    PyObject *const_str_plain__get_cipher_key;  /* [76] str = '_get_cipher_key' */
    PyObject *const_str_plain_Cipher;  /* [77] str = 'Cipher' */
    PyObject *const_str_plain_algorithms;  /* [78] str = 'algorithms' */
    PyObject *const_str_plain_AES;  /* [79] str = 'AES' */
    PyObject *const_str_plain_modes;  /* [80] str = 'modes' */
    PyObject *const_str_plain_CBC;  /* [81] str = 'CBC' */
    PyObject *const_str_plain_decryptor;  /* [82] str = 'decryptor' */
    PyObject *const_str_plain_update;  /* [83] str = 'update' */
    PyObject *const_str_plain_finalize;  /* [84] str = 'finalize' */
    PyObject *const_str_plain_pad_prim;  /* [85] str = 'pad_prim' */
    PyObject *const_str_plain_PKCS7;  /* [86] str = 'PKCS7' */
    PyObject *const_tuple_1_8;  /* [87] tuple = (128,) */
    PyObject *const_str_plain_unpadder;  /* [88] str = 'unpadder' */
    PyObject *const_str_plain_decode;  /* [89] str = 'decode' */
    PyObject *const_tuple_1_9;  /* [90] tuple = ('utf-8',) */
    PyObject *const_str_plain_json;  /* [91] str = 'json' */
    PyObject *const_str_plain_loads;  /* [92] str = 'loads' */
    PyObject *const_tuple_1_10;  /* [93] tuple = ('hwid',) */
    PyObject *const_str_plain_info;  /* [94] str = 'info' */
    PyObject *const_str_plain_exp_date;  /* [95] str = 'exp_date' */
    PyObject *const_tuple_2;  /* [96] tuple = ('expiry', 'N/A') */
    PyObject *const_tuple_2_1;  /* [97] tuple = ('last_seen_time', 0) */
    PyObject *const_int_pos_120;  /* [98] int = 120 */
    PyObject *const_tuple_1_11;  /* [99] tuple = ('[SECURITY ALERT] Phát hiện hành vi chỉnh lùi thời gian hệ ... */
    PyObject *const_str_plain_last_seen_time;  /* [100] str = 'last_seen_time' */
    PyObject *const_str_plain_save_activation;  /* [101] str = 'save_activation' */
    PyObject *const_tuple_1_12;  /* [102] tuple = ('key',) */
    PyObject *const_tuple_2_2;  /* [103] tuple = ('N/A', 'Vô thời hạn') */
    PyObject *const_str_plain_datetime;  /* [104] str = 'datetime' */
    PyObject *const_tuple_1_13;  /* [105] tuple = ('datetime',) */
    PyObject *const_str_plain_strptime;  /* [106] str = 'strptime' */
    PyObject *const_str_digest_fd4f4036;  /* [107] str = '%Y-%m-%d %H:%M:%S' */
    PyObject *const_str_digest_3dde5b0e;  /* [108] str = '%Y-%m-%d' */
    PyObject *const_str_plain__get_reliable_network_time;  /* [109] str = '_get_reliable_network_time' */
    PyObject *const_str_plain_fromtimestamp;  /* [110] str = 'fromtimestamp' */
    PyObject *const_float_30_0;  /* [111] float = 30.0 */
    PyObject *const_str_digest_3d49242a;  /* [112] str = 'Decrypts and verifies local activation file with Anti-Time-... */
    PyObject *const_str_plain_key;  /* [113] str = 'key' */
    PyObject *const_str_plain_expiry;  /* [114] str = 'expiry' */
    PyObject *const_tuple_2_3;  /* [115] tuple = ('type', 'Normal') */
    PyObject *const_str_plain_type_id;  /* [116] str = 'type_id' */
    PyObject *const_tuple_2_4;  /* [117] tuple = ('type_id', 0) */
    PyObject *const_str_digest_50641f50;  /* [118] str = 'Decrypts and returns the full activation dict or None on fa... */
    PyObject *const_str_plain_dumps;  /* [119] str = 'dumps' */
    PyObject *const_str_plain_hwid;  /* [120] str = 'hwid' */
    PyObject *const_str_plain_padder;  /* [121] str = 'padder' */
    PyObject *const_str_plain_urandom;  /* [122] str = 'urandom' */
    PyObject *const_tuple_1_14;  /* [123] tuple = (16,) */
    PyObject *const_str_plain_encryptor;  /* [124] str = 'encryptor' */
    PyObject *const_str_plain_b64encode;  /* [125] str = 'b64encode' */
    PyObject *const_str_plain_write;  /* [126] str = 'write' */
    PyObject *const_str_digest_d962850c;  /* [127] str = '[LICENSE ERROR] Save failed: ' */
    PyObject *const_str_digest_5e6dc1c0;  /* [128] str = 'Encrypts and saves activation data locally.' */
    PyObject *const_tuple_1_15;  /* [129] tuple = (32,) */
    PyObject *const_str_plain_serialization;  /* [130] str = 'serialization' */
    PyObject *const_str_plain_load_pem_public_key;  /* [131] str = 'load_pem_public_key' */
    PyObject *const_str_plain_TRIPLE_GUARD_PUB_KEY;  /* [132] str = 'TRIPLE_GUARD_PUB_KEY' */
    PyObject *const_str_plain_encrypt;  /* [133] str = 'encrypt' */
    PyObject *const_str_plain_asym_padding;  /* [134] str = 'asym_padding' */
    PyObject *const_str_plain_PKCS1v15;  /* [135] str = 'PKCS1v15' */
    PyObject *const_str_plain_license_key;  /* [136] str = 'license_key' */
    PyObject *const_str_plain_tool_name;  /* [137] str = 'tool_name' */
    PyObject *const_str_plain_encrypted_aes_key;  /* [138] str = 'encrypted_aes_key' */
    PyObject *const_dict_2;  /* [139] dict = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Ap... */
    PyObject *const_str_plain_post;  /* [140] str = 'post' */
    PyObject *const_int_pos_15;  /* [141] int = 15 */
    PyObject *const_tuple_3_2;  /* [142] tuple = ('data', 'headers', 'timeout') */
    PyObject *const_str_plain_status_code;  /* [143] str = 'status_code' */
    PyObject *const_int_pos_200;  /* [144] int = 200 */
    PyObject *const_str_digest_1b7deb54;  /* [145] str = 'Server returned status ' */
    PyObject *const_tuple_1_16;  /* [146] tuple = ('status',) */
    PyObject *const_str_plain_success;  /* [147] str = 'success' */
    PyObject *const_tuple_2_5;  /* [148] tuple = ('message', 'Unknown error') */
    PyObject *const_str_plain_iv;  /* [149] str = 'iv' */
    PyObject *const_str_plain_payload;  /* [150] str = 'payload' */
    PyObject *const_tuple_2_6;  /* [151] tuple = ('lic_type', 0) */
    PyObject *const_dict_3;  /* [152] dict = {0: 'Normal', 1: 'Premium', 2: 'Special'} */
    PyObject *const_tuple_1_17;  /* [153] tuple = ('lic_exp',) */
    PyObject *const_str_plain_server_time;  /* [154] str = 'server_time' */
    PyObject *const_tuple_1_18;  /* [155] tuple = ('server_time',) */
    PyObject *const_str_plain_Normal;  /* [156] str = 'Normal' */
    PyObject *const_str_digest_dcbb69e7;  /* [157] str = 'Lỗi kết nối máy chủ kích hoạt: ' */
    PyObject *const_str_digest_0743cb22;  /* [158] str = 'Triple Guard Protocol for PHP LicManager via cryptography p... */
    PyObject *const_str_plain_get_activation_data;  /* [159] str = 'get_activation_data' */
    PyObject *const_str_plain_fetch_from_server;  /* [160] str = 'fetch_from_server' */
    PyObject *const_str_plain_expired;  /* [161] str = 'expired' */
    PyObject *const_str_plain_invalid;  /* [162] str = 'invalid' */
    PyObject *const_str_digest_daa1bc8f;  /* [163] str = 'không tồn tại' */
    PyObject *const_str_digest_d89496d2;  /* [164] str = 'hết hạn' */
    PyObject *const_str_plain_remove;  /* [165] str = 'remove' */
    PyObject *const_str_plain_is_activated;  /* [166] str = 'is_activated' */
    PyObject *const_str_digest_dc38e8f1;  /* [167] str = 'Kiểm tra bản quyền trực tuyến với server (Triple Guard).\n ... */
    PyObject *const_str_plain_origin;  /* [168] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [169] str = 'has_location' */
    PyObject *const_str_plain_os;  /* [170] str = 'os' */
    PyObject *const_str_plain_sys;  /* [171] str = 'sys' */
    PyObject *const_str_plain_threading;  /* [172] str = 'threading' */
    PyObject *const_str_plain_Optional;  /* [173] str = 'Optional' */
    PyObject *const_str_plain_Dict;  /* [174] str = 'Dict' */
    PyObject *const_str_plain_Any;  /* [175] str = 'Any' */
    PyObject *const_str_digest_17e2d1c6;  /* [176] str = 'cryptography.hazmat.primitives.ciphers' */
    PyObject *const_tuple_3_3;  /* [177] tuple = ('Cipher', 'algorithms', 'modes') */
    PyObject *const_str_digest_3961a5ef;  /* [178] str = 'cryptography.hazmat.primitives' */
    PyObject *const_tuple_1_19;  /* [179] tuple = ('padding',) */
    PyObject *const_str_plain_padding;  /* [180] str = 'padding' */
    PyObject *const_str_digest_89c71aa6;  /* [181] str = 'cryptography.hazmat.primitives.asymmetric' */
    PyObject *const_tuple_1_20;  /* [182] tuple = ('serialization',) */
    PyObject *const_str_digest_99e67140;  /* [183] str = '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8... */
    PyObject *const_dict_2_1;  /* [184] dict = {'s': 'str', 'return': 'str'} */
    PyObject *const_str_digest_05385335;  /* [185] str = 'core.licensing' */
    PyObject *const_str_plain___qualname__;  /* [186] str = '__qualname__' */
    PyObject *const_tuple_1_21;  /* [187] tuple = ('ProxyPIA',) */
    PyObject *const_dict_1;  /* [188] dict = {'app_name': 'str'} */
    PyObject *const_str_digest_9dfe437a;  /* [189] str = 'LicenseManager.__init__' */
    PyObject *const_dict_1_1;  /* [190] dict = {'return': 'str'} */
    PyObject *const_str_digest_30606cee;  /* [191] str = 'LicenseManager.get_hwid' */
    PyObject *const_dict_1_2;  /* [192] dict = {'return': 'bytes'} */
    PyObject *const_str_digest_c8fc7920;  /* [193] str = 'LicenseManager._get_cipher_key' */
    PyObject *const_str_plain_return;  /* [194] str = 'return' */
    PyObject *const_str_digest_86e8cc55;  /* [195] str = 'LicenseManager._get_reliable_network_time' */
    PyObject *const_str_plain_Lock;  /* [196] str = 'Lock' */
    PyObject *const_dict_1_3;  /* [197] dict = {'return': 'bool'} */
    PyObject *const_str_digest_40e9e045;  /* [198] str = 'LicenseManager.is_activated' */
    PyObject *const_str_digest_b2c21070;  /* [199] str = 'LicenseManager.get_activation_data' */
    PyObject *const_str_plain_data;  /* [200] str = 'data' */
    PyObject *const_str_digest_401f3774;  /* [201] str = 'LicenseManager.save_activation' */
    PyObject *const_dict_3_1;  /* [202] dict = {'server_url': 'str', 'license_key': 'str', 'return': 'bool'... */
    PyObject *const_str_digest_60e3a6d2;  /* [203] str = 'LicenseManager.fetch_from_server' */
    PyObject *const_dict_2_2;  /* [204] dict = {'server_url': 'str', 'return': 'bool'} */
    PyObject *const_str_plain_verify_with_server;  /* [205] str = 'verify_with_server' */
    PyObject *const_str_digest_b71c75b2;  /* [206] str = 'LicenseManager.verify_with_server' */
    PyObject *const_str_digest_c09c21bf;  /* [207] str = 'core\\licensing.py' */
    PyObject *const_tuple_2_7;  /* [208] tuple = ('.0', 'b') */
    PyObject *const_str_digest_66890ff6;  /* [209] str = '<module core.licensing>' */
    PyObject *const_tuple_1_22;  /* [210] tuple = ('__class__',) */
    PyObject *const_tuple_6;  /* [211] tuple = ('self', 'app_name', 'base_dir', 'legacy_paths', 'leg', 'shu... */
    PyObject *const_tuple_1_23;  /* [212] tuple = ('self',) */
    PyObject *const_tuple_9;  /* [213] tuple = ('cls', 'now', 'time_servers', 'url', 'res', 'date_str', 'pa... */
    PyObject *const_tuple_2_8;  /* [214] tuple = ('s', 'decoded') */
    PyObject *const_tuple_24;  /* [215] tuple = ('self', 'server_url', 'license_key', 'hwid', 'aes_key_raw',... */
    PyObject *const_tuple_13;  /* [216] tuple = ('self', 'f', 'blob', 'iv', 'encrypted_data', 'key', 'cipher... */
    PyObject *const_tuple_9_1;  /* [217] tuple = ('self', 'no_window', 'res_uuid', 'uuid_out', 'res_cpu', 'cp... */
    PyObject *const_tuple_21;  /* [218] tuple = ('self', 'now_timestamp', 'f', 'content', 'blob', 'iv', 'enc... */
    PyObject *const_tuple_14;  /* [219] tuple = ('self', 'license_key', 'data', 'raw_data', 'padder', 'padde... */
    PyObject *const_tuple_5;  /* [220] tuple = ('self', 'server_url', 'act_data', 'license_key', 'success') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.licensing"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__config;   /* 'config' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__stdout;   /* 'stdout' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__headers;   /* 'headers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__headers;   /* 'headers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__parsedate_to_datetime;   /* 'parsedate_to_datetime' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__loads;   /* 'loads' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__save_activation;   /* 'save_activation' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__datetime;   /* 'datetime' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__expiry;   /* 'expiry' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__status_code;   /* 'status_code' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__success;   /* 'success' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__server_time;   /* 'server_time' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__server_time;   /* 'server_time' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__Any;   /* 'Any' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__padding;   /* 'padding' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__padding;   /* 'padding' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_16____qualname__;   /* '__qualname__' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_17__verify_with_server;   /* 'verify_with_server' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_18__licensing$gt$;   /* 'licensing>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_19__licensing$gt$;   /* 'licensing>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_20__licensing$gt$;   /* 'licensing>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_21__licensing$gt$;   /* 'licensing>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def config(exist_ok)
 *  qualname: license.dat   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$config(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def stdout(capture_output, text, creationflags)
 *  qualname: stdout   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$stdout(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def headers(timeout)
 *  qualname: email.utils   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$headers(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def headers(Date)
 *  qualname: email.utils   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$headers(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def parsedate_to_datetime(parsedate_to_datetime)
 *  qualname: email.utils   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$parsedate_to_datetime(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def loads(hwid)
 *  qualname: loads   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$loads(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def save_activation(key)
 *  qualname: save_activation   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$save_activation(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def datetime(datetime)
 *  qualname: datetime   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$datetime(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def expiry(type, Normal)
 *  qualname: expiry   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$expiry(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def status_code(data, headers, timeout)
 *  qualname: status_code   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$status_code(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def success(status)
 *  qualname: success   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$success(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def server_time(lic_exp)
 *  qualname: server_time   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$server_time(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def server_time(server_time)
 *  qualname: server_time   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$server_time(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def Any(Cipher, algorithms, modes)
 *  qualname: cryptography.hazmat.primitives.ciphers   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$Any(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def padding(padding)
 *  qualname: cryptography.hazmat.primitives   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$padding(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def padding(serialization)
 *  qualname: cryptography.hazmat.primitives.asymmetric   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$padding(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def __qualname__(ProxyPIA)
 *  qualname: core.licensing   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$__qualname__(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def verify_with_server(.0, b)
 *  qualname: <module core.licensing>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$verify_with_server(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def licensing>(__class__)
 *  qualname: <module core.licensing>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def licensing>(self, app_name, base_dir, legacy_paths, leg, shutil)
 *  qualname: <module core.licensing>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def licensing>(self)
 *  qualname: <module core.licensing>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def licensing>(cls, now, time_servers, url, res, date_str, parsedate_to_datetime, dt, server_ts)
 *  qualname: <module core.licensing>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$licensing$config(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def config(exist_ok): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$stdout(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def stdout(capture_output, text, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$headers(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def headers(timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$headers(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def headers(Date): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$parsedate_to_datetime(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def parsedate_to_datetime(parsedate_to_datetime): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$loads(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def loads(hwid): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$save_activation(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def save_activation(key): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$datetime(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def datetime(datetime): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$expiry(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def expiry(type, Normal): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$status_code(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def status_code(data, headers, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$success(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def success(status): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$server_time(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def server_time(lic_exp): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$server_time(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def server_time(server_time): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$Any(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def Any(Cipher, algorithms, modes): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$padding(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def padding(padding): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$padding(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def padding(serialization): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$__qualname__(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def __qualname__(ProxyPIA): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$verify_with_server(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def verify_with_server(.0, b): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def licensing>(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def licensing>(self, app_name, base_dir, legacy_paths, leg, shutil): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def licensing>(self): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$licensing$licensing$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def licensing>(cls, now, time_servers, url, res, date_str, parsedate_to_datetime, dt, server_ts): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$licensing(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$licensing = module;
    moduledict_core$licensing = MODULE_DICT(module_core$licensing);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141998650
     *
     * Recovered imports (detected from module constants): */
    /*   import license.dat */
    /*   import email.utils */
    /*   import cryptography.hazmat.primitives.ciphers */
    /*   import cryptography.hazmat.primitives */
    /*   import cryptography.hazmat.primitives.asymmetric */
    /*   import core.licensing */
    /*   import LicenseManager.__init__ */
    /*   import LicenseManager.get_hwid */
    /*   import LicenseManager._get_cipher_key */
    /*   import LicenseManager._get_reliable_network_time */
    /*   import LicenseManager.is_activated */
    /*   import LicenseManager.get_activation_data */
    /*   import LicenseManager.save_activation */
    /*   import LicenseManager.fetch_from_server */
    /*   import LicenseManager.verify_with_server */

    return module;
}

