/* Reconstructed C source for Python module 'core.openvpn_mgr'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$openvpn_mgr @ 0x1419CE1F0
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$openvpn_mgr;
PyDictObject *moduledict_core$openvpn_mgr;

/* Module constants: 427 entries recovered from blob chunk 'core.openvpn_mgr'. */
static struct ModuleConstants {
    PyObject *const_tuple_1;  /* [0] tuple = ('.',) */
    PyObject *const_str_plain__dns_cache;  /* [1] str = '_dns_cache' */
    PyObject *const_str_plain_socket;  /* [2] str = 'socket' */
    PyObject *const_str_plain_gethostbyname;  /* [3] str = 'gethostbyname' */
    PyObject *const_str_digest_432ecc5b;  /* [4] str = 'Phân giải nhanh hostname sang IP số có cache tránh chậm mạn... */
    PyObject *const_str_plain_isdigit;  /* [5] str = 'isdigit' */
    PyObject *const_int_pos_255;  /* [6] int = 255 */
    PyObject *const_str_digest_a49c8f51;  /* [7] str = '<genexpr>' */
    PyObject *const_str_digest_b3829348;  /* [8] str = '_fast_resolve_ip.<locals>.<genexpr>' */
    PyObject *const_str_plain_Path;  /* [9] str = 'Path' */
    PyObject *const_str_plain_resolve;  /* [10] str = 'resolve' */
    PyObject *const_str_plain_configs;  /* [11] str = 'configs' */
    PyObject *const_str_plain_openvpn;  /* [12] str = 'openvpn' */
    PyObject *const_str_plain_config_dir;  /* [13] str = 'config_dir' */
    PyObject *const_str_plain_mkdir;  /* [14] str = 'mkdir' */
    PyObject *const_tuple_2;  /* [15] tuple = (True, True) */
    PyObject *const_tuple_2_1;  /* [16] tuple = ('parents', 'exist_ok') */
    PyObject *const_str_plain_binary_dir;  /* [17] str = 'binary_dir' */
    PyObject *const_str_plain_qemu_engine;  /* [18] str = 'qemu_engine' */
    PyObject *const_str_plain_qemu_dir;  /* [19] str = 'qemu_dir' */
    PyObject *const_str_plain_bin;  /* [20] str = 'bin' */
    PyObject *const_str_digest_40d3db0a;  /* [21] str = 'qemu-system-x86_64.exe' */
    PyObject *const_str_plain_qemu_bin;  /* [22] str = 'qemu_bin' */
    PyObject *const_str_plain__vm_process;  /* [23] str = '_vm_process' */
    PyObject *const_str_plain__active_ports;  /* [24] str = '_active_ports' */
    PyObject *const_str_plain__windows_listeners;  /* [25] str = '_windows_listeners' */
    PyObject *const_str_plain_threading;  /* [26] str = 'threading' */
    PyObject *const_str_plain_Lock;  /* [27] str = 'Lock' */
    PyObject *const_str_plain__listener_lock;  /* [28] str = '_listener_lock' */
    PyObject *const_str_digest_44629a61;  /* [29] str = 'zlib1.dll' */
    PyObject *const_str_digest_9e870b94;  /* [30] str = 'qemu_engine.zip' */
    PyObject *const_str_digest_fa223edc;  /* [31] str = 'qemu_engine_clean_backup.zip' */
    PyObject *const_str_plain_st_size;  /* [32] str = 'st_size' */
    PyObject *const_int_digest_2e282594;  /* [33] int = 10485760 */
    PyObject *const_str_plain_zipfile;  /* [34] str = 'zipfile' */
    PyObject *const_str_plain_logger;  /* [35] str = 'logger' */
    PyObject *const_str_plain_info;  /* [36] str = 'info' */
    PyObject *const_str_digest_567e92ee;  /* [37] str = '📦 [MicroVM Engine] Đang tự động giải nén máy ảo lần đầu từ ... */
    PyObject *const_str_digest_2f43b42f;  /* [38] str = '...' */
    PyObject *const_str_plain_ZipFile;  /* [39] str = 'ZipFile' */
    PyObject *const_str_plain_extractall;  /* [40] str = 'extractall' */
    PyObject *const_tuple_3;  /* [41] tuple = (None, None, None) */
    PyObject *const_tuple_1_1;  /* [42] tuple = ('✅ [MicroVM Engine] Tự động giải nén máy ảo hoàn tất!',) */
    PyObject *const_str_plain_error;  /* [43] str = 'error' */
    PyObject *const_str_digest_5d5dbab2;  /* [44] str = '❌ [MicroVM Engine] Lỗi giải nén ' */
    PyObject *const_str_digest_e2654927;  /* [45] str = ': ' */
    PyObject *const_str_digest_fdba4d64;  /* [46] str = 'Tự động giải nén qemu_engine từ file zip backup nếu thư mục... */
    PyObject *const_str_plain__unpack_engine_if_needed;  /* [47] str = '_unpack_engine_if_needed' */
    PyObject *const_str_digest_39250b78;  /* [48] str = 'Kiểm tra sự tồn tại của QEMU MicroVM binary' */
    PyObject *const_str_digest_3f9df933;  /* [49] str = '-L' */
    PyObject *const_str_digest_eb369c00;  /* [50] str = '-accel' */
    PyObject *const_str_digest_43482f0b;  /* [51] str = 'whpx,kernel-irqchip=off' */
    PyObject *const_str_digest_0af4ea0c;  /* [52] str = '-nographic' */
    PyObject *const_str_digest_1ece2cce;  /* [53] str = '-nodefaults' */
    PyObject *const_str_digest_055afbf6;  /* [54] str = '-serial' */
    PyObject *const_str_plain_none;  /* [55] str = 'none' */
    PyObject *const_str_digest_098b3a3b;  /* [56] str = '-monitor' */
    PyObject *const_str_digest_67dd1c0d;  /* [57] str = '-m' */
    PyObject *const_str_digest_6783e761;  /* [58] str = '64M' */
    PyObject *const_str_plain_subprocess;  /* [59] str = 'subprocess' */
    PyObject *const_str_plain_CREATE_NO_WINDOW;  /* [60] str = 'CREATE_NO_WINDOW' */
    PyObject *const_str_plain_Popen;  /* [61] str = 'Popen' */
    PyObject *const_str_plain_PIPE;  /* [62] str = 'PIPE' */
    PyObject *const_tuple_4;  /* [63] tuple = ('stdout', 'stderr', 'text', 'creationflags') */
    PyObject *const_str_plain_time;  /* [64] str = 'time' */
    PyObject *const_str_plain_sleep;  /* [65] str = 'sleep' */
    PyObject *const_tuple_1_2;  /* [66] tuple = (0.5,) */
    PyObject *const_str_plain_poll;  /* [67] str = 'poll' */
    PyObject *const_str_plain_kill;  /* [68] str = 'kill' */
    PyObject *const_str_plain_communicate;  /* [69] str = 'communicate' */
    PyObject *const_str_plain_operational;  /* [70] str = 'operational' */
    PyObject *const_str_digest_fbf3537b;  /* [71] str = 'Kiểm tra Windows Hypervisor Platform (WHPX) có khả dụng và ... */
    PyObject *const_str_plain_requests;  /* [72] str = 'requests' */
    PyObject *const_str_plain_AGENT_API_URL;  /* [73] str = 'AGENT_API_URL' */
    PyObject *const_str_digest_95fcbda6;  /* [74] str = '/api/health' */
    PyObject *const_tuple_1_3;  /* [75] tuple = ('timeout',) */
    PyObject *const_str_plain_status_code;  /* [76] str = 'status_code' */
    PyObject *const_int_pos_200;  /* [77] int = 200 */
    PyObject *const_str_plain_json;  /* [78] str = 'json' */
    PyObject *const_tuple_1_4;  /* [79] tuple = ('status',) */
    PyObject *const_str_plain_ready;  /* [80] str = 'ready' */
    PyObject *const_str_digest_5a8e39cd;  /* [81] str = 'Kiểm tra Agent Controller bên trong MicroVM đã sẵn sàng chư... */
    PyObject *const_str_plain__is_agent_ready;  /* [82] str = '_is_agent_ready' */
    PyObject *const_tuple_1_5;  /* [83] tuple = (2.0,) */
    PyObject *const_str_plain_start_wait;  /* [84] str = 'start_wait' */
    PyObject *const_int_pos_10;  /* [85] int = 10 */
    PyObject *const_str_plain_self;  /* [86] str = 'self' */
    PyObject *const_tuple_1_6;  /* [87] tuple = (3.0,) */
    PyObject *const_tuple_1_7;  /* [88] tuple = (1.0,) */
    PyObject *const_str_plain_psutil;  /* [89] str = 'psutil' */
    PyObject *const_str_plain_process_iter;  /* [90] str = 'process_iter' */
    PyObject *const_str_plain_pid;  /* [91] str = 'pid' */
    PyObject *const_str_plain_qemu;  /* [92] str = 'qemu' */
    PyObject *const_tuple_1_8;  /* [93] tuple = ('name',) */
    PyObject *const_str_plain_run;  /* [94] str = 'run' */
    PyObject *const_str_plain_DEVNULL;  /* [95] str = 'DEVNULL' */
    PyObject *const_tuple_1_9;  /* [96] tuple = (['taskkill', '/F', '/IM', 'qemu-system-x86_64.exe'],) */
    PyObject *const_tuple_2_2;  /* [97] tuple = ('stdout', 'stderr') */
    PyObject *const_str_digest_53283d72;  /* [98] str = 'hostfwd=tcp::28888-:28888' */
    PyObject *const_str_digest_39a02b3c;  /* [99] str = 'hostfwd=tcp::28889-:28889' */
    PyObject *const_str_digest_71ad5c04;  /* [100] str = 'user,id=net0,' */
    PyObject *const_str_digest_c0cb5f0f;  /* [101] str = ',' */
    PyObject *const_str_plain_cpu_count;  /* [102] str = 'cpu_count' */
    PyObject *const_int_pos_2;  /* [103] int = 2 */
    PyObject *const_str_plain_virtual_memory;  /* [104] str = 'virtual_memory' */
    PyObject *const_str_plain_total;  /* [105] str = 'total' */
    PyObject *const_int_digest_952eb029;  /* [106] int = 1073741824 */
    PyObject *const_int_pos_14;  /* [107] int = 14 */
    PyObject *const_str_digest_966c5dd0;  /* [108] str = '1024M' */
    PyObject *const_str_digest_d40dea6b;  /* [109] str = '512M' */
    PyObject *const_str_plain__is_whpx_supported;  /* [110] str = '_is_whpx_supported' */
    PyObject *const_str_plain_tcg;  /* [111] str = 'tcg' */
    PyObject *const_str_digest_f56dfc24;  /* [112] str = '⚡ [MicroVM Engine] Cấu hình MicroVM: Accel=' */
    PyObject *const_str_digest_764a7b7b;  /* [113] str = ', vCPU=' */
    PyObject *const_str_digest_d8f055ce;  /* [114] str = ', RAM=' */
    PyObject *const_str_digest_cc62020f;  /* [115] str = '-smp' */
    PyObject *const_str_digest_112f0256;  /* [116] str = '-drive' */
    PyObject *const_str_digest_92bd5f93;  /* [117] str = 'file=' */
    PyObject *const_str_digest_36e1c0a4;  /* [118] str = 'alpine_tiny.qcow2' */
    PyObject *const_str_digest_2d194833;  /* [119] str = ',format=qcow2,if=virtio' */
    PyObject *const_str_digest_a0e4aec0;  /* [120] str = 'alpine_root_2g.raw' */
    PyObject *const_str_digest_e5c8d2a0;  /* [121] str = ',format=raw,if=virtio' */
    PyObject *const_str_digest_74046056;  /* [122] str = 'vpn_data.tar' */
    PyObject *const_str_digest_7d413563;  /* [123] str = '-netdev' */
    PyObject *const_str_digest_c0b4b0b6;  /* [124] str = '-device' */
    PyObject *const_str_digest_6331732c;  /* [125] str = 'virtio-net-pci,netdev=net0,romfile=' */
    PyObject *const_str_digest_d2d7de69;  /* [126] str = 'qemu_stderr.log' */
    PyObject *const_str_digest_e9e2aa81;  /* [127] str = 'utf-8' */
    PyObject *const_str_plain_ignore;  /* [128] str = 'ignore' */
    PyObject *const_str_plain__vm_stderr_file;  /* [129] str = '_vm_stderr_file' */
    PyObject *const_tuple_4_1;  /* [130] tuple = ('cwd', 'stdout', 'stderr', 'creationflags') */
    PyObject *const_str_digest_b81c0637;  /* [131] str = '[!] Không thể khởi động QEMU MicroVM: ' */
    PyObject *const_str_plain_start_time;  /* [132] str = 'start_time' */
    PyObject *const_str_digest_f4c6e06b;  /* [133] str = '[+] MicroVM Engine đã sẵn sàng sau ' */
    PyObject *const_str_digest_530490af;  /* [134] str = 's!' */
    PyObject *const_str_plain_strip;  /* [135] str = 'strip' */
    PyObject *const_str_digest_d372372a;  /* [136] str = '[!] QEMU MicroVM process đã thoát bất thường (code ' */
    PyObject *const_str_digest_df21692a;  /* [137] str = '). Chi tiết: ' */
    PyObject *const_str_digest_382b0f51;  /* [138] str = 'N/A' */
    PyObject *const_str_digest_fdf9a91a;  /* [139] str = '[!] Quá thời gian chờ MicroVM khởi động (' */
    PyObject *const_str_digest_6290df4e;  /* [140] str = 's)' */
    PyObject *const_str_digest_39ef7ffc;  /* [141] str = '\n        Đảm bảo MicroVM Engine đã khởi động hoàn chỉnh tr... */
    PyObject *const_str_plain_port_;  /* [142] str = 'port_' */
    PyObject *const_str_digest_0775a620;  /* [143] str = 'auth.txt' */
    PyObject *const_str_plain_write;  /* [144] str = 'write' */
    PyObject *const_str_digest_68b329da;  /* [145] str = '\n' */
    PyObject *const_str_digest_1ad723ce;  /* [146] str = 'config.ovpn' */
    PyObject *const_str_plain_data;  /* [147] str = 'data' */
    PyObject *const_str_plain_resources;  /* [148] str = 'resources' */
    PyObject *const_str_plain_pia_ovpn;  /* [149] str = 'pia_ovpn' */
    PyObject *const_str_plain_glob;  /* [150] str = 'glob' */
    PyObject *const_tuple_1_10;  /* [151] tuple = ('*.ovpn',) */
    PyObject *const_str_plain_replace;  /* [152] str = 'replace' */
    PyObject *const_tuple_2_3;  /* [153] tuple = (' ', '_') */
    PyObject *const_str_plain_stem;  /* [154] str = 'stem' */
    PyObject *const_str_plain_cands;  /* [155] str = 'cands' */
    PyObject *const_str_plain_splitlines;  /* [156] str = 'splitlines' */
    PyObject *const_str_plain_startswith;  /* [157] str = 'startswith' */
    PyObject *const_tuple_1_11;  /* [158] tuple = ('remote ',) */
    PyObject *const_tuple_1_12;  /* [159] tuple = ('proto ',) */
    PyObject *const_tuple_1_13;  /* [160] tuple = ('dev ',) */
    PyObject *const_tuple_1_14;  /* [161] tuple = ('dev-type ',) */
    PyObject *const_tuple_1_15;  /* [162] tuple = ('dev-node ',) */
    PyObject *const_tuple_1_16;  /* [163] tuple = ('auth-user-pass',) */
    PyObject *const_tuple_1_17;  /* [164] tuple = ('windows-driver',) */
    PyObject *const_tuple_1_18;  /* [165] tuple = ('route-nopull',) */
    PyObject *const_tuple_1_19;  /* [166] tuple = ('redirect-gateway',) */
    PyObject *const_str_plain_cleaned_lines;  /* [167] str = 'cleaned_lines' */
    PyObject *const_int_pos_502;  /* [168] int = 502 */
    PyObject *const_str_plain_tcp;  /* [169] str = 'tcp' */
    PyObject *const_str_plain_client;  /* [170] str = 'client' */
    PyObject *const_str_digest_628e332b;  /* [171] str = 'dev tun' */
    PyObject *const_str_digest_f7cedf1e;  /* [172] str = 'proto ' */
    PyObject *const_str_digest_b3a51d9a;  /* [173] str = 'remote ' */
    PyObject *const_str_digest_7215ee9c;  /* [174] str = ' ' */
    PyObject *const_str_digest_ff0ed4ce;  /* [175] str = 'redirect-gateway def1' */
    PyObject *const_str_digest_66b5689c;  /* [176] str = 'resolv-retry infinite' */
    PyObject *const_str_plain_nobind;  /* [177] str = 'nobind' */
    PyObject *const_str_digest_6afd67d0;  /* [178] str = 'persist-key' */
    PyObject *const_str_digest_5f9f68a8;  /* [179] str = 'persist-tun' */
    PyObject *const_str_digest_ad8c3d11;  /* [180] str = 'remote-cert-tls server' */
    PyObject *const_str_digest_1781b5f9;  /* [181] str = 'verb 1' */
    PyObject *const_str_digest_909e2a1a;  /* [182] str = 'mute 20' */
    PyObject *const_str_digest_2165d9c2;  /* [183] str = 'fast-io' */
    PyObject *const_str_digest_1cdd7619;  /* [184] str = 'reneg-sec 0' */
    PyObject *const_str_digest_ae3b1fb5;  /* [185] str = 'data-ciphers AES-256-GCM:AES-128-GCM:AES-128-CBC:AES-256-CB... */
    PyObject *const_str_digest_574ddc6a;  /* [186] str = 'data-ciphers-fallback AES-128-CBC' */
    PyObject *const_str_digest_4d1073b1;  /* [187] str = '\n# --- Provider Certs ---' */
    PyObject *const_str_digest_fd7a534c;  /* [188] str = '\n# --- PIA Default Root CA & Security ---\ncipher aes-128-... */
    PyObject *const_str_digest_1073262f;  /* [189] str = '\n        Sinh file cấu hình .ovpn cho cổng proxy với giao ... */
    PyObject *const_int_pos_10000;  /* [190] int = 10000 */
    PyObject *const_int_pos_11200;  /* [191] int = 11200 */
    PyObject *const_str_plain_AF_INET;  /* [192] str = 'AF_INET' */
    PyObject *const_str_plain_SOCK_STREAM;  /* [193] str = 'SOCK_STREAM' */
    PyObject *const_str_plain_settimeout;  /* [194] str = 'settimeout' */
    PyObject *const_str_plain_connect;  /* [195] str = 'connect' */
    PyObject *const_tuple_1_20;  /* [196] tuple = (('127.0.0.1', 44445),) */
    PyObject *const_str_plain_sendall;  /* [197] str = 'sendall' */
    PyObject *const_str_digest_447bfd2e;  /* [198] str = 'hostfwd_add net0 tcp::' */
    PyObject *const_str_digest_835bc09c;  /* [199] str = '-:' */
    PyObject *const_tuple_1_21;  /* [200] tuple = (0.05,) */
    PyObject *const_str_plain_recv;  /* [201] str = 'recv' */
    PyObject *const_tuple_1_22;  /* [202] tuple = (1024,) */
    PyObject *const_str_digest_3663ec4a;  /* [203] str = '[+] Đã thêm dynamic hostfwd cho port ' */
    PyObject *const_str_plain_debug;  /* [204] str = 'debug' */
    PyObject *const_str_digest_0ee0ffc6;  /* [205] str = 'Dynamic hostfwd port ' */
    PyObject *const_str_digest_0372b7aa;  /* [206] str = 'Đảm bảo cổng đã được forward qua QEMU Monitor nếu nằm ngoài... */
    PyObject *const_str_plain_ensure_engine_ready;  /* [207] str = 'ensure_engine_ready' */
    PyObject *const_str_plain__ensure_hostfwd;  /* [208] str = '_ensure_hostfwd' */
    PyObject *const_str_plain_raw_ovpn;  /* [209] str = 'raw_ovpn' */
    PyObject *const_tuple_1_23;  /* [210] tuple = ('remote-cert-tls',) */
    PyObject *const_str_digest_c54e7837;  /* [211] str = '1198' */
    PyObject *const_int_pos_3;  /* [212] int = 3 */
    PyObject *const_str_plain__fast_resolve_ip;  /* [213] str = '_fast_resolve_ip' */
    PyObject *const_str_plain_ovpn_lines;  /* [214] str = 'ovpn_lines' */
    PyObject *const_tuple_1_24;  /* [215] tuple = ('**\/auth.txt',) */
    PyObject *const_str_plain_auth_file;  /* [216] str = 'auth_file' */
    PyObject *const_str_plain_port;  /* [217] str = 'port' */
    PyObject *const_str_plain_ovpn_content;  /* [218] str = 'ovpn_content' */
    PyObject *const_str_plain_auth_content;  /* [219] str = 'auth_content' */
    PyObject *const_str_plain_endpoint;  /* [220] str = 'endpoint' */
    PyObject *const_tuple_4_2;  /* [221] tuple = ('range', 0, 3, 1) */
    PyObject *const_str_plain_post;  /* [222] str = 'post' */
    PyObject *const_str_digest_09f22883;  /* [223] str = '/api/port/add' */
    PyObject *const_str_plain_payload;  /* [224] str = 'payload' */
    PyObject *const_int_pos_45;  /* [225] int = 45 */
    PyObject *const_tuple_2_4;  /* [226] tuple = ('json', 'timeout') */
    PyObject *const_tuple_1_25;  /* [227] tuple = ('success',) */
    PyObject *const_str_plain__start_windows_listener;  /* [228] str = '_start_windows_listener' */
    PyObject *const_str_digest_f15ab1db;  /* [229] str = '[+] Đã kết nối OpenVPN cho port ' */
    PyObject *const_str_digest_295ab452;  /* [230] str = '[!] Lỗi khởi chạy port ' */
    PyObject *const_str_digest_d25b0837;  /* [231] str = ' (attempt ' */
    PyObject *const_str_digest_7466d79d;  /* [232] str = '): ' */
    PyObject *const_str_plain_text;  /* [233] str = 'text' */
    PyObject *const_float_1_5;  /* [234] float = 1.5 */
    PyObject *const_str_plain_warning;  /* [235] str = 'warning' */
    PyObject *const_str_digest_15596c8d;  /* [236] str = '⚠️ Port ' */
    PyObject *const_str_digest_c6c7acc3;  /* [237] str = ' kết nối chậm (' */
    PyObject *const_str_digest_2283ffd8;  /* [238] str = '), tự động thử lại lần ' */
    PyObject *const_str_digest_77c77338;  /* [239] str = ' sau ' */
    PyObject *const_str_digest_7704a156;  /* [240] str = '.1f' */
    PyObject *const_str_digest_5d404e31;  /* [241] str = 's...' */
    PyObject *const_str_digest_f2875726;  /* [242] str = '[!] Lỗi kết nối port ' */
    PyObject *const_str_digest_caae4051;  /* [243] str = ' sau 3 lần thử: ' */
    PyObject *const_str_digest_490ad3af;  /* [244] str = '[!] Exception start_openvpn_instance port ' */
    PyObject *const_str_digest_96923085;  /* [245] str = '\n        Khởi chạy OpenVPN cho 1 port cụ thể thông qua Mic... */
    PyObject *const_str_plain_Event;  /* [246] str = 'Event' */
    PyObject *const_str_plain_listener_worker;  /* [247] str = 'listener_worker' */
    PyObject *const_str_digest_e76cd98f;  /* [248] str = 'OpenVPNManager._start_windows_listener.<locals>.listener_wo... */
    PyObject *const_str_plain_Thread;  /* [249] str = 'Thread' */
    PyObject *const_tuple_2_5;  /* [250] tuple = ('target', 'daemon') */
    PyObject *const_str_plain_start;  /* [251] str = 'start' */
    PyObject *const_str_digest_e7098b49;  /* [252] str = 'Lắng nghe cổng trên Windows và chuyển tiếp qua Multiplexer ... */
    PyObject *const_str_plain_setsockopt;  /* [253] str = 'setsockopt' */
    PyObject *const_str_plain_SOL_SOCKET;  /* [254] str = 'SOL_SOCKET' */
    PyObject *const_str_plain_SO_REUSEADDR;  /* [255] str = 'SO_REUSEADDR' */
    PyObject *const_str_plain_bind;  /* [256] str = 'bind' */
    PyObject *const_str_digest_f1f17934;  /* [257] str = '0.0.0.0' */
    PyObject *const_str_plain_listen;  /* [258] str = 'listen' */
    PyObject *const_tuple_1_26;  /* [259] tuple = (128,) */
    PyObject *const_str_plain_stop_event;  /* [260] str = 'stop_event' */
    PyObject *const_str_plain_is_set;  /* [261] str = 'is_set' */
    PyObject *const_str_plain_srv;  /* [262] str = 'srv' */
    PyObject *const_str_plain_accept;  /* [263] str = 'accept' */
    PyObject *const_str_plain_timeout;  /* [264] str = 'timeout' */
    PyObject *const_str_plain_forward_conn;  /* [265] str = 'forward_conn' */
    PyObject *const_str_digest_dce74f53;  /* [266] str = 'OpenVPNManager._start_windows_listener.<locals>.listener_wo... */
    PyObject *const_tuple_3_1;  /* [267] tuple = ('target', 'args', 'daemon') */
    PyObject *const_str_digest_fe682dad;  /* [268] str = 'Windows listener error port ' */
    PyObject *const_tuple_1_27;  /* [269] tuple = (10.0,) */
    PyObject *const_tuple_1_28;  /* [270] tuple = (('127.0.0.1', 28889),) */
    PyObject *const_str_plain_struct;  /* [271] str = 'struct' */
    PyObject *const_str_plain_pack;  /* [272] str = 'pack' */
    PyObject *const_str_digest_1cd30b93;  /* [273] str = '>H' */
    PyObject *const_tuple_1_29;  /* [274] tuple = (None,) */
    PyObject *const_str_plain_pipe;  /* [275] str = 'pipe' */
    PyObject *const_str_digest_c96835cf;  /* [276] str = 'OpenVPNManager._start_windows_listener.<locals>.listener_wo... */
    PyObject *const_str_plain_mux;  /* [277] str = 'mux' */
    PyObject *const_str_plain_s_in;  /* [278] str = 's_in' */
    PyObject *const_tuple_1_30;  /* [279] tuple = (16384,) */
    PyObject *const_str_plain_s_out;  /* [280] str = 's_out' */
    PyObject *const_str_plain_shutdown;  /* [281] str = 'shutdown' */
    PyObject *const_str_plain_SHUT_RDWR;  /* [282] str = 'SHUT_RDWR' */
    PyObject *const_str_plain_set;  /* [283] str = 'set' */
    PyObject *const_str_plain_pop;  /* [284] str = 'pop' */
    PyObject *const_str_plain_items;  /* [285] str = 'items' */
    PyObject *const_str_plain_clear;  /* [286] str = 'clear' */
    PyObject *const_str_plain__stop_windows_listener;  /* [287] str = '_stop_windows_listener' */
    PyObject *const_str_digest_e0cf46e1;  /* [288] str = '/api/port/delete' */
    PyObject *const_int_pos_5;  /* [289] int = 5 */
    PyObject *const_str_digest_b866a089;  /* [290] str = 'Stop API call error port ' */
    PyObject *const_str_plain_shutil;  /* [291] str = 'shutil' */
    PyObject *const_str_plain_rmtree;  /* [292] str = 'rmtree' */
    PyObject *const_tuple_1_31;  /* [293] tuple = (True,) */
    PyObject *const_tuple_1_32;  /* [294] tuple = ('ignore_errors',) */
    PyObject *const_str_digest_1432637b;  /* [295] str = '\n        Dừng OpenVPN của 1 port và dọn sạch toàn bộ rác t... */
    PyObject *const_str_digest_a45bd416;  /* [296] str = 'concurrent.futures' */
    PyObject *const_str_plain_futures;  /* [297] str = 'futures' */
    PyObject *const_str_plain_ThreadPoolExecutor;  /* [298] str = 'ThreadPoolExecutor' */
    PyObject *const_tuple_1_33;  /* [299] tuple = (12,) */
    PyObject *const_tuple_1_34;  /* [300] tuple = ('max_workers',) */
    PyObject *const_str_plain_map;  /* [301] str = 'map' */
    PyObject *const_str_digest_11659e6b;  /* [302] str = '<lambda>' */
    PyObject *const_str_digest_8b38683e;  /* [303] str = 'OpenVPNManager.stop_many_openvpn_instances.<locals>.<lambda... */
    PyObject *const_str_digest_05213da9;  /* [304] str = 'Dừng song song nhiều cổng OpenVPN trong MicroVM siêu tốc' */
    PyObject *const_str_plain_stop_openvpn_instance;  /* [305] str = 'stop_openvpn_instance' */
    PyObject *const_str_plain_cleanup_files;  /* [306] str = 'cleanup_files' */
    PyObject *const_tuple_1_35;  /* [307] tuple = ('cleanup_files',) */
    PyObject *const_str_digest_981486ce;  /* [308] str = '/api/port/rotate' */
    PyObject *const_int_pos_20;  /* [309] int = 20 */
    PyObject *const_str_digest_6e2a97e4;  /* [310] str = '[+] Đã xoay IP thành công cho port ' */
    PyObject *const_str_digest_a89209f5;  /* [311] str = '[!] Lỗi xoay IP port ' */
    PyObject *const_str_digest_d0df6333;  /* [312] str = '\n        Xoay đổi Endpoint lấy IP mới ngay lập tức cho 1 c... */
    PyObject *const_str_plain_get_all_status;  /* [313] str = 'get_all_status' */
    PyObject *const_tuple_1_36;  /* [314] tuple = ('port',) */
    PyObject *const_str_digest_bd7577e9;  /* [315] str = 'Kiểm tra cổng OpenVPN có đang chạy trong MicroVM không' */
    PyObject *const_str_digest_e26a6772;  /* [316] str = '/api/port/status' */
    PyObject *const_tuple_1_37;  /* [317] tuple = (3,) */
    PyObject *const_str_plain_ports;  /* [318] str = 'ports' */
    PyObject *const_str_digest_a97f1afe;  /* [319] str = 'Lấy danh sách tất cả các cổng đang hoạt động từ MicroVM Age... */
    PyObject *const_str_plain__stop_all_windows_listeners;  /* [320] str = '_stop_all_windows_listeners' */
    PyObject *const_str_digest_2ef942c0;  /* [321] str = '/api/port/clean_all' */
    PyObject *const_tuple_1_38;  /* [322] tuple = (5,) */
    PyObject *const_str_digest_ec4bdb51;  /* [323] str = 'Xóa sạch 100% tất cả container, namespace, log và tunnels t... */
    PyObject *const_str_plain_clean_all_containers;  /* [324] str = 'clean_all_containers' */
    PyObject *const_str_plain_terminate;  /* [325] str = 'terminate' */
    PyObject *const_str_plain_wait;  /* [326] str = 'wait' */
    PyObject *const_tuple_1_39;  /* [327] tuple = (2,) */
    PyObject *const_str_digest_43f95a39;  /* [328] str = 'Dừng tất cả các proxy và tắt MicroVM khi đóng ứng dụng' */
    PyObject *const_str_digest_73b95e88;  /* [329] str = '\nOpenVPN Manager for OCProxy - Powered by Portable Zero-De... */
    PyObject *const_str_plain_origin;  /* [330] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [331] str = 'has_location' */
    PyObject *const_str_plain_os;  /* [332] str = 'os' */
    PyObject *const_str_plain_sys;  /* [333] str = 'sys' */
    PyObject *const_str_plain_logging;  /* [334] str = 'logging' */
    PyObject *const_str_plain_pathlib;  /* [335] str = 'pathlib' */
    PyObject *const_tuple_1_40;  /* [336] tuple = ('Path',) */
    PyObject *const_str_plain_Dict;  /* [337] str = 'Dict' */
    PyObject *const_str_plain_List;  /* [338] str = 'List' */
    PyObject *const_str_plain_Optional;  /* [339] str = 'Optional' */
    PyObject *const_str_plain_Tuple;  /* [340] str = 'Tuple' */
    PyObject *const_str_plain_getLogger;  /* [341] str = 'getLogger' */
    PyObject *const_tuple_1_41;  /* [342] tuple = ('core.openvpn_mgr',) */
    PyObject *const_str_digest_b08297b6;  /* [343] str = 'http://127.0.0.1:28888' */
    PyObject *const_tuple_2_6;  /* [344] tuple = ('str', 'str') */
    PyObject *const_dict_2;  /* [345] dict = {'hostname': 'str', 'return': 'str'} */
    PyObject *const_str_digest_76d382a2;  /* [346] str = 'core.openvpn_mgr' */
    PyObject *const_str_digest_9c87e6e4;  /* [347] str = '\n    Quản lý Multi-OpenVPN không phụ thuộc WSL, không đụng... */
    PyObject *const_str_plain_OpenVPNManager;  /* [348] str = 'OpenVPNManager' */
    PyObject *const_str_plain___qualname__;  /* [349] str = '__qualname__' */
    PyObject *const_tuple_2_7;  /* [350] tuple = (None, None) */
    PyObject *const_dict_2_1;  /* [351] dict = {'config_dir': 'str', 'binary_dir': 'str'} */
    PyObject *const_str_digest_1bfde2d1;  /* [352] str = 'OpenVPNManager.__init__' */
    PyObject *const_dict_1;  /* [353] dict = {'return': 'bool'} */
    PyObject *const_str_digest_4a57944c;  /* [354] str = 'OpenVPNManager._unpack_engine_if_needed' */
    PyObject *const_str_plain_is_available;  /* [355] str = 'is_available' */
    PyObject *const_str_digest_6dbac282;  /* [356] str = 'OpenVPNManager.is_available' */
    PyObject *const_str_digest_fd17f2be;  /* [357] str = 'OpenVPNManager._is_whpx_supported' */
    PyObject *const_tuple_1_42;  /* [358] tuple = (3.5,) */
    PyObject *const_dict_2_2;  /* [359] dict = {'timeout': 'float', 'return': 'bool'} */
    PyObject *const_str_digest_f7917c5a;  /* [360] str = 'OpenVPNManager._is_agent_ready' */
    PyObject *const_tuple_1_43;  /* [361] tuple = (50,) */
    PyObject *const_dict_2_3;  /* [362] dict = {'timeout': 'int', 'return': 'bool'} */
    PyObject *const_str_digest_02788a43;  /* [363] str = 'OpenVPNManager.ensure_engine_ready' */
    PyObject *const_tuple_7;  /* [364] tuple = (502, 'tcp', '', '', '', '', '') */
    PyObject *const_str_plain_target_ip;  /* [365] str = 'target_ip' */
    PyObject *const_str_plain_target_port;  /* [366] str = 'target_port' */
    PyObject *const_str_plain_proto;  /* [367] str = 'proto' */
    PyObject *const_str_plain_base_ovpn_content;  /* [368] str = 'base_ovpn_content' */
    PyObject *const_str_plain_username;  /* [369] str = 'username' */
    PyObject *const_str_plain_password;  /* [370] str = 'password' */
    PyObject *const_str_plain_hostname;  /* [371] str = 'hostname' */
    PyObject *const_str_plain_country;  /* [372] str = 'country' */
    PyObject *const_str_plain_return;  /* [373] str = 'return' */
    PyObject *const_str_plain_build_ovpn_config;  /* [374] str = 'build_ovpn_config' */
    PyObject *const_str_digest_c87d2d6a;  /* [375] str = 'OpenVPNManager.build_ovpn_config' */
    PyObject *const_dict_1_1;  /* [376] dict = {'port': 'int'} */
    PyObject *const_str_digest_c7e9907b;  /* [377] str = 'OpenVPNManager._ensure_hostfwd' */
    PyObject *const_dict_5;  /* [378] dict = {'port': 'int', 'ovpn_file': 'str', 'auth_file_override': 's... */
    PyObject *const_str_plain_start_openvpn_instance;  /* [379] str = 'start_openvpn_instance' */
    PyObject *const_str_digest_3a410a14;  /* [380] str = 'OpenVPNManager.start_openvpn_instance' */
    PyObject *const_str_digest_f2cf41a0;  /* [381] str = 'OpenVPNManager._start_windows_listener' */
    PyObject *const_str_digest_9605c9e8;  /* [382] str = 'OpenVPNManager._stop_windows_listener' */
    PyObject *const_str_digest_89636ff2;  /* [383] str = 'OpenVPNManager._stop_all_windows_listeners' */
    PyObject *const_dict_2_4;  /* [384] dict = {'port': 'int', 'cleanup_files': 'bool'} */
    PyObject *const_str_digest_73d067d5;  /* [385] str = 'OpenVPNManager.stop_openvpn_instance' */
    PyObject *const_str_plain_stop_many_openvpn_instances;  /* [386] str = 'stop_many_openvpn_instances' */
    PyObject *const_str_digest_b70ac7ae;  /* [387] str = 'OpenVPNManager.stop_many_openvpn_instances' */
    PyObject *const_dict_3;  /* [388] dict = {'port': 'int', 'new_endpoint': 'str', 'return': 'bool'} */
    PyObject *const_str_plain_rotate_ip;  /* [389] str = 'rotate_ip' */
    PyObject *const_str_digest_05bbef10;  /* [390] str = 'OpenVPNManager.rotate_ip' */
    PyObject *const_dict_2_5;  /* [391] dict = {'port': 'int', 'return': 'bool'} */
    PyObject *const_str_plain_is_port_alive;  /* [392] str = 'is_port_alive' */
    PyObject *const_str_digest_3d462ce1;  /* [393] str = 'OpenVPNManager.is_port_alive' */
    PyObject *const_str_digest_65678989;  /* [394] str = 'OpenVPNManager.get_all_status' */
    PyObject *const_str_digest_e9f12dbc;  /* [395] str = 'OpenVPNManager.clean_all_containers' */
    PyObject *const_str_plain_stop_all;  /* [396] str = 'stop_all' */
    PyObject *const_str_digest_88f5c0fb;  /* [397] str = 'OpenVPNManager.stop_all' */
    PyObject *const_str_plain_openvpn_mgr;  /* [398] str = 'openvpn_mgr' */
    PyObject *const_str_digest_d0b2abe6;  /* [399] str = 'core\\openvpn_mgr.py' */
    PyObject *const_tuple_2_8;  /* [400] tuple = ('.0', 'p') */
    PyObject *const_tuple_3_2;  /* [401] tuple = ('p', 'self', 'cleanup_files') */
    PyObject *const_tuple_2_9;  /* [402] tuple = ('cleanup_files', 'self') */
    PyObject *const_str_digest_6685fbd7;  /* [403] str = '<module core.openvpn_mgr>' */
    PyObject *const_tuple_1_44;  /* [404] tuple = ('__class__',) */
    PyObject *const_tuple_4_3;  /* [405] tuple = ('self', 'config_dir', 'binary_dir', 'base_dir') */
    PyObject *const_tuple_4_4;  /* [406] tuple = ('self', 'port', 's', 'e') */
    PyObject *const_tuple_3_3;  /* [407] tuple = ('hostname', 'parts', 'ip') */
    PyObject *const_tuple_3_4;  /* [408] tuple = ('self', 'timeout', 'r') */
    PyObject *const_tuple_7_1;  /* [409] tuple = ('self', 'test_cmd', 'creation_flags', 'p', 'ret', 'out', 'e... */
    PyObject *const_tuple_5;  /* [410] tuple = ('self', 'port', 'stop_event', 'listener_worker', 't') */
    PyObject *const_tuple_3_5;  /* [411] tuple = ('self', 'p', 'ev') */
    PyObject *const_tuple_2_10;  /* [412] tuple = ('self', 'port') */
    PyObject *const_tuple_9;  /* [413] tuple = ('self', 'zlib_dll', 'base_dir', 'possible_zips', 'target_zi... */
    PyObject *const_tuple_24;  /* [414] tuple = ('self', 'port', 'target_ip', 'target_port', 'proto', 'base_... */
    PyObject *const_tuple_1_45;  /* [415] tuple = ('self',) */
    PyObject *const_tuple_19;  /* [416] tuple = ('self', 'timeout', 'start_wait', 'psutil', 'proc', 'hostfwd... */
    PyObject *const_tuple_6;  /* [417] tuple = ('client_sock', 'mux', 'pipe', 't1', 't2', 'port') */
    PyObject *const_tuple_2_11;  /* [418] tuple = ('self', 'r') */
    PyObject *const_tuple_4_5;  /* [419] tuple = ('self', 'port', 'status_list', 'p') */
    PyObject *const_tuple_7_2;  /* [420] tuple = ('srv', 'c', '_', 'forward_conn', 'e', 'port', 'stop_event') */
    PyObject *const_tuple_2_12;  /* [421] tuple = ('port', 'stop_event') */
    PyObject *const_tuple_3_6;  /* [422] tuple = ('s_in', 's_out', 'data') */
    PyObject *const_tuple_6_1;  /* [423] tuple = ('self', 'port', 'new_endpoint', 'payload', 'resp', 'e') */
    PyObject *const_tuple_26;  /* [424] tuple = ('self', 'port', 'ovpn_file', 'auth_file_override', 'endpoin... */
    PyObject *const_tuple_5_1;  /* [425] tuple = ('self', 'ports', 'cleanup_files', 'concurrent', 'executor') */
    PyObject *const_tuple_6_2;  /* [426] tuple = ('self', 'port', 'cleanup_files', 'e', 'shutil', 'port_dir') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.openvpn_mgr"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__binary_dir;   /* 'binary_dir' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__PIPE;   /* 'PIPE' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__status_code;   /* 'status_code' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__json;   /* 'json' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__qemu;   /* 'qemu' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__DEVNULL;   /* 'DEVNULL' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6___vm_stderr_file;   /* '_vm_stderr_file' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__payload;   /* 'payload' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8___start_windows_listener;   /* '_start_windows_listener' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__Thread;   /* 'Thread' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__forward_conn;   /* 'forward_conn' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__rmtree;   /* 'rmtree' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__map;   /* 'map' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__cleanup_files;   /* 'cleanup_files' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__get_all_status;   /* 'get_all_status' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__pathlib;   /* 'pathlib' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_16__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_17__openvpn_mgr;   /* 'openvpn_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_18__openvpn_mgr;   /* 'openvpn_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_19__openvpn_mgr;   /* 'openvpn_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_20__openvpn_mgr$gt$;   /* 'openvpn_mgr>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_21__openvpn_mgr$gt$;   /* 'openvpn_mgr>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_22__openvpn_mgr$gt$;   /* 'openvpn_mgr>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_23__openvpn_mgr$gt$;   /* 'openvpn_mgr>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def binary_dir(parents, exist_ok)
 *  qualname: binary_dir   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$binary_dir(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def PIPE(stdout, stderr, text, creationflags)
 *  qualname: PIPE   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$PIPE(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def status_code(timeout)
 *  qualname: status_code   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$status_code(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def json(status)
 *  qualname: json   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$json(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def qemu(name)
 *  qualname: qemu   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$qemu(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def DEVNULL(stdout, stderr)
 *  qualname: DEVNULL   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$DEVNULL(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _vm_stderr_file(cwd, stdout, stderr, creationflags)
 *  qualname: qemu_stderr.log   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$_vm_stderr_file(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def payload(json, timeout)
 *  qualname: payload   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$payload(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _start_windows_listener(success)
 *  qualname: _start_windows_listener   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$_start_windows_listener(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def Thread(target, daemon)
 *  qualname: OpenVPNManager._start_windows_listener.<locals>.listener_worker   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$Thread(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def forward_conn(target, args, daemon)
 *  qualname: OpenVPNManager._start_windows_listener.<locals>.listener_worker.<locals>.forward_conn   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$forward_conn(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def rmtree(ignore_errors)
 *  qualname: concurrent.futures   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$rmtree(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def map(max_workers)
 *  qualname: <lambda>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$map(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def cleanup_files(cleanup_files)
 *  qualname: cleanup_files   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$cleanup_files(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def get_all_status(port)
 *  qualname: get_all_status   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$get_all_status(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pathlib(Path)
 *  qualname: pathlib   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$pathlib(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(str, str)
 *  qualname: core.openvpn_mgr   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr(p, self, cleanup_files)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr(cleanup_files, self)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr>(__class__)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr>(self, config_dir, binary_dir, base_dir)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr>(self, port, s, e)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def openvpn_mgr>(hostname, parts, ip)
 *  qualname: <module core.openvpn_mgr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: OpenVPNManager
 *   methods recovered: 1
 *   class body was also compiled to native code */
static PyObject *impl_core$openvpn_mgr$OpenVPNManager$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars);  /* def OpenVPNManager.openvpn_mgr(.0, p) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$openvpn_mgr$binary_dir(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def binary_dir(parents, exist_ok): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$PIPE(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def PIPE(stdout, stderr, text, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$status_code(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def status_code(timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$json(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def json(status): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$qemu(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def qemu(name): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$DEVNULL(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def DEVNULL(stdout, stderr): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$_vm_stderr_file(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _vm_stderr_file(cwd, stdout, stderr, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$payload(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def payload(json, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$_start_windows_listener(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _start_windows_listener(success): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$Thread(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def Thread(target, daemon): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$forward_conn(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def forward_conn(target, args, daemon): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$rmtree(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def rmtree(ignore_errors): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$map(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def map(max_workers): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$cleanup_files(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def cleanup_files(cleanup_files): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$get_all_status(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def get_all_status(port): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$pathlib(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pathlib(Path): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(str, str): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr(p, self, cleanup_files): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr(cleanup_files, self): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr>(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr>(self, config_dir, binary_dir, base_dir): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr>(self, port, s, e): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$openvpn_mgr$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def openvpn_mgr>(hostname, parts, ip): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$openvpn_mgr$OpenVPNManager$openvpn_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* def OpenVPNManager.openvpn_mgr(.0, p): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$openvpn_mgr(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$openvpn_mgr = module;
    moduledict_core$openvpn_mgr = MODULE_DICT(module_core$openvpn_mgr);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1419CE1F0
     *
     * Recovered imports (detected from module constants): */
    /*   import zlib1.dll */
    /*   import qemu_engine.zip */
    /*   import qemu_engine_clean_backup.zip */
    /*   import alpine_tiny.qcow2 */
    /*   import alpine_root_2g.raw */
    /*   import vpn_data.tar */
    /*   import qemu_stderr.log */
    /*   import auth.txt */
    /*   import config.ovpn */
    /*   import s... */
    /*   import 0.0.0.0 */
    /*   import concurrent.futures */
    /*   import core.openvpn_mgr */
    /*   import OpenVPNManager.__init__ */
    /*   import OpenVPNManager._unpack_engine_if_needed */
    /*   import OpenVPNManager.is_available */
    /*   import OpenVPNManager._is_whpx_supported */
    /*   import OpenVPNManager._is_agent_ready */
    /*   import OpenVPNManager.ensure_engine_ready */
    /*   import OpenVPNManager.build_ovpn_config */
    /*   import OpenVPNManager._ensure_hostfwd */
    /*   import OpenVPNManager.start_openvpn_instance */
    /*   import OpenVPNManager._start_windows_listener */
    /*   import OpenVPNManager._stop_windows_listener */
    /*   import OpenVPNManager._stop_all_windows_listeners */
    /*   import OpenVPNManager.stop_openvpn_instance */
    /*   import OpenVPNManager.stop_many_openvpn_instances */
    /*   import OpenVPNManager.rotate_ip */
    /*   import OpenVPNManager.is_port_alive */
    /*   import OpenVPNManager.get_all_status */
    /*   import OpenVPNManager.clean_all_containers */
    /*   import OpenVPNManager.stop_all */

    return module;
}

