/* Reconstructed C source for Python module 'core.pia_api'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$pia_api @ 0x1419E7C40
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$pia_api;
PyDictObject *moduledict_core$pia_api;

/* Module constants: 218 entries recovered from blob chunk 'core.pia_api'. */
static struct ModuleConstants {
    PyObject *const_str_plain_x25519;  /* [0] str = 'x25519' */
    PyObject *const_str_plain_X25519PrivateKey;  /* [1] str = 'X25519PrivateKey' */
    PyObject *const_str_plain_generate;  /* [2] str = 'generate' */
    PyObject *const_str_plain_public_key;  /* [3] str = 'public_key' */
    PyObject *const_str_plain_private_bytes;  /* [4] str = 'private_bytes' */
    PyObject *const_str_plain_serialization;  /* [5] str = 'serialization' */
    PyObject *const_str_plain_Encoding;  /* [6] str = 'Encoding' */
    PyObject *const_str_plain_Raw;  /* [7] str = 'Raw' */
    PyObject *const_str_plain_PrivateFormat;  /* [8] str = 'PrivateFormat' */
    PyObject *const_str_plain_NoEncryption;  /* [9] str = 'NoEncryption' */
    PyObject *const_tuple_3;  /* [10] tuple = ('encoding', 'format', 'encryption_algorithm') */
    PyObject *const_str_plain_public_bytes;  /* [11] str = 'public_bytes' */
    PyObject *const_str_plain_PublicFormat;  /* [12] str = 'PublicFormat' */
    PyObject *const_tuple_2;  /* [13] tuple = ('encoding', 'format') */
    PyObject *const_str_plain_base64;  /* [14] str = 'base64' */
    PyObject *const_str_plain_b64encode;  /* [15] str = 'b64encode' */
    PyObject *const_str_plain_decode;  /* [16] str = 'decode' */
    PyObject *const_tuple_1;  /* [17] tuple = ('utf-8',) */
    PyObject *const_str_digest_649415ff;  /* [18] str = '\n        Sinh cặp khóa Wireguard (private_key, public_key)... */
    PyObject *const_str_digest_853ae90f;  /* [19] str = ':' */
    PyObject *const_str_plain_time;  /* [20] str = 'time' */
    PyObject *const_str_plain_PIAAPI;  /* [21] str = 'PIAAPI' */
    PyObject *const_str_plain__token_cache;  /* [22] str = '_token_cache' */
    PyObject *const_dict_1;  /* [23] dict = {'User-Agent': 'PIA-Proxy-Manager-v2'} */
    PyObject *const_str_plain_username;  /* [24] str = 'username' */
    PyObject *const_str_plain_password;  /* [25] str = 'password' */
    PyObject *const_str_plain_requests;  /* [26] str = 'requests' */
    PyObject *const_str_plain_post;  /* [27] str = 'post' */
    PyObject *const_str_plain_PIA_TOKEN_API;  /* [28] str = 'PIA_TOKEN_API' */
    PyObject *const_int_pos_8;  /* [29] int = 8 */
    PyObject *const_tuple_3_1;  /* [30] tuple = ('data', 'headers', 'timeout') */
    PyObject *const_str_plain_status_code;  /* [31] str = 'status_code' */
    PyObject *const_int_pos_401;  /* [32] int = 401 */
    PyObject *const_str_digest_c926f62c;  /* [33] str = 'Sai Tên đăng nhập hoặc Mật khẩu PIA (' */
    PyObject *const_str_digest_df5ba48d;  /* [34] str = ')!' */
    PyObject *const_int_pos_402;  /* [35] int = 402 */
    PyObject *const_str_digest_d487b2ea;  /* [36] str = 'Tài khoản PIA (' */
    PyObject *const_str_digest_51a59858;  /* [37] str = ') đã HẾT HẠN GÓI CƯỚC (Payment Required - 402)!' */
    PyObject *const_str_plain_raise_for_status;  /* [38] str = 'raise_for_status' */
    PyObject *const_str_plain_json;  /* [39] str = 'json' */
    PyObject *const_tuple_1_1;  /* [40] tuple = ('token',) */
    PyObject *const_str_plain_logger;  /* [41] str = 'logger' */
    PyObject *const_str_plain_info;  /* [42] str = 'info' */
    PyObject *const_str_digest_1e7f3d0d;  /* [43] str = 'Đã lấy token PIA qua API gốc cho user ' */
    PyObject *const_int_pos_82800;  /* [44] int = 82800 */
    PyObject *const_str_plain_warning;  /* [45] str = 'warning' */
    PyObject *const_str_digest_56cf9001;  /* [46] str = 'API gốc lấy token thất bại (' */
    PyObject *const_str_digest_b2e05a42;  /* [47] str = '), thử Meta Service...' */
    PyObject *const_str_plain_PIA_SERVER_LIST_API;  /* [48] str = 'PIA_SERVER_LIST_API' */
    PyObject *const_tuple_2_1;  /* [49] tuple = (False, 8) */
    PyObject *const_tuple_2_2;  /* [50] tuple = ('verify', 'timeout') */
    PyObject *const_str_plain_text;  /* [51] str = 'text' */
    PyObject *const_str_plain_strip;  /* [52] str = 'strip' */
    PyObject *const_str_plain_find;  /* [53] str = 'find' */
    PyObject *const_tuple_1_2;  /* [54] tuple = ('{',) */
    PyObject *const_str_plain_rfind;  /* [55] str = 'rfind' */
    PyObject *const_tuple_1_3;  /* [56] tuple = ('}',) */
    PyObject *const_str_plain_loads;  /* [57] str = 'loads' */
    PyObject *const_str_plain_regions;  /* [58] str = 'regions' */
    PyObject *const_str_plain_servers;  /* [59] str = 'servers' */
    PyObject *const_str_plain_meta;  /* [60] str = 'meta' */
    PyObject *const_str_plain_meta_servers;  /* [61] str = 'meta_servers' */
    PyObject *const_str_plain_append;  /* [62] str = 'append' */
    PyObject *const_tuple_1_4;  /* [63] tuple = ('ip',) */
    PyObject *const_str_plain_random;  /* [64] str = 'random' */
    PyObject *const_str_plain_sample;  /* [65] str = 'sample' */
    PyObject *const_str_plain_min;  /* [66] str = 'min' */
    PyObject *const_int_pos_3;  /* [67] int = 3 */
    PyObject *const_str_digest_f8eae675;  /* [68] str = 'https://' */
    PyObject *const_str_digest_5d032d38;  /* [69] str = ':443/authv3/generateToken' */
    PyObject *const_str_plain_data;  /* [70] str = 'data' */
    PyObject *const_str_plain_headers;  /* [71] str = 'headers' */
    PyObject *const_int_pos_5;  /* [72] int = 5 */
    PyObject *const_tuple_4;  /* [73] tuple = ('params', 'headers', 'verify', 'timeout') */
    PyObject *const_int_pos_200;  /* [74] int = 200 */
    PyObject *const_str_digest_f7b180b7;  /* [75] str = 'Đã lấy token PIA qua Meta Service (' */
    PyObject *const_str_digest_6e7fa8a0;  /* [76] str = ') cho user ' */
    PyObject *const_str_plain_now;  /* [77] str = 'now' */
    PyObject *const_str_plain_cache_key;  /* [78] str = 'cache_key' */
    PyObject *const_str_plain_error;  /* [79] str = 'error' */
    PyObject *const_str_digest_ecc61bad;  /* [80] str = 'Lỗi khi lấy token PIA: ' */
    PyObject *const_str_digest_57f85b27;  /* [81] str = '\n        Lấy token xác thực từ PIA API (Có cache 23h trong... */
    PyObject *const_tuple_2_3;  /* [82] tuple = (False, 30) */
    PyObject *const_tuple_1_5;  /* [83] tuple = ('country',) */
    PyObject *const_str_plain_country;  /* [84] str = 'country' */
    PyObject *const_str_plain_upper;  /* [85] str = 'upper' */
    PyObject *const_str_plain_wireguard;  /* [86] str = 'wireguard' */
    PyObject *const_str_plain_wg;  /* [87] str = 'wg' */
    PyObject *const_str_plain_openvpn;  /* [88] str = 'openvpn' */
    PyObject *const_str_plain_ovpnudp;  /* [89] str = 'ovpnudp' */
    PyObject *const_str_plain_protocol_key;  /* [90] str = 'protocol_key' */
    PyObject *const_str_plain_ip;  /* [91] str = 'ip' */
    PyObject *const_str_plain_region;  /* [92] str = 'region' */
    PyObject *const_str_plain_region_name;  /* [93] str = 'region_name' */
    PyObject *const_tuple_1_6;  /* [94] tuple = ('name',) */
    PyObject *const_str_plain_port_forward;  /* [95] str = 'port_forward' */
    PyObject *const_tuple_2_4;  /* [96] tuple = ('port_forward', False) */
    PyObject *const_str_digest_46d05aa6;  /* [97] str = 'Đã lấy ' */
    PyObject *const_str_digest_6116b13f;  /* [98] str = ' server ' */
    PyObject *const_str_digest_0eb819b3;  /* [99] str = ' cho quốc gia ' */
    PyObject *const_str_digest_fd93b8b6;  /* [100] str = 'Lỗi khi lấy server list: ' */
    PyObject *const_str_digest_3472a623;  /* [101] str = '\n        Lấy danh sách server từ PIA\n        \n        Ar... */
    PyObject *const_str_digest_a0e9a534;  /* [102] str = ':1337/addKey' */
    PyObject *const_str_plain_pt;  /* [103] str = 'pt' */
    PyObject *const_str_plain_token;  /* [104] str = 'token' */
    PyObject *const_str_plain_pubkey;  /* [105] str = 'pubkey' */
    PyObject *const_str_plain_current_public_key;  /* [106] str = 'current_public_key' */
    PyObject *const_float_6_0;  /* [107] float = 6.0 */
    PyObject *const_tuple_3_2;  /* [108] tuple = ('params', 'verify', 'timeout') */
    PyObject *const_str_plain_server_public_key;  /* [109] str = 'server_public_key' */
    PyObject *const_tuple_1_7;  /* [110] tuple = ('server_key',) */
    PyObject *const_str_plain_server_port;  /* [111] str = 'server_port' */
    PyObject *const_tuple_2_5;  /* [112] tuple = ('server_port', 41820) */
    PyObject *const_str_plain_peer_ip;  /* [113] str = 'peer_ip' */
    PyObject *const_tuple_1_8;  /* [114] tuple = ('peer_ip',) */
    PyObject *const_str_plain_private_key;  /* [115] str = 'private_key' */
    PyObject *const_str_plain_current_private_key;  /* [116] str = 'current_private_key' */
    PyObject *const_str_digest_02682492;  /* [117] str = 'Đã đăng ký key với server ' */
    PyObject *const_str_digest_ffe57e9c;  /* [118] str = ', peer IP: ' */
    PyObject *const_str_plain_exceptions;  /* [119] str = 'exceptions' */
    PyObject *const_str_plain_HTTPError;  /* [120] str = 'HTTPError' */
    PyObject *const_str_plain_response;  /* [121] str = 'response' */
    PyObject *const_int_pos_409;  /* [122] int = 409 */
    PyObject *const_str_digest_b80869a0;  /* [123] str = 'Conflict khi đăng ký key với server ' */
    PyObject *const_str_digest_03592ed6;  /* [124] str = ', sinh key mới và retry (attempt ' */
    PyObject *const_str_plain_max_retries;  /* [125] str = 'max_retries' */
    PyObject *const_str_digest_9371d7a2;  /* [126] str = ')' */
    PyObject *const_str_plain_generate_wireguard_keys;  /* [127] str = 'generate_wireguard_keys' */
    PyObject *const_str_digest_c69abfff;  /* [128] str = 'Lỗi HTTP khi đăng ký key: ' */
    PyObject *const_str_plain_Timeout;  /* [129] str = 'Timeout' */
    PyObject *const_str_digest_a3986dd4;  /* [130] str = 'Timeout khi đăng ký key với ' */
    PyObject *const_str_digest_20fb5ac2;  /* [131] str = ' (port 1337): ' */
    PyObject *const_str_plain_ConnectionError;  /* [132] str = 'ConnectionError' */
    PyObject *const_str_digest_913f481f;  /* [133] str = 'Không thể kết nối port 1337 server ' */
    PyObject *const_str_digest_e2654927;  /* [134] str = ': ' */
    PyObject *const_str_digest_add2a499;  /* [135] str = 'Lỗi khi đăng ký Wireguard key với server ' */
    PyObject *const_str_digest_5aa9cc98;  /* [136] str = 'Không thể đăng ký key với server ' */
    PyObject *const_str_digest_77c77338;  /* [137] str = ' sau ' */
    PyObject *const_str_digest_8757e6ca;  /* [138] str = ' lần thử' */
    PyObject *const_str_digest_e5a36447;  /* [139] str = '\n        Đăng ký public key với server PIA qua port 1337\n... */
    PyObject *const_str_digest_af531fe7;  /* [140] str = 'Đã lấy OpenVPN credentials cho user ' */
    PyObject *const_str_digest_e11f3d2b;  /* [141] str = 'Lỗi khi lấy OpenVPN credentials: ' */
    PyObject *const_str_digest_812f1696;  /* [142] str = '\n        Lấy thông tin OpenVPN credentials từ PIA\n       ... */
    PyObject *const_str_plain_get_server_list;  /* [143] str = 'get_server_list' */
    PyObject *const_str_plain_available_servers;  /* [144] str = 'available_servers' */
    PyObject *const_str_plain_existing_ips;  /* [145] str = 'existing_ips' */
    PyObject *const_str_plain_add;  /* [146] str = 'add' */
    PyObject *const_str_digest_29344eed;  /* [147] str = 'được chọn' */
    PyObject *const_str_digest_94f2fe44;  /* [148] str = '⚠️ Quốc gia ' */
    PyObject *const_str_digest_f44d0c48;  /* [149] str = ' chỉ có ' */
    PyObject *const_str_digest_c8eb1c96;  /* [150] str = ' server WireGuard khả dụng. Hệ thống đã tự động bổ sung ' */
    PyObject *const_str_digest_d64bfe50;  /* [151] str = ' server từ các khu vực khác để đảm bảo 100% Unique IP không... */
    PyObject *const_str_plain_sort_key;  /* [152] str = 'sort_key' */
    PyObject *const_str_digest_d73b1d3b;  /* [153] str = 'PIAAPI.get_random_servers.<locals>.sort_key' */
    PyObject *const_str_plain_sort;  /* [154] str = 'sort' */
    PyObject *const_tuple_1_9;  /* [155] tuple = ('key',) */
    PyObject *const_str_plain_shuffle;  /* [156] str = 'shuffle' */
    PyObject *const_str_plain_selected;  /* [157] str = 'selected' */
    PyObject *const_str_plain_expansion_warning;  /* [158] str = 'expansion_warning' */
    PyObject *const_str_digest_bea404c4;  /* [159] str = '\n        Lấy ngẫu nhiên N server từ danh sách, ưu tiên ser... */
    PyObject *const_tuple_2_6;  /* [160] tuple = ('ip', '') */
    PyObject *const_str_plain_server_usage;  /* [161] str = 'server_usage' */
    PyObject *const_str_plain_origin;  /* [162] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [163] str = 'has_location' */
    PyObject *const_str_plain_urllib3;  /* [164] str = 'urllib3' */
    PyObject *const_str_plain_logging;  /* [165] str = 'logging' */
    PyObject *const_str_digest_89c71aa6;  /* [166] str = 'cryptography.hazmat.primitives.asymmetric' */
    PyObject *const_tuple_1_10;  /* [167] tuple = ('x25519',) */
    PyObject *const_str_digest_3961a5ef;  /* [168] str = 'cryptography.hazmat.primitives' */
    PyObject *const_tuple_1_11;  /* [169] tuple = ('serialization',) */
    PyObject *const_str_digest_648a792d;  /* [170] str = 'cryptography.hazmat.backends' */
    PyObject *const_tuple_1_12;  /* [171] tuple = ('default_backend',) */
    PyObject *const_str_plain_default_backend;  /* [172] str = 'default_backend' */
    PyObject *const_str_plain_Dict;  /* [173] str = 'Dict' */
    PyObject *const_str_plain_List;  /* [174] str = 'List' */
    PyObject *const_str_plain_Optional;  /* [175] str = 'Optional' */
    PyObject *const_str_plain_disable_warnings;  /* [176] str = 'disable_warnings' */
    PyObject *const_str_plain_InsecureRequestWarning;  /* [177] str = 'InsecureRequestWarning' */
    PyObject *const_str_plain_getLogger;  /* [178] str = 'getLogger' */
    PyObject *const_tuple_1_13;  /* [179] tuple = ('core.pia_api',) */
    PyObject *const_str_digest_2d13e6d0;  /* [180] str = 'https://www.privateinternetaccess.com/api/client/v2/token' */
    PyObject *const_str_digest_7d90e03e;  /* [181] str = 'https://serverlist.piaservers.net/vpninfo/servers/v4' */
    PyObject *const_str_digest_13b2711b;  /* [182] str = 'core.pia_api' */
    PyObject *const_str_digest_03d4d9f9;  /* [183] str = 'Giao tiếp với API của Private Internet Access' */
    PyObject *const_str_plain___qualname__;  /* [184] str = '__qualname__' */
    PyObject *const_dict_1_1;  /* [185] dict = {'return': ('GenericAlias', 'tuple', ('str', 'str'))} */
    PyObject *const_str_digest_f0807f49;  /* [186] str = 'PIAAPI.generate_wireguard_keys' */
    PyObject *const_dict_3;  /* [187] dict = {'username': 'str', 'password': 'str', 'return': 'str'} */
    PyObject *const_str_plain_get_pia_token;  /* [188] str = 'get_pia_token' */
    PyObject *const_str_digest_e2b307b8;  /* [189] str = 'PIAAPI.get_pia_token' */
    PyObject *const_tuple_2_7;  /* [190] tuple = (None, 'wireguard') */
    PyObject *const_str_plain_protocol;  /* [191] str = 'protocol' */
    PyObject *const_str_plain_return;  /* [192] str = 'return' */
    PyObject *const_str_digest_dfef2e94;  /* [193] str = 'PIAAPI.get_server_list' */
    PyObject *const_tuple_1_14;  /* [194] tuple = (3,) */
    PyObject *const_str_plain_server_ip;  /* [195] str = 'server_ip' */
    PyObject *const_str_plain_register_wireguard_key;  /* [196] str = 'register_wireguard_key' */
    PyObject *const_str_digest_c30f26b9;  /* [197] str = 'PIAAPI.register_wireguard_key' */
    PyObject *const_str_plain_get_openvpn_credentials;  /* [198] str = 'get_openvpn_credentials' */
    PyObject *const_str_digest_8d459db9;  /* [199] str = 'PIAAPI.get_openvpn_credentials' */
    PyObject *const_tuple_5;  /* [200] tuple = (None, False, 'wireguard', None, None) */
    PyObject *const_str_plain_count;  /* [201] str = 'count' */
    PyObject *const_str_plain_port_forward_only;  /* [202] str = 'port_forward_only' */
    PyObject *const_tuple_2_8;  /* [203] tuple = ('str', 'int') */
    PyObject *const_str_plain_exclude_ips;  /* [204] str = 'exclude_ips' */
    PyObject *const_str_plain_get_random_servers;  /* [205] str = 'get_random_servers' */
    PyObject *const_str_digest_8ee6751e;  /* [206] str = 'PIAAPI.get_random_servers' */
    PyObject *const_str_digest_c1f568c4;  /* [207] str = 'core\\pia_api.py' */
    PyObject *const_str_digest_cc0d1c1d;  /* [208] str = '<module core.pia_api>' */
    PyObject *const_tuple_1_15;  /* [209] tuple = ('__class__',) */
    PyObject *const_tuple_7;  /* [210] tuple = ('private_key', 'public_key', 'private_bytes', 'public_bytes... */
    PyObject *const_tuple_4_1;  /* [211] tuple = ('username', 'password', 'credentials', 'e') */
    PyObject *const_tuple_23;  /* [212] tuple = ('username', 'password', 'cache_key', 'now', 'cached_token',... */
    PyObject *const_tuple_19;  /* [213] tuple = ('count', 'country', 'port_forward_only', 'protocol', 'serve... */
    PyObject *const_tuple_14;  /* [214] tuple = ('country', 'protocol', 'response', 'text', 'start_idx', 'en... */
    PyObject *const_tuple_13;  /* [215] tuple = ('server_ip', 'token', 'private_key', 'public_key', 'max_ret... */
    PyObject *const_tuple_3_3;  /* [216] tuple = ('s', 'ip', 'server_usage') */
    PyObject *const_tuple_1_16;  /* [217] tuple = ('server_usage',) */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.pia_api"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__NoEncryption;   /* 'NoEncryption' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__PublicFormat;   /* 'PublicFormat' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__status_code;   /* 'status_code' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__json;   /* 'json' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__text;   /* 'text' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__append;   /* 'append' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__headers;   /* 'headers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__country;   /* 'country' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__region_name;   /* 'region_name' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__server_public_key;   /* 'server_public_key' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__server_public_key;   /* 'server_public_key' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__peer_ip;   /* 'peer_ip' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__sort;   /* 'sort' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__logging;   /* 'logging' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__default_backend;   /* 'default_backend' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__default_backend;   /* 'default_backend' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_16__port_forward_only;   /* 'port_forward_only' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_17__get_random_servers;   /* 'get_random_servers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_18__pia_api$gt$;   /* 'pia_api>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_19__pia_api$gt$;   /* 'pia_api>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_20__pia_api$gt$;   /* 'pia_api>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def NoEncryption(encoding, format, encryption_algorithm)
 *  qualname: NoEncryption   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$NoEncryption(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def PublicFormat(encoding, format)
 *  qualname: PublicFormat   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$PublicFormat(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def status_code(data, headers, timeout)
 *  qualname: status_code   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$status_code(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def json(token)
 *  qualname: json   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$json(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def text(verify, timeout)
 *  qualname: text   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$text(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def append(ip)
 *  qualname: append   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$append(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def headers(params, headers, verify, timeout)
 *  qualname: headers   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$headers(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def country(country)
 *  qualname: country   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$country(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def region_name(name)
 *  qualname: region_name   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$region_name(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def server_public_key(params, verify, timeout)
 *  qualname: server_public_key   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$server_public_key(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def server_public_key(server_key)
 *  qualname: server_public_key   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$server_public_key(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def peer_ip(peer_ip)
 *  qualname: peer_ip   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$peer_ip(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def sort(key)
 *  qualname: PIAAPI.get_random_servers.<locals>.sort_key   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$sort(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def logging(x25519)
 *  qualname: cryptography.hazmat.primitives.asymmetric   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$logging(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def default_backend(serialization)
 *  qualname: cryptography.hazmat.primitives   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$default_backend(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def default_backend(default_backend)
 *  qualname: cryptography.hazmat.backends   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$default_backend(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def get_random_servers(__class__)
 *  qualname: <module core.pia_api>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$get_random_servers(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pia_api>(private_key, public_key, private_bytes, public_bytes, base64, private_key_b64, public_key_b64)
 *  qualname: <module core.pia_api>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pia_api>(username, password, credentials, e)
 *  qualname: <module core.pia_api>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pia_api>(username, password, cache_key, now, cached_token, expire_at, headers, data, response, token, ve, e, text, start_idx, end_idx, server_data, regions, meta_servers, region, meta_list, server, meta_ip, meta_url)
 *  qualname: <module core.pia_api>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: PIAAPI
 *   methods recovered: 1
 *   class body was also compiled to native code */
static PyObject *impl_core$pia_api$PIAAPI$port_forward_only(PyThreadState *tstate, PyObject **python_pars);  /* def PIAAPI.port_forward_only(str, int) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$pia_api$NoEncryption(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def NoEncryption(encoding, format, encryption_algorithm): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$PublicFormat(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def PublicFormat(encoding, format): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$status_code(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def status_code(data, headers, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$json(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def json(token): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$text(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def text(verify, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$append(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def append(ip): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$headers(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def headers(params, headers, verify, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$country(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def country(country): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$region_name(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def region_name(name): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$server_public_key(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def server_public_key(params, verify, timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$server_public_key(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def server_public_key(server_key): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$peer_ip(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def peer_ip(peer_ip): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$sort(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def sort(key): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$logging(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def logging(x25519): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$default_backend(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def default_backend(serialization): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$default_backend(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def default_backend(default_backend): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$get_random_servers(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def get_random_servers(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pia_api>(private_key, public_key, private_bytes, public_bytes, base64, private_key_b64, public_key_b64): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pia_api>(username, password, credentials, e): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$pia_api$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pia_api>(username, password, cache_key, now, cached_token, expire_at, headers, data, response, token, ve, e, text, start_idx, end_idx, server_data, regions, meta_servers, region, meta_list, server, meta_ip, meta_url): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$pia_api$PIAAPI$port_forward_only(PyThreadState *tstate, PyObject **python_pars) {
    /* def PIAAPI.port_forward_only(str, int): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$pia_api(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$pia_api = module;
    moduledict_core$pia_api = MODULE_DICT(module_core$pia_api);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x1419E7C40
     *
     * Recovered imports (detected from module constants): */
    /*   import cryptography.hazmat.primitives.asymmetric */
    /*   import cryptography.hazmat.primitives */
    /*   import cryptography.hazmat.backends */
    /*   import core.pia_api */
    /*   import PIAAPI.generate_wireguard_keys */
    /*   import PIAAPI.get_pia_token */
    /*   import PIAAPI.get_server_list */
    /*   import PIAAPI.register_wireguard_key */
    /*   import PIAAPI.get_openvpn_credentials */
    /*   import PIAAPI.get_random_servers */

    return module;
}

