/* Reconstructed C source for Python module 'core.provider_servers'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$provider_servers @ 0x141A07C60
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$provider_servers;
PyDictObject *moduledict_core$provider_servers;

/* Module constants: 207 entries recovered from blob chunk 'core.provider_servers'. */
static struct ModuleConstants {
    PyObject *const_str_plain_Path;  /* [0] str = 'Path' */
    PyObject *const_str_plain_resolve;  /* [1] str = 'resolve' */
    PyObject *const_str_plain_resources;  /* [2] str = 'resources' */
    PyObject *const_str_plain_servers;  /* [3] str = 'servers' */
    PyObject *const_str_plain_cache_dir;  /* [4] str = 'cache_dir' */
    PyObject *const_str_plain_mkdir;  /* [5] str = 'mkdir' */
    PyObject *const_tuple_2;  /* [6] tuple = (True, True) */
    PyObject *const_tuple_2_1;  /* [7] tuple = ('parents', 'exist_ok') */
    PyObject *const_str_plain__cache;  /* [8] str = '_cache' */
    PyObject *const_str_digest_cc8f0c0e;  /* [9] str = '.json' */
    PyObject *const_str_plain_GLUETUN_URLS;  /* [10] str = 'GLUETUN_URLS' */
    PyObject *const_str_digest_08faac81;  /* [11] str = 'Unknown provider: ' */
    PyObject *const_str_plain_logger;  /* [12] str = 'logger' */
    PyObject *const_str_plain_info;  /* [13] str = 'info' */
    PyObject *const_str_digest_957bdcc8;  /* [14] str = 'Fetching server list for ' */
    PyObject *const_str_digest_a8556338;  /* [15] str = ' from gluetun-servers...' */
    PyObject *const_str_plain_urlopen;  /* [16] str = 'urlopen' */
    PyObject *const_tuple_1;  /* [17] tuple = (60,) */
    PyObject *const_tuple_1_1;  /* [18] tuple = ('timeout',) */
    PyObject *const_str_plain_json;  /* [19] str = 'json' */
    PyObject *const_str_plain_loads;  /* [20] str = 'loads' */
    PyObject *const_str_plain_decode;  /* [21] str = 'decode' */
    PyObject *const_tuple_1_2;  /* [22] tuple = ('utf-8',) */
    PyObject *const_tuple_3;  /* [23] tuple = (None, None, None) */
    PyObject *const_str_plain__get_cache_path;  /* [24] str = '_get_cache_path' */
    PyObject *const_str_digest_e9e2aa81;  /* [25] str = 'utf-8' */
    PyObject *const_str_plain_dump;  /* [26] str = 'dump' */
    PyObject *const_str_plain_data;  /* [27] str = 'data' */
    PyObject *const_str_digest_f1256fe3;  /* [28] str = 'Cached ' */
    PyObject *const_str_digest_75ba31ea;  /* [29] str = ' server list to ' */
    PyObject *const_str_plain_error;  /* [30] str = 'error' */
    PyObject *const_str_digest_b4ef9ba2;  /* [31] str = 'Failed to fetch ' */
    PyObject *const_str_digest_b2de349b;  /* [32] str = ' server list: ' */
    PyObject *const_str_plain_load;  /* [33] str = 'load' */
    PyObject *const_tuple_2_2;  /* [34] tuple = ('timestamp', 0) */
    PyObject *const_str_plain_time;  /* [35] str = 'time' */
    PyObject *const_str_plain_CACHE_TTL;  /* [36] str = 'CACHE_TTL' */
    PyObject *const_str_plain_debug;  /* [37] str = 'debug' */
    PyObject *const_str_digest_79ad8cca;  /* [38] str = 'Loaded ' */
    PyObject *const_str_digest_2791b6dc;  /* [39] str = ' server list from cache' */
    PyObject *const_str_digest_ee3e1a50;  /* [40] str = 'Cache for ' */
    PyObject *const_str_digest_1dd2323e;  /* [41] str = ' expired, refreshing...' */
    PyObject *const_str_plain_warning;  /* [42] str = 'warning' */
    PyObject *const_str_digest_ae61c555;  /* [43] str = 'Failed to read cache for ' */
    PyObject *const_str_digest_e2654927;  /* [44] str = ': ' */
    PyObject *const_str_plain__fetch_from_gluetun;  /* [45] str = '_fetch_from_gluetun' */
    PyObject *const_str_digest_2cbeccec;  /* [46] str = 'Fetch failed, using stale cache for ' */
    PyObject *const_str_plain__load_or_fetch;  /* [47] str = '_load_or_fetch' */
    PyObject *const_str_plain_pia;  /* [48] str = 'pia' */
    PyObject *const_tuple_2_3;  /* [49] tuple = ('version', 1) */
    PyObject *const_tuple_2_4;  /* [50] tuple = ('region', '') */
    PyObject *const_str_plain_strip;  /* [51] str = 'strip' */
    PyObject *const_str_plain_COUNTRY_TO_CODE;  /* [52] str = 'COUNTRY_TO_CODE' */
    PyObject *const_str_plain_XX;  /* [53] str = 'XX' */
    PyObject *const_str_plain_isupper;  /* [54] str = 'isupper' */
    PyObject *const_str_plain_UK;  /* [55] str = 'UK' */
    PyObject *const_str_plain_GB;  /* [56] str = 'GB' */
    PyObject *const_str_plain_CODE_TO_COUNTRY;  /* [57] str = 'CODE_TO_COUNTRY' */
    PyObject *const_str_plain_parsed;  /* [58] str = 'parsed' */
    PyObject *const_str_plain_provider;  /* [59] str = 'provider' */
    PyObject *const_str_plain_country_code;  /* [60] str = 'country_code' */
    PyObject *const_str_plain_country_name;  /* [61] str = 'country_name' */
    PyObject *const_str_plain_region;  /* [62] str = 'region' */
    PyObject *const_str_plain_city;  /* [63] str = 'city' */
    PyObject *const_str_plain_vpn;  /* [64] str = 'vpn' */
    PyObject *const_tuple_2_5;  /* [65] tuple = ('vpn', 'openvpn') */
    PyObject *const_str_plain_tcp;  /* [66] str = 'tcp' */
    PyObject *const_tuple_2_6;  /* [67] tuple = ('tcp', False) */
    PyObject *const_str_plain_udp;  /* [68] str = 'udp' */
    PyObject *const_tuple_2_7;  /* [69] tuple = ('udp', False) */
    PyObject *const_str_plain_port_forward;  /* [70] str = 'port_forward' */
    PyObject *const_tuple_2_8;  /* [71] tuple = ('port_forward', False) */
    PyObject *const_str_plain_hostname;  /* [72] str = 'hostname' */
    PyObject *const_tuple_2_9;  /* [73] tuple = ('hostname', '') */
    PyObject *const_str_plain_ips;  /* [74] str = 'ips' */
    PyObject *const_tuple_2_10;  /* [75] tuple = ('country', '') */
    PyObject *const_str_plain_items;  /* [76] str = 'items' */
    PyObject *const_str_plain_country;  /* [77] str = 'country' */
    PyObject *const_str_plain_startswith;  /* [78] str = 'startswith' */
    PyObject *const_tuple_2_11;  /* [79] tuple = ('city', '') */
    PyObject *const_str_plain_wgpubkey;  /* [80] str = 'wgpubkey' */
    PyObject *const_tuple_1_3;  /* [81] tuple = ('wgpubkey',) */
    PyObject *const_str_plain__parse_servers;  /* [82] str = '_parse_servers' */
    PyObject *const_str_plain_wireguard;  /* [83] str = 'wireguard' */
    PyObject *const_tuple_1_4;  /* [84] tuple = ('vpn',) */
    PyObject *const_str_plain_openvpn;  /* [85] str = 'openvpn' */
    PyObject *const_str_plain_country_map;  /* [86] str = 'country_map' */
    PyObject *const_str_plain_code;  /* [87] str = 'code' */
    PyObject *const_str_plain_count;  /* [88] str = 'count' */
    PyObject *const_str_plain_sorted;  /* [89] str = 'sorted' */
    PyObject *const_str_digest_11659e6b;  /* [90] str = '<lambda>' */
    PyObject *const_str_digest_f6091424;  /* [91] str = 'ProviderServerRegistry.get_countries.<locals>.<lambda>' */
    PyObject *const_tuple_1_5;  /* [92] tuple = ('key',) */
    PyObject *const_str_plain_upper;  /* [93] str = 'upper' */
    PyObject *const_tuple_1_6;  /* [94] tuple = ('tcp',) */
    PyObject *const_tuple_1_7;  /* [95] tuple = ('udp',) */
    PyObject *const_str_plain_get_servers;  /* [96] str = 'get_servers' */
    PyObject *const_str_plain_random;  /* [97] str = 'random' */
    PyObject *const_str_plain_sample;  /* [98] str = 'sample' */
    PyObject *const_str_plain_min;  /* [99] str = 'min' */
    PyObject *const_str_digest_a49c8f51;  /* [100] str = '<genexpr>' */
    PyObject *const_str_digest_220a47f9;  /* [101] str = 'ProviderServerRegistry.has_vpn_type.<locals>.<genexpr>' */
    PyObject *const_tuple_3_1;  /* [102] tuple = ('country', 'vpn', 'protocol') */
    PyObject *const_tuple_2_12;  /* [103] tuple = ('country', 'vpn') */
    PyObject *const_tuple_1_8;  /* [104] tuple = ('hostname',) */
    PyObject *const_str_plain_target_ip;  /* [105] str = 'target_ip' */
    PyObject *const_str_plain_unique_candidates;  /* [106] str = 'unique_candidates' */
    PyObject *const_str_plain_append;  /* [107] str = 'append' */
    PyObject *const_str_digest_29344eed;  /* [108] str = 'được chọn' */
    PyObject *const_str_digest_94f2fe44;  /* [109] str = '⚠️ Quốc gia ' */
    PyObject *const_str_digest_f44d0c48;  /* [110] str = ' chỉ có ' */
    PyObject *const_str_digest_6116b13f;  /* [111] str = ' server ' */
    PyObject *const_str_digest_c25bc4fd;  /* [112] str = ' khả dụng. Hệ thống đã tự động bổ sung ' */
    PyObject *const_str_digest_d64bfe50;  /* [113] str = ' server từ các khu vực khác để đảm bảo 100% Unique IP không... */
    PyObject *const_str_plain_sort;  /* [114] str = 'sort' */
    PyObject *const_str_digest_412a3b05;  /* [115] str = 'ProviderServerRegistry.select_servers.<locals>.<lambda>' */
    PyObject *const_str_plain_shuffle;  /* [116] str = 'shuffle' */
    PyObject *const_str_plain_selected;  /* [117] str = 'selected' */
    PyObject *const_str_plain_result;  /* [118] str = 'result' */
    PyObject *const_tuple_2_13;  /* [119] tuple = ('country_code', '') */
    PyObject *const_tuple_2_14;  /* [120] tuple = ('country_name', '') */
    PyObject *const_str_plain_expansion_warning;  /* [121] str = 'expansion_warning' */
    PyObject *const_str_plain_expanded;  /* [122] str = 'expanded' */
    PyObject *const_str_plain_sort_key;  /* [123] str = 'sort_key' */
    PyObject *const_str_digest_2c6d3d07;  /* [124] str = 'ProviderServerRegistry.select_servers.<locals>.sort_key' */
    PyObject *const_str_plain_choice;  /* [125] str = 'choice' */
    PyObject *const_str_plain_ip;  /* [126] str = 'ip' */
    PyObject *const_str_digest_3ac360fc;  /* [127] str = 'ProviderServerRegistry.select_servers.<locals>.<genexpr>' */
    PyObject *const_str_plain_server_usage;  /* [128] str = 'server_usage' */
    PyObject *const_tuple_1_9;  /* [129] tuple = ('ips',) */
    PyObject *const_str_digest_f1f17934;  /* [130] str = '0.0.0.0' */
    PyObject *const_str_plain_self;  /* [131] str = 'self' */
    PyObject *const_str_digest_3fea34ed;  /* [132] str = 'Failed to refresh ' */
    PyObject *const_str_plain_origin;  /* [133] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [134] str = 'has_location' */
    PyObject *const_str_plain_logging;  /* [135] str = 'logging' */
    PyObject *const_str_plain_os;  /* [136] str = 'os' */
    PyObject *const_str_plain_pathlib;  /* [137] str = 'pathlib' */
    PyObject *const_tuple_1_10;  /* [138] tuple = ('Path',) */
    PyObject *const_str_plain_Dict;  /* [139] str = 'Dict' */
    PyObject *const_str_plain_List;  /* [140] str = 'List' */
    PyObject *const_str_plain_Optional;  /* [141] str = 'Optional' */
    PyObject *const_str_digest_b08c6262;  /* [142] str = 'urllib.request' */
    PyObject *const_tuple_1_11;  /* [143] tuple = ('urlopen',) */
    PyObject *const_str_plain_getLogger;  /* [144] str = 'getLogger' */
    PyObject *const_tuple_1_12;  /* [145] tuple = ('core.provider_servers',) */
    PyObject *const_dict_141;  /* [146] dict = {'Afghanistan': 'AF', 'Albania': 'AL', 'Algeria': 'DZ', 'And... */
    PyObject *const_str_digest_89f9c9f4;  /* [147] str = 'United Kingdom' */
    PyObject *const_str_digest_f253efe3;  /* [148] str = 'United States' */
    PyObject *const_str_plain_US;  /* [149] str = 'US' */
    PyObject *const_str_digest_4d4803b0;  /* [150] str = 'South Korea' */
    PyObject *const_str_plain_KR;  /* [151] str = 'KR' */
    PyObject *const_str_plain_Vietnam;  /* [152] str = 'Vietnam' */
    PyObject *const_str_plain_VN;  /* [153] str = 'VN' */
    PyObject *const_dict_23;  /* [154] dict = {'pia': 'https://raw.githubusercontent.com/qdm12/gluetun-ser... */
    PyObject *const_int_pos_86400;  /* [155] int = 86400 */
    PyObject *const_str_digest_5f796d2a;  /* [156] str = 'core.provider_servers' */
    PyObject *const_str_plain_ProviderServerRegistry;  /* [157] str = 'ProviderServerRegistry' */
    PyObject *const_str_plain___qualname__;  /* [158] str = '__qualname__' */
    PyObject *const_tuple_1_13;  /* [159] tuple = (None,) */
    PyObject *const_dict_1;  /* [160] dict = {'cache_dir': 'str'} */
    PyObject *const_str_digest_fb965037;  /* [161] str = 'ProviderServerRegistry.__init__' */
    PyObject *const_str_plain_return;  /* [162] str = 'return' */
    PyObject *const_str_digest_c0fb530c;  /* [163] str = 'ProviderServerRegistry._get_cache_path' */
    PyObject *const_dict_2;  /* [164] dict = {'provider': 'str', 'return': 'dict'} */
    PyObject *const_str_digest_56f7cabb;  /* [165] str = 'ProviderServerRegistry._fetch_from_gluetun' */
    PyObject *const_str_digest_1f0ef49f;  /* [166] str = 'ProviderServerRegistry._load_or_fetch' */
    PyObject *const_str_digest_5ac50024;  /* [167] str = 'ProviderServerRegistry._parse_servers' */
    PyObject *const_str_plain_get_countries;  /* [168] str = 'get_countries' */
    PyObject *const_str_digest_f3bd9c5e;  /* [169] str = 'ProviderServerRegistry.get_countries' */
    PyObject *const_str_plain_protocol;  /* [170] str = 'protocol' */
    PyObject *const_str_digest_7f4ffab6;  /* [171] str = 'ProviderServerRegistry.get_servers' */
    PyObject *const_tuple_3_2;  /* [172] tuple = (None, 1, None) */
    PyObject *const_str_plain_get_random_servers;  /* [173] str = 'get_random_servers' */
    PyObject *const_str_digest_ca244714;  /* [174] str = 'ProviderServerRegistry.get_random_servers' */
    PyObject *const_tuple_1_14;  /* [175] tuple = ('wireguard',) */
    PyObject *const_dict_3;  /* [176] dict = {'provider': 'str', 'vpn': 'str', 'return': 'bool'} */
    PyObject *const_str_plain_has_vpn_type;  /* [177] str = 'has_vpn_type' */
    PyObject *const_str_digest_3b1c7da8;  /* [178] str = 'ProviderServerRegistry.has_vpn_type' */
    PyObject *const_tuple_5;  /* [179] tuple = (None, 1, 'wireguard', None, None) */
    PyObject *const_tuple_2_15;  /* [180] tuple = ('str', 'int') */
    PyObject *const_str_plain_exclude_ips;  /* [181] str = 'exclude_ips' */
    PyObject *const_str_plain_select_servers;  /* [182] str = 'select_servers' */
    PyObject *const_str_digest_9e6fd5f9;  /* [183] str = 'ProviderServerRegistry.select_servers' */
    PyObject *const_dict_1_1;  /* [184] dict = {'provider': 'str'} */
    PyObject *const_str_plain_refresh_cache;  /* [185] str = 'refresh_cache' */
    PyObject *const_str_digest_79b9011d;  /* [186] str = 'ProviderServerRegistry.refresh_cache' */
    PyObject *const_str_digest_4b84da2c;  /* [187] str = 'core\\provider_servers.py' */
    PyObject *const_tuple_3_3;  /* [188] tuple = ('.0', 's', 'vpn') */
    PyObject *const_tuple_3_4;  /* [189] tuple = ('.0', 'c', 'ip') */
    PyObject *const_tuple_1_15;  /* [190] tuple = ('x',) */
    PyObject *const_tuple_2_16;  /* [191] tuple = ('s', 'server_usage') */
    PyObject *const_tuple_1_16;  /* [192] tuple = ('server_usage',) */
    PyObject *const_str_digest_db14aa97;  /* [193] str = '<module core.provider_servers>' */
    PyObject *const_tuple_1_17;  /* [194] tuple = ('__class__',) */
    PyObject *const_tuple_2_17;  /* [195] tuple = ('self', 'cache_dir') */
    PyObject *const_tuple_8;  /* [196] tuple = ('self', 'provider', 'url', 'r', 'data', 'cache_path', 'f', ... */
    PyObject *const_tuple_2_18;  /* [197] tuple = ('self', 'provider') */
    PyObject *const_tuple_7;  /* [198] tuple = ('self', 'provider', 'cache_path', 'f', 'data', 'ts', 'e') */
    PyObject *const_tuple_14;  /* [199] tuple = ('self', 'provider', 'data', 'raw_servers', 'parsed', 'versi... */
    PyObject *const_tuple_11;  /* [200] tuple = ('self', 'provider', 'vpn', 'servers', 'vpn_clean', 'country... */
    PyObject *const_tuple_6;  /* [201] tuple = ('self', 'provider', 'country', 'count', 'vpn', 'servers') */
    PyObject *const_tuple_7_1;  /* [202] tuple = ('self', 'provider', 'country', 'vpn', 'protocol', 'servers'... */
    PyObject *const_tuple_4;  /* [203] tuple = ('self', 'provider', 'vpn', 'servers') */
    PyObject *const_tuple_4_1;  /* [204] tuple = ('self', 'provider', 'prov', 'e') */
    PyObject *const_tuple_23;  /* [205] tuple = ('self', 'provider', 'country', 'count', 'vpn', 'server_usag... */
    PyObject *const_tuple_3_5;  /* [206] tuple = ('s', 'ip', 'server_usage') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.provider_servers"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0___cache;   /* '_cache' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__json;   /* 'json' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__vpn;   /* 'vpn' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__wgpubkey;   /* 'wgpubkey' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__wireguard;   /* 'wireguard' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__upper;   /* 'upper' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__upper;   /* 'upper' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__get_servers;   /* 'get_servers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__min;   /* 'min' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__target_ip;   /* 'target_ip' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__target_ip;   /* 'target_ip' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__server_usage;   /* 'server_usage' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__pathlib;   /* 'pathlib' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__getLogger;   /* 'getLogger' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_14__get_random_servers;   /* 'get_random_servers' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_15__exclude_ips;   /* 'exclude_ips' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_16__refresh_cache;   /* 'refresh_cache' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_17__refresh_cache;   /* 'refresh_cache' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_18__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_19__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_20__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_21__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_22__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_23__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_24__provider_servers$gt$;   /* 'provider_servers>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def _cache(parents, exist_ok)
 *  qualname: .json   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$_cache(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def json(timeout)
 *  qualname: json   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$json(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def vpn(vpn, openvpn)
 *  qualname: vpn   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$vpn(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def wgpubkey(wgpubkey)
 *  qualname: wgpubkey   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$wgpubkey(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def wireguard(vpn)
 *  qualname: wireguard   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$wireguard(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def upper(key)
 *  qualname: <lambda>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$upper(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def upper(tcp)
 *  qualname: <lambda>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$upper(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def get_servers(udp)
 *  qualname: get_servers   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$get_servers(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def min(country, vpn, protocol)
 *  qualname: <genexpr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$min(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def target_ip(country, vpn)
 *  qualname: <genexpr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$target_ip(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def target_ip(hostname)
 *  qualname: <genexpr>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$target_ip(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def server_usage(ips)
 *  qualname: server_usage   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$server_usage(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pathlib(Path)
 *  qualname: urllib.request   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$pathlib(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def getLogger(urlopen)
 *  qualname: urllib.request   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$getLogger(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(x)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(s, server_usage)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(server_usage)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(__class__)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(self, cache_dir)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(self, provider, url, r, data, cache_path, f, e)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def provider_servers>(self, provider)
 *  qualname: <module core.provider_servers>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* Class: ProviderServerRegistry
 *   methods recovered: 4
 *   class body was also compiled to native code */
static PyObject *impl_core$provider_servers$ProviderServerRegistry$get_random_servers(PyThreadState *tstate, PyObject **python_pars);  /* def ProviderServerRegistry.get_random_servers(wireguard) line 0 */
static PyObject *impl_core$provider_servers$ProviderServerRegistry$exclude_ips(PyThreadState *tstate, PyObject **python_pars);  /* def ProviderServerRegistry.exclude_ips(str, int) line 0 */
static PyObject *impl_core$provider_servers$ProviderServerRegistry$refresh_cache(PyThreadState *tstate, PyObject **python_pars);  /* def ProviderServerRegistry.refresh_cache(.0, s, vpn) line 0 */
static PyObject *impl_core$provider_servers$ProviderServerRegistry$refresh_cache(PyThreadState *tstate, PyObject **python_pars);  /* def ProviderServerRegistry.refresh_cache(.0, c, ip) line 0 */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$provider_servers$_cache(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _cache(parents, exist_ok): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$json(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def json(timeout): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$vpn(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def vpn(vpn, openvpn): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$wgpubkey(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def wgpubkey(wgpubkey): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$wireguard(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def wireguard(vpn): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$upper(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def upper(key): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$upper(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def upper(tcp): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$get_servers(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def get_servers(udp): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$min(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def min(country, vpn, protocol): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$target_ip(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def target_ip(country, vpn): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$target_ip(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def target_ip(hostname): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$server_usage(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def server_usage(ips): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$pathlib(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pathlib(Path): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$getLogger(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def getLogger(urlopen): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(x): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(s, server_usage): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(server_usage): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(self, cache_dir): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(self, provider, url, r, data, cache_path, f, e): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$provider_servers$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def provider_servers>(self, provider): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$ProviderServerRegistry$get_random_servers(PyThreadState *tstate, PyObject **python_pars) {
    /* def ProviderServerRegistry.get_random_servers(wireguard): ... */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$ProviderServerRegistry$exclude_ips(PyThreadState *tstate, PyObject **python_pars) {
    /* def ProviderServerRegistry.exclude_ips(str, int): ... */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$ProviderServerRegistry$refresh_cache(PyThreadState *tstate, PyObject **python_pars) {
    /* def ProviderServerRegistry.refresh_cache(.0, s, vpn): ... */
    Py_RETURN_NONE;
}

static PyObject *impl_core$provider_servers$ProviderServerRegistry$refresh_cache(PyThreadState *tstate, PyObject **python_pars) {
    /* def ProviderServerRegistry.refresh_cache(.0, c, ip): ... */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$provider_servers(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$provider_servers = module;
    moduledict_core$provider_servers = MODULE_DICT(module_core$provider_servers);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141A07C60
     *
     * Recovered imports (detected from module constants): */
    /*   import 0.0.0.0 */
    /*   import urllib.request */
    /*   import core.provider_servers */
    /*   import ProviderServerRegistry.__init__ */
    /*   import ProviderServerRegistry._get_cache_path */
    /*   import ProviderServerRegistry._fetch_from_gluetun */
    /*   import ProviderServerRegistry._load_or_fetch */
    /*   import ProviderServerRegistry._parse_servers */
    /*   import ProviderServerRegistry.get_countries */
    /*   import ProviderServerRegistry.get_servers */
    /*   import ProviderServerRegistry.get_random_servers */
    /*   import ProviderServerRegistry.has_vpn_type */
    /*   import ProviderServerRegistry.select_servers */
    /*   import ProviderServerRegistry.refresh_cache */

    return module;
}

