/* Reconstructed C source for Python module 'core.settings'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$settings @ 0x141A18DA0
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$settings;
PyDictObject *moduledict_core$settings;

/* Module constants: 152 entries recovered from blob chunk 'core.settings'. */
static struct ModuleConstants {
    PyObject *const_str_plain_frozen;  /* [0] str = 'frozen' */
    PyObject *const_str_plain_Path;  /* [1] str = 'Path' */
    PyObject *const_str_plain_executable;  /* [2] str = 'executable' */
    PyObject *const_str_plain_resolve;  /* [3] str = 'resolve' */
    PyObject *const_str_plain_data;  /* [4] str = 'data' */
    PyObject *const_str_plain_mkdir;  /* [5] str = 'mkdir' */
    PyObject *const_tuple_2;  /* [6] tuple = (True, True) */
    PyObject *const_tuple_2_1;  /* [7] tuple = ('parents', 'exist_ok') */
    PyObject *const_str_digest_0327376b;  /* [8] str = 'Lấy thư mục data bền vững (nơi chứa settings.json, db.json,... */
    PyObject *const_str_digest_5bc02cef;  /* [9] str = 'main.py' */
    PyObject *const_str_digest_ccf6f3c9;  /* [10] str = 'Lấy đường dẫn tới main executable/script' */
    PyObject *const_str_plain_get_data_dir;  /* [11] str = 'get_data_dir' */
    PyObject *const_str_plain_data_dir;  /* [12] str = 'data_dir' */
    PyObject *const_str_digest_9f423fca;  /* [13] str = 'settings.json' */
    PyObject *const_str_plain_settings_file;  /* [14] str = 'settings_file' */
    PyObject *const_str_plain_shutil;  /* [15] str = 'shutil' */
    PyObject *const_str_plain_copy2;  /* [16] str = 'copy2' */
    PyObject *const_str_plain_logger;  /* [17] str = 'logger' */
    PyObject *const_str_plain_info;  /* [18] str = 'info' */
    PyObject *const_tuple_1;  /* [19] tuple = ('📦 [Auto-Migration] Đã di chuyển settings.json vào thư mục ... */
    PyObject *const_str_plain_warning;  /* [20] str = 'warning' */
    PyObject *const_str_digest_6eb1cb3a;  /* [21] str = 'Lỗi di chuyển settings.json cũ: ' */
    PyObject *const_str_plain__load;  /* [22] str = '_load' */
    PyObject *const_str_plain__settings;  /* [23] str = '_settings' */
    PyObject *const_str_digest_e9e2aa81;  /* [24] str = 'utf-8' */
    PyObject *const_str_plain_json;  /* [25] str = 'json' */
    PyObject *const_str_plain_load;  /* [26] str = 'load' */
    PyObject *const_str_plain_DEFAULT_SETTINGS;  /* [27] str = 'DEFAULT_SETTINGS' */
    PyObject *const_str_plain_copy;  /* [28] str = 'copy' */
    PyObject *const_str_plain_update;  /* [29] str = 'update' */
    PyObject *const_tuple_3;  /* [30] tuple = (None, None, None) */
    PyObject *const_str_digest_267abd5c;  /* [31] str = 'Không thể đọc settings.json: ' */
    PyObject *const_str_digest_12111cf8;  /* [32] str = 'Đọc settings từ file' */
    PyObject *const_str_plain_dump;  /* [33] str = 'dump' */
    PyObject *const_tuple_2_2;  /* [34] tuple = (2, False) */
    PyObject *const_tuple_2_3;  /* [35] tuple = ('indent', 'ensure_ascii') */
    PyObject *const_str_digest_c21e98a9;  /* [36] str = 'Đã lưu settings → ' */
    PyObject *const_str_plain_error;  /* [37] str = 'error' */
    PyObject *const_str_digest_a8da14b8;  /* [38] str = 'Lỗi ghi settings.json: ' */
    PyObject *const_str_digest_6344e2db;  /* [39] str = 'Ghi settings ra file' */
    PyObject *const_str_plain_port;  /* [40] str = 'port' */
    PyObject *const_str_plain__save;  /* [41] str = '_save' */
    PyObject *const_str_plain_auto_startup;  /* [42] str = 'auto_startup' */
    PyObject *const_str_plain__apply_auto_startup;  /* [43] str = '_apply_auto_startup' */
    PyObject *const_str_digest_d83d45a5;  /* [44] str = 'Lấy toàn bộ settings' */
    PyObject *const_str_plain_items;  /* [45] str = 'items' */
    PyObject *const_str_plain_self;  /* [46] str = 'self' */
    PyObject *const_str_plain_changed;  /* [47] str = 'changed' */
    PyObject *const_str_digest_77a26977;  /* [48] str = 'Cập nhật settings và áp dụng' */
    PyObject *const_str_plain__register_scheduled_task;  /* [49] str = '_register_scheduled_task' */
    PyObject *const_str_plain__unregister_scheduled_task;  /* [50] str = '_unregister_scheduled_task' */
    PyObject *const_str_digest_216465f1;  /* [51] str = 'Bật/tắt auto-start thông qua Windows Task Scheduler' */
    PyObject *const_str_plain_windll;  /* [52] str = 'windll' */
    PyObject *const_str_plain_shell32;  /* [53] str = 'shell32' */
    PyObject *const_str_plain_IsUserAnAdmin;  /* [54] str = 'IsUserAnAdmin' */
    PyObject *const_str_digest_f9e3485d;  /* [55] str = 'Kiểm tra process hiện tại có đang chạy quyền Admin không' */
    PyObject *const_str_digest_21e21be8;  /* [56] str = "-Argument '--autostart'" */
    PyObject *const_str_digest_0cd11e01;  /* [57] str = '-Argument \'"' */
    PyObject *const_str_digest_42a83852;  /* [58] str = '" --autostart\'' */
    PyObject *const_str_digest_3709c08a;  /* [59] str = "\n        $user = [System.Security.Principal.WindowsIdentit... */
    PyObject *const_str_digest_f21ef7c0;  /* [60] str = "' " */
    PyObject *const_str_digest_20224eac;  /* [61] str = " -WorkingDirectory '" */
    PyObject *const_str_digest_26d86b27;  /* [62] str = '\'\n        $trigger = New-ScheduledTaskTrigger -AtLogOn\n ... */
    PyObject *const_str_plain_subprocess;  /* [63] str = 'subprocess' */
    PyObject *const_str_plain_run;  /* [64] str = 'run' */
    PyObject *const_str_plain_powershell;  /* [65] str = 'powershell' */
    PyObject *const_str_digest_4089c192;  /* [66] str = '-NoProfile' */
    PyObject *const_str_digest_99496c03;  /* [67] str = '-NonInteractive' */
    PyObject *const_str_digest_0bc69e2a;  /* [68] str = '-Command' */
    PyObject *const_tuple_4;  /* [69] tuple = (True, True, 30, 134217728) */
    PyObject *const_tuple_4_1;  /* [70] tuple = ('capture_output', 'text', 'timeout', 'creationflags') */
    PyObject *const_str_plain_returncode;  /* [71] str = 'returncode' */
    PyObject *const_str_digest_802b201e;  /* [72] str = '✅ Đã đăng ký auto-start (Task Scheduler: OCProxyManager, Wo... */
    PyObject *const_str_digest_9371d7a2;  /* [73] str = ')' */
    PyObject *const_str_digest_dbd58669;  /* [74] str = '⚠️  Lỗi đăng ký auto-start: ' */
    PyObject *const_str_plain_stderr;  /* [75] str = 'stderr' */
    PyObject *const_str_plain_strip;  /* [76] str = 'strip' */
    PyObject *const_str_digest_d3d92780;  /* [77] str = 'Lỗi khi đăng ký auto-start: ' */
    PyObject *const_str_digest_cc5e2af1;  /* [78] str = 'Tạo Task Scheduler để chạy app khi người dùng đăng nhập với... */
    PyObject *const_int_digest_9ab98b1f;  /* [79] int = 134217728 */
    PyObject *const_tuple_2_4;  /* [80] tuple = ('OCProxyManager', 'PIAProxyManager') */
    PyObject *const_str_digest_55671381;  /* [81] str = "Unregister-ScheduledTask -TaskName '" */
    PyObject *const_str_digest_f2b745cc;  /* [82] str = "' -Confirm:$false -ErrorAction SilentlyContinue" */
    PyObject *const_int_pos_15;  /* [83] int = 15 */
    PyObject *const_str_plain_no_window;  /* [84] str = 'no_window' */
    PyObject *const_str_digest_89ec2eaa;  /* [85] str = '✅ Đã xóa auto-start (Task Scheduler: ' */
    PyObject *const_str_digest_9de01ba6;  /* [86] str = 'Lỗi khi xóa auto-start ' */
    PyObject *const_str_digest_e2654927;  /* [87] str = ': ' */
    PyObject *const_str_digest_20a0dfce;  /* [88] str = 'Xóa Task Scheduler (xóa cả tên cũ PIAProxyManager lẫn tên m... */
    PyObject *const_tuple_5;  /* [89] tuple = (['powershell', '-NoProfile', '-NonInteractive', '-Command',... */
    PyObject *const_str_plain_stdout;  /* [90] str = 'stdout' */
    PyObject *const_tuple_2_5;  /* [91] tuple = ('Ready', 'Running') */
    PyObject *const_str_digest_6f881b91;  /* [92] str = 'Kiểm tra Task Scheduler đã đăng ký chưa (check cả tên mới O... */
    PyObject *const_str_digest_5e44119c;  /* [93] str = '\nSettings Manager for PIA Proxy Manager v2\n\nQuản lý sett... */
    PyObject *const_str_plain_origin;  /* [94] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [95] str = 'has_location' */
    PyObject *const_str_plain_logging;  /* [96] str = 'logging' */
    PyObject *const_str_plain_os;  /* [97] str = 'os' */
    PyObject *const_str_plain_sys;  /* [98] str = 'sys' */
    PyObject *const_str_plain_pathlib;  /* [99] str = 'pathlib' */
    PyObject *const_tuple_1_1;  /* [100] tuple = ('Path',) */
    PyObject *const_str_plain_Optional;  /* [101] str = 'Optional' */
    PyObject *const_str_plain_getLogger;  /* [102] str = 'getLogger' */
    PyObject *const_tuple_1_2;  /* [103] tuple = ('core.settings',) */
    PyObject *const_dict_2;  /* [104] dict = {'port': 8000, 'auto_startup': False} */
    PyObject *const_str_plain_return;  /* [105] str = 'return' */
    PyObject *const_dict_1;  /* [106] dict = {'return': 'str'} */
    PyObject *const_str_plain_get_exe_path;  /* [107] str = 'get_exe_path' */
    PyObject *const_str_digest_eb4dc22f;  /* [108] str = 'core.settings' */
    PyObject *const_str_digest_0b891467;  /* [109] str = 'Quản lý cài đặt hệ thống' */
    PyObject *const_str_plain_SettingsManager;  /* [110] str = 'SettingsManager' */
    PyObject *const_str_plain___qualname__;  /* [111] str = '__qualname__' */
    PyObject *const_tuple_1_3;  /* [112] tuple = (None,) */
    PyObject *const_str_digest_75ea32da;  /* [113] str = 'SettingsManager.__init__' */
    PyObject *const_dict_1_1;  /* [114] dict = {'return': 'dict'} */
    PyObject *const_str_digest_94fca737;  /* [115] str = 'SettingsManager._load' */
    PyObject *const_str_digest_97003b7d;  /* [116] str = 'SettingsManager._save' */
    PyObject *const_dict_1_2;  /* [117] dict = {'return': 'int'} */
    PyObject *const_str_digest_c6b22590;  /* [118] str = 'SettingsManager.port' */
    PyObject *const_str_plain_setter;  /* [119] str = 'setter' */
    PyObject *const_dict_1_3;  /* [120] dict = {'value': 'int'} */
    PyObject *const_dict_1_4;  /* [121] dict = {'return': 'bool'} */
    PyObject *const_str_digest_f91db65a;  /* [122] str = 'SettingsManager.auto_startup' */
    PyObject *const_dict_1_5;  /* [123] dict = {'value': 'bool'} */
    PyObject *const_str_plain_get_all;  /* [124] str = 'get_all' */
    PyObject *const_str_digest_c0d0a4c7;  /* [125] str = 'SettingsManager.get_all' */
    PyObject *const_dict_1_6;  /* [126] dict = {'new_settings': 'dict'} */
    PyObject *const_str_digest_7b43d916;  /* [127] str = 'SettingsManager.update' */
    PyObject *const_dict_1_7;  /* [128] dict = {'enable': 'bool'} */
    PyObject *const_str_digest_5f3ebf09;  /* [129] str = 'SettingsManager._apply_auto_startup' */
    PyObject *const_str_plain_is_admin;  /* [130] str = 'is_admin' */
    PyObject *const_str_digest_201d653c;  /* [131] str = 'SettingsManager.is_admin' */
    PyObject *const_str_digest_51283084;  /* [132] str = 'SettingsManager._register_scheduled_task' */
    PyObject *const_str_digest_65e4b9cb;  /* [133] str = 'SettingsManager._unregister_scheduled_task' */
    PyObject *const_str_plain_is_task_registered;  /* [134] str = 'is_task_registered' */
    PyObject *const_str_digest_88276a87;  /* [135] str = 'SettingsManager.is_task_registered' */
    PyObject *const_str_plain_settings_mgr;  /* [136] str = 'settings_mgr' */
    PyObject *const_str_digest_6c04b2be;  /* [137] str = 'core\\settings.py' */
    PyObject *const_str_digest_a197062c;  /* [138] str = '<module core.settings>' */
    PyObject *const_tuple_1_4;  /* [139] tuple = ('__class__',) */
    PyObject *const_tuple_5_1;  /* [140] tuple = ('self', 'data_dir', 'legacy_file', 'shutil', 'me') */
    PyObject *const_tuple_2_6;  /* [141] tuple = ('self', 'enable') */
    PyObject *const_tuple_5_2;  /* [142] tuple = ('self', 'f', 'data', 'merged', 'e') */
    PyObject *const_tuple_10;  /* [143] tuple = ('self', 'task_name', 'exe_path', 'arg_part', 'work_dir', 'm... */
    PyObject *const_tuple_3_1;  /* [144] tuple = ('self', 'f', 'e') */
    PyObject *const_tuple_5_3;  /* [145] tuple = ('self', 'no_window', 'task_name', 'result', 'e') */
    PyObject *const_tuple_1_5;  /* [146] tuple = ('self',) */
    PyObject *const_tuple_2_7;  /* [147] tuple = ('self', 'value') */
    PyObject *const_tuple_2_8;  /* [148] tuple = ('base_dir', 'data_dir') */
    PyObject *const_tuple_1_6;  /* [149] tuple = ('ctypes',) */
    PyObject *const_tuple_3_2;  /* [150] tuple = ('no_window', 'result', 'state') */
    PyObject *const_tuple_5_4;  /* [151] tuple = ('self', 'new_settings', 'changed', 'key', 'value') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.settings"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__mkdir;   /* 'mkdir' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__dump;   /* 'dump' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__returncode;   /* 'returncode' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__strip;   /* 'strip' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__stdout;   /* 'stdout' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__pathlib;   /* 'pathlib' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6__settings_mgr;   /* 'settings_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__settings_mgr;   /* 'settings_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__settings$gt$;   /* 'settings>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__settings$gt$;   /* 'settings>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def mkdir(parents, exist_ok)
 *  qualname: mkdir   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$mkdir(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def dump(indent, ensure_ascii)
 *  qualname: dump   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$dump(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def returncode(capture_output, text, timeout, creationflags)
 *  qualname: returncode   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$returncode(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def strip(OCProxyManager, PIAProxyManager)
 *  qualname: strip   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$strip(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def stdout(Ready, Running)
 *  qualname: stdout   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$stdout(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pathlib(Path)
 *  qualname: pathlib   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$pathlib(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def settings_mgr(__class__)
 *  qualname: <module core.settings>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$settings_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def settings_mgr(self, data_dir, legacy_file, shutil, me)
 *  qualname: <module core.settings>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$settings_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def settings>(self, enable)
 *  qualname: <module core.settings>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$settings$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def settings>(self, f, data, merged, e)
 *  qualname: <module core.settings>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$settings$settings$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$settings$mkdir(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def mkdir(parents, exist_ok): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$dump(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def dump(indent, ensure_ascii): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$returncode(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def returncode(capture_output, text, timeout, creationflags): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$strip(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def strip(OCProxyManager, PIAProxyManager): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$stdout(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def stdout(Ready, Running): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$pathlib(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pathlib(Path): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$settings_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def settings_mgr(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$settings_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def settings_mgr(self, data_dir, legacy_file, shutil, me): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$settings$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def settings>(self, enable): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$settings$settings$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def settings>(self, f, data, merged, e): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$settings(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$settings = module;
    moduledict_core$settings = MODULE_DICT(module_core$settings);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141A18DA0
     *
     * Recovered imports (detected from module constants): */
    /*   import main.py */
    /*   import settings.json */
    /*   import core.settings */
    /*   import SettingsManager.__init__ */
    /*   import SettingsManager._load */
    /*   import SettingsManager._save */
    /*   import SettingsManager.port */
    /*   import SettingsManager.auto_startup */
    /*   import SettingsManager.get_all */
    /*   import SettingsManager.update */
    /*   import SettingsManager._apply_auto_startup */
    /*   import SettingsManager.is_admin */
    /*   import SettingsManager._register_scheduled_task */
    /*   import SettingsManager._unregister_scheduled_task */
    /*   import SettingsManager.is_task_registered */

    return module;
}

