/* Reconstructed C source for Python module 'core.tray_icon'
 * Recovered by Nuitka Static Unpacker v7.3 from compiled binary metadata.
 *
 * Original C was generated by Nuitka but is not stored in the binary.
 * This reconstruction applies the same Nuitka code-generation templates
 * to the metadata we recovered from the constants blob.
 *
 * STRUCTURAL PARTS (match what Nuitka produced):
 *   - Module constants table (every constant byte-identical)
 *   - Code object declarations (names, line numbers, arg names)
 *   - Function signature declarations
 *   - Module-initialization entry point
 *
 * LOST (compiled directly to native instructions by Nuitka):
 *   - Function bodies — translated through Nuitka IR to C operations
 *     to x86-64/ARM assembly. Original Python statements cannot be
 *     reconstructed without disassembling the native code around the
 *     module_init_func pointer.
 *
 * NATIVE ENTRY POINT: module_code_core$tray_icon @ 0x141A4D0F0
 * Flags: TRANSLATED
 * Is package: False
 */

#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "__helpers.h"

/* The module object (Python-visible) */
PyObject *module_core$tray_icon;
PyDictObject *moduledict_core$tray_icon;

/* Module constants: 172 entries recovered from blob chunk 'core.tray_icon'. */
static struct ModuleConstants {
    PyObject *const_str_plain_frozen;  /* [0] str = 'frozen' */
    PyObject *const_str_plain_Path;  /* [1] str = 'Path' */
    PyObject *const_str_plain_executable;  /* [2] str = 'executable' */
    PyObject *const_str_plain_static;  /* [3] str = 'static' */
    PyObject *const_str_digest_7e804ee5;  /* [4] str = 'logo.ico' */
    PyObject *const_str_digest_1bb87d41;  /* [5] str = 'logo.png' */
    PyObject *const_str_plain_getcwd;  /* [6] str = 'getcwd' */
    PyObject *const_str_plain_Image;  /* [7] str = 'Image' */
    PyObject *const_str_plain_convert;  /* [8] str = 'convert' */
    PyObject *const_tuple_1;  /* [9] tuple = ('RGBA',) */
    PyObject *const_str_plain_resize;  /* [10] str = 'resize' */
    PyObject *const_tuple_2;  /* [11] tuple = (64, 64) */
    PyObject *const_str_plain_LANCZOS;  /* [12] str = 'LANCZOS' */
    PyObject *const_str_plain_logger;  /* [13] str = 'logger' */
    PyObject *const_str_plain_debug;  /* [14] str = 'debug' */
    PyObject *const_str_digest_558bc364;  /* [15] str = 'Tray icon loaded from: ' */
    PyObject *const_str_plain_warning;  /* [16] str = 'warning' */
    PyObject *const_str_digest_70af72b6;  /* [17] str = 'Không thể load tray icon từ ' */
    PyObject *const_str_digest_e2654927;  /* [18] str = ': ' */
    PyObject *const_tuple_1_1;  /* [19] tuple = ('Không tìm thấy logo icon, dùng icon mặc định',) */
    PyObject *const_str_plain_new;  /* [20] str = 'new' */
    PyObject *const_tuple_3;  /* [21] tuple = ('RGBA', (64, 64), (0, 0, 0, 0)) */
    PyObject *const_str_plain_ImageDraw;  /* [22] str = 'ImageDraw' */
    PyObject *const_str_plain_Draw;  /* [23] str = 'Draw' */
    PyObject *const_str_plain_polygon;  /* [24] str = 'polygon' */
    PyObject *const_tuple_3_1;  /* [25] tuple = ([(32, 4), (56, 12), (56, 38), (32, 56), (8, 38), (8, 12)], ... */
    PyObject *const_tuple_2_1;  /* [26] tuple = ('fill', 'outline') */
    PyObject *const_str_plain_text;  /* [27] str = 'text' */
    PyObject *const_tuple_3_2;  /* [28] tuple = ((19, 18), 'O', 'white') */
    PyObject *const_tuple_1_2;  /* [29] tuple = ('fill',) */
    PyObject *const_str_digest_55bb5495;  /* [30] str = 'Load logo.ico hoặc logo.png làm tray icon. Fallback về icon... */
    PyObject *const_str_plain_port;  /* [31] str = 'port' */
    PyObject *const_str_plain_threading;  /* [32] str = 'threading' */
    PyObject *const_str_plain_Event;  /* [33] str = 'Event' */
    PyObject *const_str_plain_stop_event;  /* [34] str = 'stop_event' */
    PyObject *const_str_plain_icon;  /* [35] str = 'icon' */
    PyObject *const_str_plain__restart_flag;  /* [36] str = '_restart_flag' */
    PyObject *const_str_digest_eb4dc22f;  /* [37] str = 'core.settings' */
    PyObject *const_tuple_1_3;  /* [38] tuple = ('settings_mgr',) */
    PyObject *const_str_plain_settings_mgr;  /* [39] str = 'settings_mgr' */
    PyObject *const_str_digest_52c5287a;  /* [40] str = 'http://localhost:' */
    PyObject *const_str_plain__get_dashboard_url;  /* [41] str = '_get_dashboard_url' */
    PyObject *const_str_plain_startswith;  /* [42] str = 'startswith' */
    PyObject *const_tuple_1_4;  /* [43] tuple = ('#',) */
    PyObject *const_str_digest_f1146534;  /* [44] str = '/#' */
    PyObject *const_str_plain_startfile;  /* [45] str = 'startfile' */
    PyObject *const_str_digest_0ac8c2f1;  /* [46] str = 'Không thể mở browser: ' */
    PyObject *const_str_digest_a95a464a;  /* [47] str = 'Mở dashboard trong browser' */
    PyObject *const_str_plain__open_browser;  /* [48] str = '_open_browser' */
    PyObject *const_tuple_1_5;  /* [49] tuple = ('tab-settings',) */
    PyObject *const_str_digest_02eb0baf;  /* [50] str = 'Mở tab settings trên Web Dashboard' */
    PyObject *const_str_plain_info;  /* [51] str = 'info' */
    PyObject *const_tuple_1_6;  /* [52] tuple = ('🔄 Restart requested from tray menu',) */
    PyObject *const_str_plain_set;  /* [53] str = 'set' */
    PyObject *const_str_plain_stop;  /* [54] str = 'stop' */
    PyObject *const_str_plain__do_restart;  /* [55] str = '_do_restart' */
    PyObject *const_str_digest_8360c45c;  /* [56] str = 'TrayIcon._on_restart.<locals>._do_restart' */
    PyObject *const_str_plain_Thread;  /* [57] str = 'Thread' */
    PyObject *const_tuple_2_2;  /* [58] tuple = ('target', 'daemon') */
    PyObject *const_str_plain_start;  /* [59] str = 'start' */
    PyObject *const_str_plain_time;  /* [60] str = 'time' */
    PyObject *const_str_plain_sleep;  /* [61] str = 'sleep' */
    PyObject *const_tuple_1_7;  /* [62] tuple = (0.5,) */
    PyObject *const_str_plain_subprocess;  /* [63] str = 'subprocess' */
    PyObject *const_str_plain_Popen;  /* [64] str = 'Popen' */
    PyObject *const_str_plain_argv;  /* [65] str = 'argv' */
    PyObject *const_tuple_4;  /* [66] tuple = ('slice', 1, None, None) */
    PyObject *const_str_plain_error;  /* [67] str = 'error' */
    PyObject *const_str_digest_9ca8d853;  /* [68] str = 'Lỗi khi restart process: ' */
    PyObject *const_tuple_1_8;  /* [69] tuple = (0.3,) */
    PyObject *const_str_plain__exit;  /* [70] str = '_exit' */
    PyObject *const_tuple_1_9;  /* [71] tuple = (0,) */
    PyObject *const_tuple_1_10;  /* [72] tuple = ('🛑 Exit requested from tray menu',) */
    PyObject *const_str_plain_main;  /* [73] str = 'main' */
    PyObject *const_tuple_1_11;  /* [74] tuple = ('close_browser_app',) */
    PyObject *const_str_plain_close_browser_app;  /* [75] str = 'close_browser_app' */
    PyObject *const_str_plain__force_exit;  /* [76] str = '_force_exit' */
    PyObject *const_str_digest_8ad0165e;  /* [77] str = 'TrayIcon._on_exit.<locals>._force_exit' */
    PyObject *const_tuple_1_12;  /* [78] tuple = (1.0,) */
    PyObject *const_tuple_1_13;  /* [79] tuple = ('🛑 Force exiting process...',) */
    PyObject *const_str_plain_notify;  /* [80] str = 'notify' */
    PyObject *const_str_digest_a44e68e2;  /* [81] str = 'Server running on port ' */
    PyObject *const_str_digest_cf1f3e5c;  /* [82] str = '\n🚀 Dashboard: http://localhost:' */
    PyObject *const_str_digest_c8d36d26;  /* [83] str = 'OCProxy Manager' */
    PyObject *const_str_digest_395c3d44;  /* [84] str = 'Phát thông báo Toast nhẹ nhàng khi ứng dụng khởi động' */
    PyObject *const_str_plain_pystray;  /* [85] str = 'pystray' */
    PyObject *const_str_plain_Menu;  /* [86] str = 'Menu' */
    PyObject *const_str_plain_MenuItem;  /* [87] str = 'MenuItem' */
    PyObject *const_str_digest_ff619452;  /* [88] str = '📊 Open Dashboard' */
    PyObject *const_str_plain__on_open;  /* [89] str = '_on_open' */
    PyObject *const_tuple_1_14;  /* [90] tuple = (True,) */
    PyObject *const_tuple_1_15;  /* [91] tuple = ('default',) */
    PyObject *const_str_digest_50544271;  /* [92] str = '⚙️ Settings' */
    PyObject *const_str_plain__on_settings;  /* [93] str = '_on_settings' */
    PyObject *const_str_plain_SEPARATOR;  /* [94] str = 'SEPARATOR' */
    PyObject *const_str_digest_c4c6d160;  /* [95] str = '🔄 Restart' */
    PyObject *const_str_plain__on_restart;  /* [96] str = '_on_restart' */
    PyObject *const_str_digest_8f114c68;  /* [97] str = '🚪 Exit' */
    PyObject *const_str_plain__on_exit;  /* [98] str = '_on_exit' */
    PyObject *const_str_plain__create_icon;  /* [99] str = '_create_icon' */
    PyObject *const_str_plain_Icon;  /* [100] str = 'Icon' */
    PyObject *const_str_plain_OCProxyManager;  /* [101] str = 'OCProxyManager' */
    PyObject *const_str_digest_8d46173a;  /* [102] str = 'OCProxy Manager (:' */
    PyObject *const_str_digest_9371d7a2;  /* [103] str = ')' */
    PyObject *const_str_plain__setup_menu;  /* [104] str = '_setup_menu' */
    PyObject *const_str_plain__on_show_notification;  /* [105] str = '_on_show_notification' */
    PyObject *const_str_plain_run;  /* [106] str = 'run' */
    PyObject *const_str_digest_9fa566bd;  /* [107] str = 'Chạy tray icon loop (blocking)' */
    PyObject *const_str_digest_a002aeae;  /* [108] str = 'Chủ động hiển thị thông báo Toast trên khay hệ thống Window... */
    PyObject *const_str_plain_TrayIcon;  /* [109] str = 'TrayIcon' */
    PyObject *const_tuple_2_3;  /* [110] tuple = ('port', 'server_stop_event') */
    PyObject *const_str_digest_273f6829;  /* [111] str = '\n    Khởi động tray icon trong thread riêng\n    \n    Arg... */
    PyObject *const_str_digest_bac59909;  /* [112] str = '\nSystem Tray Icon for PIA Proxy Manager v2\n\nKhi app star... */
    PyObject *const_str_plain_origin;  /* [113] str = 'origin' */
    PyObject *const_str_plain_has_location;  /* [114] str = 'has_location' */
    PyObject *const_str_plain_io;  /* [115] str = 'io' */
    PyObject *const_str_plain_logging;  /* [116] str = 'logging' */
    PyObject *const_str_plain_os;  /* [117] str = 'os' */
    PyObject *const_str_plain_sys;  /* [118] str = 'sys' */
    PyObject *const_str_plain_pathlib;  /* [119] str = 'pathlib' */
    PyObject *const_tuple_1_16;  /* [120] tuple = ('Path',) */
    PyObject *const_str_plain_Optional;  /* [121] str = 'Optional' */
    PyObject *const_str_plain_ctypes;  /* [122] str = 'ctypes' */
    PyObject *const_str_plain_windll;  /* [123] str = 'windll' */
    PyObject *const_str_plain_shell32;  /* [124] str = 'shell32' */
    PyObject *const_str_plain_SetCurrentProcessExplicitAppUserModelID;  /* [125] str = 'SetCurrentProcessExplicitAppUserModelID' */
    PyObject *const_tuple_1_17;  /* [126] tuple = ('OCProxy Manager',) */
    PyObject *const_str_plain_PIL;  /* [127] str = 'PIL' */
    PyObject *const_tuple_2_4;  /* [128] tuple = ('Image', 'ImageDraw') */
    PyObject *const_str_plain_getLogger;  /* [129] str = 'getLogger' */
    PyObject *const_tuple_1_18;  /* [130] tuple = ('core.tray_icon',) */
    PyObject *const_str_plain_return;  /* [131] str = 'return' */
    PyObject *const_str_digest_d937ba29;  /* [132] str = 'core.tray_icon' */
    PyObject *const_str_digest_5cfbc081;  /* [133] str = '\n    Quản lý system tray icon\n    \n    Menu:\n    - Open... */
    PyObject *const_str_plain___qualname__;  /* [134] str = '__qualname__' */
    PyObject *const_tuple_2_5;  /* [135] tuple = (8000, None) */
    PyObject *const_str_plain_server_stop_event;  /* [136] str = 'server_stop_event' */
    PyObject *const_str_digest_5bc83c4d;  /* [137] str = 'TrayIcon.__init__' */
    PyObject *const_dict_1;  /* [138] dict = {'return': 'str'} */
    PyObject *const_str_digest_b880dfa3;  /* [139] str = 'TrayIcon._get_dashboard_url' */
    PyObject *const_tuple_1_19;  /* [140] tuple = ('',) */
    PyObject *const_dict_1_1;  /* [141] dict = {'tab_hash': 'str'} */
    PyObject *const_str_digest_fe82c431;  /* [142] str = 'TrayIcon._open_browser' */
    PyObject *const_str_plain_item;  /* [143] str = 'item' */
    PyObject *const_str_digest_1c320c8d;  /* [144] str = 'TrayIcon._on_open' */
    PyObject *const_str_digest_ae9ce897;  /* [145] str = 'TrayIcon._on_settings' */
    PyObject *const_str_digest_ef5fc74e;  /* [146] str = 'TrayIcon._on_restart' */
    PyObject *const_str_digest_40426d66;  /* [147] str = 'TrayIcon._on_exit' */
    PyObject *const_str_digest_518d2150;  /* [148] str = 'TrayIcon._on_show_notification' */
    PyObject *const_str_digest_716ffaaa;  /* [149] str = 'TrayIcon._setup_menu' */
    PyObject *const_str_digest_dbeb390c;  /* [150] str = 'TrayIcon.run' */
    PyObject *const_dict_2;  /* [151] dict = {'message': 'str', 'title': 'str'} */
    PyObject *const_str_digest_1680e7e9;  /* [152] str = 'TrayIcon.notify' */
    PyObject *const_dict_1_2;  /* [153] dict = {'return': 'bool'} */
    PyObject *const_str_plain_should_restart;  /* [154] str = 'should_restart' */
    PyObject *const_str_digest_1c0f7125;  /* [155] str = 'TrayIcon.should_restart' */
    PyObject *const_str_plain_start_tray;  /* [156] str = 'start_tray' */
    PyObject *const_str_digest_43d1de29;  /* [157] str = 'core\\tray_icon.py' */
    PyObject *const_str_digest_7056b8b6;  /* [158] str = '<module core.tray_icon>' */
    PyObject *const_tuple_1_20;  /* [159] tuple = ('__class__',) */
    PyObject *const_tuple_3_3;  /* [160] tuple = ('self', 'port', 'server_stop_event') */
    PyObject *const_tuple_8;  /* [161] tuple = ('candidates', 'base', 'path', 'img', 'e', 'size', 'draw', '... */
    PyObject *const_tuple_1_21;  /* [162] tuple = ('e',) */
    PyObject *const_tuple_3_4;  /* [163] tuple = ('self', 'settings_mgr', 'current_port') */
    PyObject *const_tuple_5;  /* [164] tuple = ('self', 'icon', 'item', 'close_browser_app', '_force_exit') */
    PyObject *const_tuple_3_5;  /* [165] tuple = ('self', 'icon', 'item') */
    PyObject *const_tuple_4_1;  /* [166] tuple = ('self', 'icon', 'item', '_do_restart') */
    PyObject *const_tuple_1_22;  /* [167] tuple = ('self',) */
    PyObject *const_tuple_5_1;  /* [168] tuple = ('self', 'tab_hash', 'url', 'subprocess', 'e') */
    PyObject *const_tuple_3_6;  /* [169] tuple = ('self', 'message', 'title') */
    PyObject *const_tuple_2_6;  /* [170] tuple = ('self', 'icon_image') */
    PyObject *const_tuple_4_2;  /* [171] tuple = ('port', 'server_stop_event', 'tray', 't') */
} mod_consts;

static PyObject *module_filename_obj = NULL;
static bool constants_created = false;

static void createModuleConstants(PyThreadState *tstate) {
    if (constants_created == false) {
        loadConstantsBlob(tstate, (PyObject **)&mod_consts, UN_TRANSLATE("core.tray_icon"));
        constants_created = true;
    }
}

/* Code objects declared for this module's functions. Nuitka
 * creates one PyCodeObject per function/class body, then wraps
 * them in Nuitka_Function objects via MAKE_FUNCTION_*. */
static PyCodeObject *codeobj_0__convert;   /* 'convert' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_1__text;   /* 'text' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_2__text;   /* 'text' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_3__settings_mgr;   /* 'settings_mgr' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_4__Thread;   /* 'Thread' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_5__main;   /* 'main' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_6___on_open;   /* '_on_open' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_7__TrayIcon;   /* 'TrayIcon' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_8__pathlib;   /* 'pathlib' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_9__PIL;   /* 'PIL' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_10__start_tray;   /* 'start_tray' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_11__start_tray;   /* 'start_tray' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_12__tray_icon$gt$;   /* 'tray_icon>' @ line 0  (inferred-from-constants) */
static PyCodeObject *codeobj_13__tray_icon$gt$;   /* 'tray_icon>' @ line 0  (inferred-from-constants) */


/* === Free function signatures =============================== */

/* Recovered Python signature:  def convert(RGBA)
 *  qualname: logo.png   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$convert(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def text(fill, outline)
 *  qualname: text   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$text(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def text(fill)
 *  qualname: text   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$text(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def settings_mgr(settings_mgr)
 *  qualname: core.settings   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$settings_mgr(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def Thread(target, daemon)
 *  qualname: TrayIcon._on_restart.<locals>._do_restart   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$Thread(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def main(close_browser_app)
 *  qualname: TrayIcon._on_exit.<locals>._force_exit   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$main(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def _on_open(default)
 *  qualname: _on_open   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$_on_open(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def TrayIcon(port, server_stop_event)
 *  qualname: TrayIcon   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$TrayIcon(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def pathlib(Path)
 *  qualname: pathlib   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$pathlib(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def PIL(Image, ImageDraw)
 *  qualname: core.tray_icon   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$PIL(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def start_tray(__class__)
 *  qualname: <module core.tray_icon>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$start_tray(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def start_tray(self, port, server_stop_event)
 *  qualname: <module core.tray_icon>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$start_tray(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def tray_icon>(candidates, base, path, img, e, size, draw, accent)
 *  qualname: <module core.tray_icon>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$tray_icon$gt$(PyThreadState *tstate, PyObject **python_pars);

/* Recovered Python signature:  def tray_icon>(e)
 *  qualname: <module core.tray_icon>   line: 0
 *  flags: 0x0
 *  body: compiled to native code — not recoverable here */
static PyObject *impl_core$tray_icon$tray_icon$gt$(PyThreadState *tstate, PyObject **python_pars);

/* === Class bodies ============================================ */

/* === Function body stubs =====================================
 *   All bodies are placeholders. The real implementations are
 *   at the machine-code level. See module_code_<name> below
 *   for the native entry point recovered from the PE. */

static PyObject *impl_core$tray_icon$convert(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def convert(RGBA): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$text(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def text(fill, outline): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$text(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def text(fill): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$settings_mgr(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def settings_mgr(settings_mgr): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$Thread(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def Thread(target, daemon): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$main(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def main(close_browser_app): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$_on_open(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def _on_open(default): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$TrayIcon(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def TrayIcon(port, server_stop_event): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$pathlib(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def pathlib(Path): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$PIL(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def PIL(Image, ImageDraw): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$start_tray(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def start_tray(__class__): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$start_tray(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def start_tray(self, port, server_stop_event): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$tray_icon$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def tray_icon>(candidates, base, path, img, e, size, draw, accent): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

static PyObject *impl_core$tray_icon$tray_icon$gt$(PyThreadState *tstate, PyObject **python_pars) {
    /* Original Python source equivalent:  def tray_icon>(e): ... */
    /* Body unrecoverable. Disassemble around the native
     * module_init entry point to inspect the compiled code. */
    Py_RETURN_NONE;
}

/* ============================================================
 *  Module initialization entry point
 *  Nuitka template: template_module_body in CodeTemplatesModules.py
 * ============================================================ */
PyObject *module_code_core$tray_icon(PyThreadState *tstate, PyObject *module,
                                     struct Nuitka_MetaPathBasedLoaderEntry const *loader_entry) {
    module_core$tray_icon = module;
    moduledict_core$tray_icon = MODULE_DICT(module_core$tray_icon);

    static bool init_done = false;
    if (init_done == false) {
        createModuleConstants(tstate);
        init_done = true;
    }

    /* The sequence of CREATE_MODULE_VARIABLE + MAKE_FUNCTION calls
     * that Nuitka generates here for import statements and class
     * definitions is not recoverable from metadata alone.
     * It lives natively at:
     *    PE virtual address  0x141A4D0F0
     *
     * Recovered imports (detected from module constants): */
    /*   import logo.ico */
    /*   import logo.png */
    /*   import core.settings */
    /*   import core.tray_icon */
    /*   import TrayIcon.__init__ */
    /*   import TrayIcon._get_dashboard_url */
    /*   import TrayIcon._open_browser */
    /*   import TrayIcon._on_open */
    /*   import TrayIcon._on_settings */
    /*   import TrayIcon._on_restart */
    /*   import TrayIcon._on_exit */
    /*   import TrayIcon._on_show_notification */
    /*   import TrayIcon._setup_menu */
    /*   import TrayIcon.run */
    /*   import TrayIcon.notify */
    /*   import TrayIcon.should_restart */

    return module;
}

